### ISSUE TITLE
Managing Experiments from mlflow ui

### ISSUE THREAD

**Issue by kleysonr** [mlflow/mlflow#1028]
I would like to be able to delete and create Experiments folders as well as move runs from one Experiment to another from the mlflow ui.

Best Regards.
Kleyson Rios.

**Comment by LucaMoschella** [comment]
I would love to be able to move runs from one experiment to another!

I'd like to have one experiment that gathers all the runs that make sense (e.g. the favorite/starred runs), moving there the interesting runs.

**Comment by petibear** [comment]
+1 for this feature. Moving, deleting and "starring" would be a useful addition. 

Deleting of an experiment is already possible via mlflow cli, however not available in UI. Would be nice if it was accessible via UI. 
Moving of runs between experiments is not possible at all, however it seems like it would be implementable by moving runs between folders for the file store and updating a db records for sqlalchemystore, not sure about that rest store. 
And starring, well, that would be indeed useful.

**Comment by petibear** [comment]
Wrt deleting, if it is indeed this "simple" (can somebody confirm, pls?), I'd happily try implementing it in cli to learn how to contribute here.

**Comment by LucaMoschella** [comment]
> Wrt moving runs between experiments, if it is indeed this "simple" (can somebody confirm, pls?), I'd happily try implementing it in cli to learn how to contribute here.

In the file store I confirm that moving runs between experiments is simple, since at the moment I'm doing it manually when I have to.

**Comment by petibear** [comment]
Wrt moving of runs between experiments, I looked at the code more in detail and it seems to me that one would need to add a support at 3 places:
- `file_store.py` - to indeed move the run between experiments directories, but also to update the run's yaml config (as it contains experiment id; not sure why this needs to be in yaml, looks redundant to me) + (*)
- `sqlalchemy_store.py` - update the run's reference to its experiment + (*)
- `rest_store.py` - add new protobuf messages, create client & server handlers (in `store/rest_store.py` & `server/handlers.py`)

(*) But that's not all. It seems to me that artifacts would also need to be moved because their location is right now defined not only on the level of individual runs, but also on the level of their experiments (see `meta.yaml` of an experiment + `experiments` table with sqlalchemystore). The latter seems unnecessary; however to keep these references correct, one would need to move also artifacts. Alternatively, one could remove these experiment-level references.

**Comment by rquintino** [comment]
all would be highly useful, think they are actually the top limiting factors for getting the most of mlflow tracking (tracking works well, exploring and analysis not so much)

I would not mind not having move option between experiments, in case there was another concept of analysis/report, where I can pick up any run I want (like previous framework we used for tracking).  Think that makes more sense for us, and really is what we're using, exporting regularly a huge single dataframe with all runs , params, metrics, and explore that externally to mlflow ui (dash, pandas, powerbi, whatever).

we also cache this all runs dataframe because realistically we don't need to go to mlflow backend (specially filesystem) every single time, most often there are not new runs or data changes. 

that and the way filesystem backend stores every param/metric in a single file, killing us :) studying that, but for another thread
thanks!

**Comment by svenpelzer** [comment]
Can you please add a delete button of experiments to the UI, so it is easier to remove "old" experiments?

**Comment by LucaMoschella** [comment]
Any news on this?

**Comment by fzyzcjy** [comment]
+1 For the "move run between experiments". Will we have that?

**Comment by clara2911** [comment]
+100 for moving runs between experiments. Please!!

**Comment by ykpgrr** [comment]
+1 for move runs between experiments

**Comment by mike576** [comment]
+1 for move runs between experiments

**Comment by sluki** [comment]
I think this should be divided to two different issues:
 - move runs between experiments (much easier, very useful)
 - organize experiments (much harder, less useful)

ps: difficulty and usefulness are my opinion only
ps2: you can move runs with mlflow-export-import tools (it says it can, i have not tried it)

**Comment by mHash1m** [comment]
+1 for moving runs b/w experiments

**Comment by ReHoss** [comment]
+1

**Comment by amesar** [comment]
https://github.com/mlflow/mlflow-export-import

This package provides tools to copy MLflow objects (runs, experiments or registered models) from one MLflow tracking server (Databricks workspace) to another.

**Comment by LeoLionel** [comment]
A feature to move a run from one experiment to another would be highly appreciated! ⭐️

I work with a setup that uses ML Flow for logging and when I start a run and forget to provide an experiment name it ends up in the one titled "Default". Currently I see no easy way to move it away from there.

**Comment by elenavolkova93** [comment]
+1

**Comment by ReHoss** [comment]
For local storage user, you can move folder from a xp to an other, don't forget to update metadata if necessary.
