### ISSUE TITLE
Unable to see mlflow ui at http://127.0.0.1:5000 on macOS Sierra version 10.12.3

### ISSUE THREAD

**Issue by datariders** [mlflow/mlflow#108]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  macOS Sierra version 10.12.3
- **MLflow installed from (source or binary)**:   binary . (I did "pip3 install mlflow")
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**:  0.2.1
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **npm version (if running the dev UI):  5.3.0
- **Exact command to reproduce**:

"mlflow ui"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

Here is the terminal console logs:

$ mlflow ui
[2018-07-01 23:35:56 -0700] [3302] [INFO] Starting gunicorn 19.8.1
[2018-07-01 23:35:56 -0700] [3302] [INFO] Listening at: http://127.0.0.1:5000 (3302)
[2018-07-01 23:35:56 -0700] [3302] [INFO] Using worker: sync
[2018-07-01 23:35:56 -0700] [3305] [INFO] Booting worker with pid: 3305
[2018-07-01 23:46:16 -0700] [3302] [CRITICAL] WORKER TIMEOUT (pid:3305)
[2018-07-01 23:46:16 -0700] [3305] [INFO] Worker exiting (pid: 3305)
[2018-07-01 23:46:16 -0700] [3402] [INFO] Booting worker with pid: 3402

When I opened a browser and tried reaching to "http://127.0.0.1:5000/".  I dont see the dashboard of all my runs.  I only see "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

It took some time to see the [CRITICAL] WORKER TIMEOUT error in the logs.  My hunch is, the npm module, which serves the http://127.0.0.1:5000 request timeout as it is not up.  Hence the error.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by mateiz** [comment]
Thanks for reporting this. A few questions about it:
- Are there any additional messages beyond "worker timeout"? Maybe on stderr or stdout?
- Do you have a `mlruns` directory in the location where you ran `mlflow ui`? If so, are any runs created using an older version of MLflow? (This isn't expected to be a problem but would be good to know.)

**Comment by dennyglee** [comment]
Out of curiosity, by any chance will `http://localhost:5000`work even though `http://127.0.0.1:500` will not?   I currently am able to repro this (both issues) with the following configuration:
* OS Platform: `macOS High Sierra 10.13.2`
* MLflow Install: `pip install mlflow`
* MLflow version: `0.2.1`
* Python version:  `Python 3.6.5 :: Anaconda, Inc.`
* npm vresion: `not installed`

**Comment by mateiz** [comment]
OK, maybe we should just document this then unless there is a workaround to the Gunicorn thing. It's too bad that the logs print out 127.0.0.1 but we can at least warn about this issue.

**Comment by stenpiren** [comment]
I have similar issue. When I first cloned the repository and followed the tutorial by passing train alpha and l1 all worked. I started the UI at the directory having mlruns and it did work in the browser but then after exploring the interface and few refreshes here and there, it suddenly went down without warning at the terminal, while the same terminal shows it as running normally. I took it down, restarted computer and started mlflow ui again and at the browser was getting NOT FOUND. No clue what the issue is now.

**Comment by dennyglee** [comment]
Hi @stenpiren - to confirm you're running Ubuntu 16.04 in Virtualbox on macOS?  If so - which version of the OS?  Thanks!

**Comment by stenpiren** [comment]
hi @dennyglee . it's Ubuntu 16.04.4 LTS

**Comment by adrian555** [comment]
@stenpiren did you happen to run the `mlflow ui` from the root path of your cloned repo, for example,  from the $HOME/mlflow which is your project path?

Similar error happened to me and I finally figured out what caused it. Python searches the module by sys.path and the current directory is the first path it searches. The mlflow project directory structure has `mlflow/mlflow/server` in it. So when the `gunicorn` tries to run the app, it is not getting from the installed one. Instead, it is looking at the cloned project. And because the js/build does not exist (aka server is not built) yet, the worker fails.

**Comment by mycaule** [comment]
Same problem, I followed the tutorial and got 404 error

**Comment by thunterdb** [comment]
@stenpiren I had the same problem, which was due to the fact that the web files (js, css) were not built. I did the following in a virtualenv environment:
 - build the UI and wheel files, following this section: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact
 - install mlflow within the virtualenv environment: `pip install -e .`

Then you can run `mlflow ui` using the latest source version.

**Comment by sabeerzaman** [comment]
Creating the symlink like @tszumowski pointed out caused other issues when trying to view the UI. In the context of following the tutorial, I think @mycaule meant:

1. Change into the `example` folder in the first place to run the the `train.py` with varying parameters (vs running it from the root folder of the repo) - `mlflow` creats the `mlruns` folder in the working directory that the script was invoked from (in this case `<project_root>/example`
2. Run `mlflow ui` from the same `<project_root>/example` folder, and it will now successfully load the mlflow runs in `<project_root>/example/mlruns`

At least that's what worked for me 😄

**Comment by smurching** [comment]
Thanks all for the helpful suggestions! @adrian555's explanation is correct - running `mlflow ui` from within a checkout of MLflow runs the dev UI from source, which doesn't come pre-built with the JS/CSS assets needed to render the UI.

We recommend running `mlflow ui` from a directory other than your checkout of MLflow (the same workaround many of you already discussed above), using the `--file-store` option if needed to specify the path to the logging directory to view with the UI. #289 updates the quickstart/tutorial/README to clarify this :).

**Comment by akashagarwal7** [comment]
My issue here was that I installed the `mlflow-skinny` pip dependency, instead of `mlflow`.
