### ISSUE TITLE
Unable to see mlflow ui at http://127.0.0.1:5000 when mlflow is running in docker container

### ISSUE THREAD

**Issue by datariders** [mlflow/mlflow#109]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:  No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Docker container running in macOS Sierra 10.12.3
- **MLflow installed from (source or binary)**:  Dockerfile
- **MLflow version (run ``python -c "from mlflow import version; print(version.VERSION)"``)**:  0.2.1
- **Python version**:   Python 3.6.5 :: Anaconda, Inc.
- **npm version (if running the dev UI):  5.3.0
- **Exact command to reproduce**:

mlflow ui

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

We did a git clone of the mlflow repo and built a docker image from the Dockerfile.  We spun up a docker container from that image.  The container was up and running.  We mapped the port to the default 5000.  We tried opening a browser and reaching to "http://127.0.0.1:5000/".  Unfortunately, we still could not get the dashboard.

Note:  I am conversant with dockers, kubernetes, etc.  Let me know how can help.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by mateiz** [comment]
Does using `http://localhost:5000` fix this one too?

**Comment by Debdutto** [comment]
@datariders I had the same issue. The problem here is gunicorn is binding to just 127.0.0.1 inside the container. The workaround is to pass host while starting your `mlflow ui`. Or you can also go into `/app/mlflow/utils/cli.py` and change the default host to `0.0.0.0`.

I did this and was able to access the UI from chrome on my host using `localhost:5000` or `127.0.0.1:5000`

Let me know if this works out for you.

**Comment by jakubczakon** [comment]
@datariders @Debdutto 
You could also have your MLflow projects hosted on [neptune.ml][1] knowledge sharing hub. 
There are two benefits to it:

 - you can avoid all the problems with MLflow's UI,
 - you can share your experiment runs with everyone. For example, [check out this project][2]. 

We have recently released free Neptune version and developed integration with MLflow which, I think, brings a lot of value to the community.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995

**Comment by rquintino** [comment]
Note, using mlflow server seemed to work for this, mlflow ui seemed not to accept --host parameter?

having said that, we're currently using notebook server proxy extension, so that mlflow ui is exposed through jupyter url like .../proxy/5000/ . No problems until now, no ports to handle on container, and we inherit jupyter auth.

(recent fix for mlflow ui relative url now allows this to work properly through proxy
https://github.com/mlflow/mlflow/pull/1413 )

**Comment by kamalaVJ** [comment]
@rquintino @mateiz 
None of the above solutions worked for me. However, I realized the node/js build scripts were not present in the cloned repo, hence I installed them.
From the directory "/mlflow/mlflow/server/js", I call npm start, which gives me this error, any idea what could be wrong?
Error: Cannot find module '/mlflow/mlflow/server/js/node_modules/react-scripts/config/webpack.config.dev'

**Comment by mateiz** [comment]
Ah, in general, the MLflow repo is not designed so that you can just run the server from source. You'd have to do `npm install` first and then `npm start` as described here: https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#running-the-javascript-dev-server, but instead, I would recommend building a distributable Python wheel artifact (https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact) and running that in your Docker container.

**Comment by kamalaVJ** [comment]
Hi @mparkhe , 
I have tried that too and I get the same error - 
Can't connect to ('127.0.0.1', 5000)
Running the mlflow server failed

I am trying to self host mlflow on local machine and not using azure databricks.

**Comment by sp7412** [comment]
This issue was a major gotcha for me. Took several hours and then I found this post.

**Comment by bubblefoil** [comment]
I just went through this frustration until I found [this G group conversation](https://groups.google.com/g/mlflow-users/c/7cezJGzfnic?pli=1). I had to start mlflow server with the -h parameter. When running mlflow ui, the -h parameter is ignored. You can see the effect in the log: `[INFO] Listening at: http://0.0.0.0:5000`

**Comment by thinkbigdatanalytics** [comment]
Here is how I solved it and it works.

`docker run -t -i -p 8000:8000 -e GUNICORN_CMD_ARGS="--bind=0.0.0.0"  docker.io/library/diabetes`

**Comment by imancrsrk** [comment]
@bubblefoil Thanks for your reply. I am able to see the log [INFO] Listening at: http://0.0.0.0:5000 but I am still not able to access the UI at http://127.0.0.1:5000/ or http://localhost:5000/

Do you have any input?

**Comment by johan010** [comment]
You can try:
docker run -it --network host mlflow

**Comment by imancrsrk** [comment]
@johan010 @bubblefoil Actually I resolved it following all comments above but it still didn't work because I was running the ML flow server at the wrong time. 

I changed my set up to start the MLflow server at port 5000 in the docker container along with jupyterlab and then exposed port 5000 also in docker run command as shown below - 

`docker run -it -p 8888:8888 -p 5000:5000 docker-img` 

Here 8888 is the port on which jupyterlab is run and 5000 the MLFlow server port

**Comment by adrienpacifico** [comment]
Windows users  : `mlflow server -h 0.0.0.0` instead of `mlflow ui` did the trick for me.

**Comment by Kshitizkhandel** [comment]
This worked for me:
docker run -p 5000:5000 -it docker-image/bin/bash
mlflow server -h 0.0.0.0(Using mlflow server instead of mlflow ui)

**Comment by 75andybermond** [comment]
Thank you @Kshitizkhandel it worked fine for me this way.

**Comment by 75andybermond** [comment]
> This worked for me: docker run -p 5000:5000 -it docker-image/bin/bash mlflow server -h 0.0.0.0(Using mlflow server instead of mlflow ui)

Thank you @Kshitizkhandel it worked fine for me this way.

**Comment by manel00** [comment]
Hello

Sorry i cannot connect to mlflow from jupyter in the same docker, something is wrong with mlflow, it retrieves this:

![MicrosoftTeams-image (3)](https://github.com/mlflow/mlflow/assets/8410687/5251667c-a060-4e80-a45f-2ab1f47717af)

**Comment by TheStoneMX** [comment]
what worked for me was I did uninstall mlflow and then installed it again.
