### ISSUE TITLE
Replicating tutorial example "wine quality" gives error

### ISSUE THREAD

**Issue by coconutattitude** [mlflow/mlflow#1110]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.6.3
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
python train.py
### Describe the problem
Running tutorial example from https://mlflow.org/docs/latest/tutorial.html with the data specified gives following error: KeyError: "['quality'] not found in axis"

**Comment by adam-m-mcelhinney** [comment]
I am encountering the same issue, but I am also not finding the wine.csv file. I believe there are a few possible solutions (which I hope to work on when I find time).

1. Instead of reading the csv locally, I propose that we instead just read it remotely from the url.
2. The reason you are getting the key error is that the separator in the file is a ;.

`    data = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
                       , sep=';')`

That should fix both issues. I will try to submit a PR once I can find time to set up the environment according to the contributor guidelines.

**Comment by aarondav** [comment]
Ah, this is a good point. Our wine quality example in the tutorial should probably not require the user download the mlflow repository to run!

@adam-m-mcelhinney Do you have time to submit a PR?

**Comment by HackyRoot** [comment]
Hey @adam-m-mcelhinney,
I would love to work on this issue if it's not assigned to anyone else yet.

**Comment by adam-m-mcelhinney** [comment]
@HackyRoot go for it. You'll just need to replace the `pd.read_csv` reference with the one above and change 1-2 column names. If you need any help, I'll be around this weekend

**Comment by HackyRoot** [comment]
@adam-m-mcelhinney Do we follow GitFlow model here? I'm a bit confused in which branch I should push the changes.
