### ISSUE TITLE
MLflow filter works in the UI, but not via REST query

### ISSUE THREAD

**Issue by eboiarskaia** [mlflow/mlflow#1219]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: custom
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 0.9.0
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
```
"filter": "params.`fro-model-version` like '2.0.0'" 
```
 works in UI, but not via REST query.

```
"filter": "params.projectId = 4314"
```
 works for both

### Describe the problem
Running 
```
curl -XPOST https://shardname.cloud.databricks.com/api/2.0/preview/mlflow/runs/search \ 
-H "Authorization: Bearer TOKEN" \ 
-d '{ 
"experiment_ids": [ 2300 ], 
"filter": "params.`fro-model-version` like '2.0.0'" 
}'
```
returns an empty set, but

```
curl -XPOST https://shardname.cloud.databricks.com/api/2.0/preview/mlflow/runs/search \ 
-H "Authorization: Bearer TOKEN" \ 
-d '{ 
"experiment_ids": [ 2300 ], 
"filter": "params.projectId = 4314" 
}'
```
Both filters work in the UI. Possibly a bug in the way the filters in the REST query are parsed before they reach the MLflow backend @mparkhe ?

**Comment by mparkhe** [comment]
I am sorry this issue slipped through the cracks. A similar issue has been reported before (`TODO`: add duplicate bug). 

The issue here is that on command line backtick gets evaluated before the command is sent over. So "filter": "params.`fro-model-version` like '2.0.0'"  so the column name is dropped. 

Solution replace backtick with `"`. or remove it all together.
