### ISSUE TITLE
Clarify open-source project governance in CONTRIBUTIONS ?

### ISSUE THREAD

**Issue by cristianopris** [mlflow/mlflow#1252]
There doesn't seem to be any information on how the MLFlow open-source is managed. Can you please add clarification on the process around contributions, commits and strategic design decisions for the MLFlow open-source project ? Is there a specific governance model in place ?

Thanks,
Cristian Opris

**Comment by mateiz** [comment]
We're working on a doc about this actually, but the short story is that we expect to discuss all major decisions on GitHub Issues or the mailing list (including posting design docs, etc), to stick to a strict versioning policy around APIs (don't break stuff that worked before), and to add new committers after they make substantial contributions. This is what's been happening so far. Please just open issues about specific things you'd like added in.

**Comment by cristianopris** [comment]
Thank you Matei. Just to clarify, in terms of governance my understanding is that this is a Databricks driven project where ultimately decisions on accepting contributions and strategic direction lies with Databricks folks ?

**Comment by mateiz** [comment]
Not necessarily -- the goal is to grow a set of committers from other companies too, and then get consensus from the committers on changes. For example, we added some committers from RStudio who review a lot of the R changes. In practice, things will be accepted into the project if the committers have interest in maintaining them. If something is not accepted, we also want to provide APIs so that people can easily develop it outside of this repo. For example, we expect that a lot of more esoteric contributions such as language bindings for less commonly used languages might fall into that category. There's already been a patch to make the tracking stores pluggable through an extension API for example: https://github.com/mlflow/mlflow/pull/881, as well as context-specific run metadata: https://github.com/mlflow/mlflow/pull/930.

We (Databricks) have also had regular sync with the bigger contributors, and we might turn this into a regular video sync. If you want to reach out about a larger feature, you can start by pinging people on our Slack channel or opening an issue here.

**Comment by mateiz** [comment]
Still working on this, so I'm reopening it.

**Comment by ankitmathur-db** [comment]
@dmatrix @pogil @mateiz - I think our processes around this have evolved quite a bit since the last response and since we became a part of Linux Foundation. Maybe you all can comment more on it

**Comment by dmatrix** [comment]
@pogil and I are working on updating the CONTRIBUTIONS to include Governance, technical steering committee, and other related guidelines with respect to Linux Foundation.

**Comment by dbczumar** [comment]
This has been addressed by https://github.com/mlflow/mlflow/pull/3219.
