### ISSUE TITLE
Make Python API methods public

### ISSUE THREAD

**Issue by kirillmakhonin** [mlflow/mlflow#1255]
I'm working on integrating MLflow into another system and I need to install uWSGI to model's conda environment (that is created by MLflow run method), but I can not get project's conda env. name without using `mlflow.projects._project_spec` "private" module and `mlflow.projects._get_conda_env_name` "private" method.

I guess, that these (and maybe some others methods) could be public to allow externals tools to integrate with MLFlow (not just using API for tracking server querying).

**Comment by mateiz** [comment]
What about reading the MLproject YAML file directly? We didn't make these public because we don't necessarily want to maintain compatibility for them in all releases (they're just internal utility functions), but the YAML format is stable. If that's annoying to use, we may also consider making these public.

**Comment by kirillmakhonin** [comment]
I've pushed PR #1284 with another approach. @mateiz, what do you think about it?
