### ISSUE TITLE
[FR] Support for async functions in the fluent tracing API

### ISSUE THREAD

**Issue by MPKonst** [mlflow/mlflow#12756]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

The proposal is to modify the `@trace` decorator in `mlflow/tracing/fluent.py` to handle async functions. Essentially, this would involve two changes to the code -- defining the wrapper as async and modifying the [function call](https://github.com/mlflow/mlflow/blob/092306d9101b9870b9826c47ac4d4913c425a80c/mlflow/tracing/fluent.py#L141) to be an `await` statement. 

One way to do this while minimising code repetition would be to define the initial and final logic that the wrapper introduces in a coroutine as follows:

```
def pre_post_logic_coro():
    # code for initial logic, e.g. entering the span context manager
    ...
    result = yield
    # code for finalising logic
    ...
```
 Then the sync wrapper can be defined with `coro.send(fn(*args, **kwargs)` and the async version can be defined with `coro.send(await fn(*args, **kwargs)).` The decorator can decide which wrapper to return by calling `inspect.is_coroutine_function` on the decorated function.

### Motivation

> #### What is the use case for this feature?
The use case I have in mind is tracing of a function that calls out to an LLM api. In any kind of involved LLM or agentic workflow, these are exactly the kinds of functions that one wants to trace and since they are API calls, they are usually async functions. 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by B-Step62** [comment]
@MPKonst Thank you so much for the well thought proposal!

I fully agree on the demand of tracing async functions, it would be really awesome if we can support it🙂

Aside from the coroutine handling in the wrapper, there is one challenge needs to be addressed. When creating a root span, MLflow talks to the backend store to get the unique ID for the trace (`request ID`). This is currently blocking operation and every children spans creation wait for that, so we can construct children spans with that request ID.
* Indeed, if we are fine with creating children spans without request ID, it should be possible to make it non-blocking. The request ID will only be required when logging the entire trace at the end. However, this means that the `request_id` field is not available in child spans at runtime, which might be inconvenient for some use cases.
* Alternatively, we can say "the root span creation may add some blocking time for async function". For your use case, I imagine the root span is defined as a sync function that make multiple LLM calls as async tasks (child spans). Therefore, having some blocking time in the root span might be acceptable.

Considering the size of effort for achieving the first option, I would suggest starting from the second option (unless you have a better idea!).

I also read the OpenTelemetry's roadmap for async support [here](https://github.com/open-telemetry/opentelemetry-python/issues/62#issuecomment-1515418483), but it appears that the remaining items don't block us, for how we are using their SDK now.

If you feel comfortable on the idea, would you mind building some POC as a starter? Since it could be large effort to complete the implementation, I would like to start from validating our idea for some simple cases.

**Comment by MPKonst** [comment]
Thanks @B-Step62 for the detailed reply. I think it's ok for the creation of the root span to be blocking since, as you point out, the root span will probably be created once per run and there would be many child spans.

I'd be happy to put a POC together later this week.

**Comment by B-Step62** [comment]
@MPKonst Sounds great! Ok, so let's set the following as the goal of this work;

1. Update the `@mlflow.trace()` decorator to returns async function when wrapping async function.
2. The pre/post logic around `yield` statement doesn't have to be async. The only notable overhead would be the root span creation, which should not be a major concern for common use cases.
3. The code should follow DRY principle and avoid repetition between sync and async handling.

> I'd be happy to put a POC together later this week

Awesome! Please feel free to ping me if you make progress or face any blocker. Thank you for the willingness to the contribution😄

**Comment by MPKonst** [comment]
@B-Step62 -- PoC PR is ready for you to take a look whenever you get a chance 🙂

**Comment by B-Step62** [comment]
The PR is merged and the feature will be available in the next MLflow release. Thank you so much for the contribution @MPKonst !
