### ISSUE TITLE
[FR] Add flavor for AutoGluon's predictors

### ISSUE THREAD

**Issue by automatize1** [mlflow/mlflow#13214]
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

AutoGluon is a widely used library for automl, but there is no flavor for it. I think that users would benefit from having the option to seamlessly integrate their AutoGluon training routines to mlflow.

### Motivation

> #### What is the use case for this feature?
Logging experiments with AutoGluon

> #### Why is this use case valuable to support for MLflow users in general?
Because AutoGluon is a relevant automl framework that is commonly used in ML tasks.

> #### Why is this use case valuable to support for your project(s) or organization?
Because MLflow is a great way to track ML experiments, but I encountered drawbacks when trying to include AutoGluon's training in the tracking routine.

> #### Why is it currently difficult to achieve this use case?
Because AutoGluon has some of its own classes (e.g. TabularPredictor, TabularDataset, TimeseriesDataset, etc) that are not easily integrated to the logging by using mlflow.pyfunc.PythonModel.

### Details

There is an [open issue on AutoGluon's repo](https://github.com/autogluon/autogluon/issues/1404) regarding this integration. I think that mlflow would benefit from adding this flavor.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by B-Step62** [comment]
Hi @automatize1. Unblocking AutoGulon users to manage experiments in MLflow seems to be a fruitful idea! However, we are facing some resource constraint due to the large number of the built-in flavors. As we are not very knowledgeable about the AutoGulon library, we would not be able to maintain the integration.

Thereby, I would suggest an alternative collaboration model, which seems to be a better fit for this case. We have a concept of **community flavor**, where people can implement the new flavor integration in their repository. Here are some reference documentations to get started!🙂
* https://mlflow.org/docs/latest/community-model-flavors.html
* https://mlflow.org/docs/latest/models.html#custom-flavors
