### ISSUE TITLE
Feature request: Allow 'step' in UI to be set to the order in which the metrics were logged

### ISSUE THREAD

**Issue by ahmed-shariff** [mlflow/mlflow#1432]
The old API, had the x-axis set to the the order in which metrics were logged, which can be interpreted as steps. Would be more convenient to have an option to not have to set the `step` value and the order in which the metrics were logged to interpreted as the steps. One possible way to do this would be to add an auto-increment the step when logging.

**Comment by smurching** [comment]
Hi @ahmed-shariff, thanks for bringing this up. With the current metrics UI, it is possible to set the metric x-axis to relative or absolute wall time, which should allow you to view metrics in the order they were logged (as timestamps are generated on the client). Does this not fit/satisfy your use case?

**Comment by ahmed-shariff** [comment]
Hey there, @smurching, the new UI is alot better than it was before; :+1:  for that
In a particular workflow of mine, I log the metrics at the end of each epoc. Hence, for me the order in which the metrics were logged viewed as steps is more useful that the timestamp. Perhaps display both step(the parameter passed/order in which they were logged) and timestamp?

**Comment by dbczumar** [comment]
Hi @ahmed-shariff, for the time being, we recommend explicitly specifying the step values for metric values if you require "logging order" view. We considered adding support autoincrementation of the "step" parameter across MLflow's fluent APIs, but there are significant design hurdles to cross in order to ensure that autoincrementation behaves sensibly. As a result, autoincrementation support is  not currently on our roadmap, but we'd be happy to take open source proposals for how this might look. For reference, here's the RFC for "step" value support: https://docs.google.com/document/d/17yHR_xOvoEJQBT-D-y4QGfc3OvHqP-eGWwfMcGBIH2k/edit?usp=sharing.

**Comment by ahmed-shariff** [comment]
@dbczumar Thank you for sharing the proposal. As a more simpler solution, perhaps `_get_metric_history` can verify if all `step` values are 0, and when that is true, return the step values as auto-incremented valus instead of 0? Or the time-stamp can be displayed as a tuple of (time-stamp, logging order)?
