### ISSUE TITLE
Access large data from within a Docker environment

### ISSUE THREAD

**Issue by samgd** [mlflow/mlflow#1441]
Feature Request.

Many algorithms are trained on large quantities of data (GB++) that cannot be included in the repository or Docker image. However, MLFlow Docker environments currently only have access to data baked into the repository or image or must download a large dataset for each run. This is not a practical way to run experiments and prevents many non-trivial models from being trained. e.g. pulling ImageNet for each run when training an image classifier. 

A potential solution is to enable the user to mount a volume (e.g. local directory containing the data) into the Docker container?

**Comment by nlaille** [comment]
I would like to have this feature as well. 
Maybe with the usage of parameter of type `path` ?

**Comment by sbourke** [comment]
Would it be ok if you download the data from a network drive when the docker container starts up ?

**Comment by samgd** [comment]
No, I think we should avoid having each experiment download potentially tens or hundreds of GB of data over the network each time it starts. If that were viable, this also has issues with Docker itself (your system would need large disk/memory, MLflow docker layer become huge, etc)

**Comment by dbczumar** [comment]
Hi @samgd , assuming that you're referring to Docker containers in the context of MLflow Projects, the `docker_env` attribute of your MLproject configuration file supports a list of mounts that can be used to provide access to your large files / data within the Docker container, without the need for copying. Each mount point is exposed to the container using the `docker run -v` flag. More information can be found in the MLflow docs: https://mlflow.org/docs/latest/projects.html#specifying-an-environment, and here's an example:

```
docker_env:
  image: mlflow-docker-example-environment
  volumes: ["/local/path:/container/mount/path"]
  environment: [["NEW_ENV_VAR", "new_var_value"], "VAR_TO_COPY_FROM_HOST_ENVIRONMENT"]
```

I'm going to go ahead and close this issue, since it appears that this functionality is already supported. Please feel free to reopen it if this `volumes` attribute does not meet your use case.
