### ISSUE TITLE
Feature Request: SageMaker Batch Transform (for offline inference)

### ISSUE THREAD

**Issue by andremoeller** [mlflow/mlflow#1472]
MLFlow supports deploying models to SageMaker using Endpoints for real-time inference: https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/cli.py

Is there interest in adding SageMaker Batch Transform support for offline inference as well?

The usage story is: users would supply their model, an input S3 bucket and content type, an output S3 bucket and Accept type, and instance types and counts. SageMaker Batch will run a job using input S3 data and storing inferences in output S3 bucket.

Thanks.

**Comment by pierorex** [comment]
+1.
At my company, we have tons of models that we use only on Batch Transform.
Right now we're trying to include MLFlow into our current toolset but without this feature, it would be a nightmare.

**Comment by strawberrypie** [comment]
It would be great to have such an option.

**Comment by rasensio** [comment]
+1 to this functionality. I have customers deploying models that can be inferred offline and they need this feature

**Comment by gm-spacagna** [comment]
Any update from dev team about the feasibility?

**Comment by edgBR** [comment]
Here #2745 the topic is re-open @gm-spacagna @rasensio @strawberrypie @pierorex

**Comment by YQ-Wang** [comment]
Hi @ankit-db , I am an ml engineer who uses MLflow in my personal projects and day-to-day work heavily. There was a use case for interacting Sagemaker Batch Transform with MLflow in my recent project, so I implemented the Python APIs and the CLI supports. I noticed this Feature Request has not been implemented yet. I would like to discuss my design with you and create a PR once you approve.

Design for the MLflow Sagemaker Batch Transform integration:
1. The API that deploys the model as a Sagemaker batch transform job: 
Since the batch transform job needs to have a unique name, it first checks whether the provided name has already been existing. If no, then it uploads the model from the MLflow artifact to S3 and creates a Sagemaker model. After that, it creates the transform job with the provided parameters via boto3 API. If synchronous=True, it will keep monitoring the process and returning logs until it passed the timeout seconds. 
`mlflow.sagemaker.deploy_transform_job(job_name, model_uri, s3_input_data_type, s3_input_uri, content_type, s3_output_path, compression_type='None', split_type='Line', accept='text/csv', assemble_with='Line', input_filter='$', output_filter='$', join_resource='None', execution_role_arn=None, bucket=None, image_url=None, region_name='us-west-2', instance_type='ml.m4.xlarge', instance_count=1, vpc_config=None, flavor=None, synchronous=True, timeout_seconds=1200)`
Please notice synchronous follows the same logic as the other existing APIs.

2. The API that terminates the Sagemaker batch transform job with the specified name:
It terminates the transform job with the provided name via boto3 API. If archive=False, it will delete the model as well as the model artifact in S3. Both synchronous and timeout_seconds have the same logic as the other APIs.
`mlflow.sagemaker.terminate_transform_job(job_name=None, region_name='us-west-2', archive=True, synchronous=True, timeout_seconds=300)`
I also include the CLI support for the above APIs. Detailed info will be provided in the document.

Please let me know what you think. I will create a PR once you agree.

Thanks

**Comment by ankit-db** [comment]
Thanks @YQ-Wang and others for pointing out that this would be useful support to add! I think it'd make sense for us to look to the community for design/implementation help on this so thanks for taking that initiative. I'll make an action item for myself to review this with the team and will spend some time thinking about the batch transform API and get back to you with questions

**Comment by edgBR** [comment]
Hi @YQ-Wang 

What happens if MLflow is already using S3 as artifact storage? Shouldn't w have only one model URI?

BR
/E

**Comment by YQ-Wang** [comment]
Hey @edgBR ,

Thank you for the question. Followings are the use cases of the model_uri parameter in the code. 
`/Users/me/path/to/local/model | 
relative/path/to/local/model | 
s3://my_bucket/path/to/model | 
runs:/<mlflow_run_id>/run-relative/path/to/model | 
models:/<model_name>/<model_version> | 
models:/<model_name>/<stage>`
The model_uri follows the same standard as the endpoint deployment API  to make the MLflow/Sagemaker API consistent. So yes, if you use S3 as the artifact storage, you can use the S3 key to create the Sagemaker model, which will eventually be attached to the batch transform job.

**Comment by YQ-Wang** [comment]
Hey @ankit-db ,

Here is the implementation I made for the Sagemaker Batch Transform support - https://github.com/mlflow/mlflow/pull/4304. I created a pull request just to make it easier for you to review the overall logic as well as the code. Please let me know if you have any suggestions. 

Thank you!

**Comment by smanchem** [comment]
Hi, this would be a useful feature to have. Any update on when/if it'll be available? Thanks

**Comment by qtz123** [comment]
Hi @tomasatdatabricks and @ankit-db , 

I happen to need this function in my project. Are there any updates?

**Comment by tomasatdatabricks** [comment]
Hi @YQ-Wang , thank you for the PR and sorry for dropping the ball on this! I will try to review this ASAP.

@qtz123 We will try to get this in ASAP, in the meantime, you can checkout the PR #4304 linked above. If you do, please let us know here if something does not work for you.

**Comment by YQ-Wang** [comment]
Hey @tomasatdatabricks and @qtz123, I accidentally closed the old PR #4304 while fixing some comments length issues. Here is a new PR with the updated code: #4410 
Thank you!

**Comment by qtz123** [comment]
Hi @tomasatdatabricks.I've tried to deploy an xgboost model to a transform job. The function looks good to me.

**Comment by dbczumar** [comment]
Closing this out now that this functionality has been merged into MLflow. Thanks @YQ-Wang !
