### ISSUE TITLE
[Feature Request]: Support for RedisAI for deployment

### ISSUE THREAD

**Issue by hhsecond** [mlflow/mlflow#1570]
### Describe the problem
Being the new kid in the DL/ML deployment world, RedisAI is getting ready for general availability ver soon. Considering the fact that RedisAI can solve a couple of problems with existing deployment toolkits, and the ease to scale the deployments, it will be really good to have RediAI integrated into MLFlow. Here are some features I think relevant to the AI/OPS community. PS: I am part of the development team behind RedisAI

- Multiple backends (TF, PyTorch, ONNXRuntime and a bunch of other backends through ONNXRuntime like sklearn, xgboost, coreml etc)
- Multiple devices (CPU & GPU already. TPU & some others are upcoming)
- Language agnostics
- HA
- Redis ecosystem
- Can run everwhere Redis runs (like a raspberry pi)
- Auto batching (upcoming)
- Keep the data local (for example in case of sequence network, you don't have to pass around the hidden data, instead can keep it in Redis itself)
- Clustering

**Comment by mparkhe** [comment]
What sort of integration are you looking for. Several companies and users have written backends that use MLflow API to talk to specific backends for tracking, executing runs ... etc. Are you trying to use MLflow API with Redis backend or looking to contribute to MLflow?

**Comment by hhsecond** [comment]
Could you point me to one such example of case 1 you have specified? I was thinking more of contributing to MLflow.

**Comment by mparkhe** [comment]
If you look at ["Used By" link](https://github.com/mlflow/mlflow/network/dependents) at the top of MLflow github page, several of those have backends implemented. 

Additionally, several integration conversations on [MLflow slack channels and email user groups](https://mlflow.org/#community). I would particularly look at [#mlflow-plugins](https://mlflow-users.slack.com/archives/CFYUVSHEZ) slack channel.

[I am closing out this issue since this is more of a question rather than an issue. If you have additional questions please feel free to reach out over slack or email]
