### ISSUE TITLE
Http GET in the request body

### ISSUE THREAD

**Issue by adnan333bd** [mlflow/mlflow#1596]
this GET api is expecting experiment_id in the request body, 
https://mlflow.org/docs/latest/rest-api.html#get-experiment

isn't it violating REST api standard?, the httpClient api of angular even does not allow it.
could we put the experiment id in the url?

**Comment by adnan333bd** [comment]
aha it is **also** working with query param, like this /api/2.0/preview/mlflow/experiments/get?experiment_id=0
the doc is not that clear then ...

**Comment by ankitmathur-db** [comment]
All GET requests are expected to work with query parameters by definition of the RFC for HTTP GET (https://tools.ietf.org/html/rfc2616#section-9.3). It says "The GET method means retrieve whatever information (in the form of an
   entity) is identified by the Request-URI.". Our implementation does this, even though the new RFC since 2014 is less "strict" about this definition (https://tools.ietf.org/html/rfc7231#section-4.3.1) and does not include this reference.

If your problem is that our implementation does actually work if you send content in the request body, the RFC does not explicitly have a problem with this "A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing
implementations to reject the request." (https://tools.ietf.org/html/rfc7231#section-4.3.1) Our docs explicitly define the semantics that our implementation expects, so we think this is acceptable to do.

Thanks for reporting and please let us know if something breaks, or feel free to make a PR with docs changes that you think would be better.
