### ISSUE TITLE
Feature Request: Give MLFlow Experiment overview UI option to display average metric value instead of latest logged value

### ISSUE THREAD

**Issue by Rjdrenth** [mlflow/mlflow#160]
When you log multiple values for a metric in a single run, the MLFlow Tracking UI run overview table shows the latest logged metrics as the value for each metric. This makes sense when training e.g. Neural Networks and you want to log performance after multiple iterations. 

It makes less sense when logging different metric values from different Cross Validation folds, which I think are logical to log under the same run. In this use-case it would be more beneficial to display the average metric value. 

Both ways have merit, so if there could be a toggle somewhere to change between these two options that would be perfect.

**Comment by 5ke** [comment]
+1 to not caring about the latest metric value: I rather want to see the best one :-D

**Comment by aarondav** [comment]
Definitely a good idea. Currently, we'd recommend logging one last metric at the end of training for the best/average value -- MLflow is not really intended as a timeseries database, and the "last metric value" thing simplifies the API to make it feasible for several backend implementations with reasonable performance.

Given a small number of runs (e.g., in a run comparison view), though, this would still definitely make sense, since we serve all logged metrics to the UI.

**Comment by chenmoneygithub** [comment]
Close inactive issue.
