### ISSUE TITLE
[BUG] no data in mlflow UI

### ISSUE THREAD

**Issue by ajoeajoe** [mlflow/mlflow#1755]
as the following pic shows:

![image](https://user-images.githubusercontent.com/11608953/63222918-92214600-c1e0-11e9-8c12-f2acf0dccf41.png)

and ouput folds in mlruns:

![image](https://user-images.githubusercontent.com/11608953/63222937-e3c9d080-c1e0-11e9-95fd-31e35c3d4f77.png)

**Comment by MainHanzo** [comment]
1. pls check the folder in the screenshot corresponds to the "Artifact location" in your first pic which is ./mlruns/0. Normally ths pwd is the dir you launched cmd "mlflow ui"

2. Perhaps you have import the runs from elsewhere. which means your "meta.yaml" doesn't match  your "Artifact location". pls check it

**Comment by ajoeajoe** [comment]
@MainHanzo  thx ，it is ok when iI run the machine learning models command  on the same directory as run "mlflow ui"

**Comment by dbczumar** [comment]
@ajoeajoe By default, the `mlflow ui` command will use the current working directory for backend storage. In order to display runs in a particular directory with the MLflow UI, you must either run the `mlflow ui` command from that directory or specify the `--backend-store-uri` argument as follows:

```
mlflow ui --backend-store-uri /path/to/my/directory
```

It sounds like you were able to resolve the issue, so I'm going to go ahead and close this GitHub ticket. Feel free to reopen it if the issue persists.
