### ISSUE TITLE
[FR] Add mypy / typing checks

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#1756]
## Describe the proposal
Add mypy checks in travis. 

### Motivation
Annotations and typing module catch errors by static analysis. In order to improve the code base, I suggest to start to annotate the code and add mypy analysis in travis.

### Proposed Changes
* Add mypy checks in travis 
* Use python2 compatible annotations (using comments) https://mypy.readthedocs.io/en/latest/python2.html

**Comment by smurching** [comment]
@jdlesage thanks for filing this (we're currently going through the backlog of issues). This should hopefully become easier after we drop Python 2 compatibility, which we're planinng to do early next week - will resurface this issue in the community Slack channel etc then, hopefully we can get some help with this effort :)

**Comment by sansagara** [comment]
DS projects keep geting complicated with time, and type checks are usually checked/enforced more each time. I have a project with lots of dependencies and MLflow is the only one giving me mypy issues. I would love that to not be the case :)

**Comment by smurching** [comment]
@sansagara makes a lot of sense! Since my last comment, we've dropped Python 2 support in MLflow, so it should be easier to introduce type-checking to the MLflow codebase (note that we've already started to use types when introducing new Python code to MLflow, e.g. https://github.com/mlflow/mlflow/pull/2775)

We'd welcome contributions to start adding type annotations to other parts of the codebase! I'd recommend making these contributions incrementally (e.g. updating one module at a time to have type annotations) to facilitate code review, vs having one large PR.

**Comment by sansagara** [comment]
Love it! I will try and get some time to contribute a bit on the core files. Maybe start with cli.py

**Comment by harupy** [comment]
@smurching I think we should drop Python 3.5 if we add type annotations because Python 3.5 does not support [variable annotations](https://www.python.org/dev/peps/pep-0526/)

**Comment by mcitoler** [comment]
Are there any updates on this topic or any plans to include it in the roadmap: https://github.com/mlflow/mlflow/milestone/3?
