### ISSUE TITLE
Deploying Custom-model on SageMaker Error

### ISSUE THREAD

**Issue by lucasmengual92** [mlflow/mlflow#179]
### How to deploy in SageMaker custom-made model using MLflow.
I´ve been if there will be a basic demo sometime, because I´m having struggle deploying using Amazon SageMaker. and also from the AWS side, since I need to retrieve the **app** name (I don´t know hat it is), **ARN** (managed to get it), and **S3** name (also managed), and still getting credentials error. 
```
raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

### Describe the problem
This is the command I managed to make so far, but is giving me a credential error as mentioned:
```
mlflow sagemaker deploy -a mlflowknn -m mlruns/0/b28171ca29f94e16a5f1c355bf8b78ac/artifacts/model -e arn:aws:sagemaker:us-east-2:992223509516:model/mlflowknn -b mlflowdemo
```
### Source code / logs
Anything else you want to check, I´m happy to pass here as well.

**Comment by tomasatdatabricks** [comment]
Hi Lucas. MLflow only provides an interface to Sagemaker. You can try the run-local option without any permission (you need to have Docker for that) but if you want to actually deploy to Sagemaker service  you need to set up permissions first. See https://boto3.readthedocs.io/en/latest/guide/configuration.html.

And in order to use Sagemaker, you will also need Sagemaker rights:
https://docs.aws.amazon.com/sagemaker/latest/dg/api-permissions-reference.html https://boto3.readthedocs.io/en/latest/guide/configuration.html

**Comment by smurching** [comment]
Thanks @lucasmengual92 @tomasatdatabricks - I'll go ahead & close this issue for now since the question was addressed, but feel free to reopen :)
