### ISSUE TITLE
Share mlruns folder across machines

### ISSUE THREAD

**Issue by Nithanaroy** [mlflow/mlflow#184]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
  - No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
  - Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
  - Mac OS X High Sierra
- **MLflow installed from (source or binary)**: 
  - Using pip
- **MLflow version (run ``mlflow --version``)**:
  - 0.3.0
- **Python version**: 
  - Python 3.6.5 :: Anaconda, Inc.
- **npm version (if running the dev UI):
  - NA
- **Exact command to reproduce**:
  - mlflow ui

### Describe the problem
Sharing the `mlruns` folder across machines with different parent to project folder structure does not work and fails with 500 Internal Server. On checking a run's `meta.yaml`, found that `artifact_uri`, `source_name` are absolute paths which are no longer valid on the latter / destination machine.

### Steps to Reproduce
- On Machine 1:
  - goto `cd ~/` folder
  - track some work using mlflow.tracking API
  - check in the mlruns folder into a version control
- On Machine 2:
  - goto `cd ~/Desktop`, different than the one used in Machine 1
  - Clone the above repo created on Machine 1
  - Run `mlflow ui` in the project folder where `mlruns` folder exists
  - goto http://127.0.0.1:5000/experiments/2, i.e. to the corresponding experiment to see 500 errors and folder not found exceptions in the mflow server logs

Note: The above can be easily replicated on a single machine by cloning `mlruns` folder

### Possible solution
There might be a reason why the mlflow devs might have chosen to use absolute paths in the `meta.yaml` file. However having the ability to be able to easily share mlruns folder could be quite helpful. A simpler way for starters could be by storing relative paths from the nearest ancestor `.git` folder.

**Comment by smurching** [comment]
Hi @Nithanaroy, thanks for bringing this up. We did opt for absolute paths in the source name & artifact URI because they allow us to display absolute paths to artifacts in the UI / show an `mlflow run` command in the UI that can be used to reproduce the original run (independent of working directory).

For sharing / accessing information about runs across machines, we recommend running a  tracking server accessible to both machines ([see docs](https://mlflow.org/docs/latest/tracking.html#running-a-tracking-server)) - admittedly this is a bit more heavyweight to set up than checking `mlruns` into version control, but it has the advantage of easily staying in sync across machines. Thanks & hope that helps!

**Comment by Nithanaroy** [comment]
Oh cool. Thanks for clarification.

How about starting the mlflow ui server such that it can be accessed by any other machine in the same network as well. Currently `mlflow ui` launches **127.0.0.1:5000/experiments**. 

Tensorboard does it by default and that lets us share the URL to colleagues while in office, without needing to setting a dedicated box for hosting the ui server.

**Comment by apurva-koti** [comment]
As @smurching notes, running a tracking server accessible across machines should address the use case in question.
