### ISSUE TITLE
[FR] Automatic reload

### ISSUE THREAD

**Issue by sim-san** [mlflow/mlflow#1849]
### Description / Motivation
At the moment the website is not automatically reloaded when a new run is run or tags, parameters or metrics are updated. The automatic reload would make the use of mlflow more efficient. 

### Proposed Changes
I'm not a web developer. But I think with react framework it should be pretty easy.

**Comment by andychow-db** [comment]
Thank you for the feature request. I think this makes sense. My initial hunch would be to fetch the information after some period of time.

**Comment by briankosw** [comment]
This would be really helpful! I think a workflow similar to how TensorBoard works - automatically fetch information after some period of time AND fetch information when the some form of reload button is pressed - would be really convenient instead of manually reloading the entire website.

**Comment by wyessen** [comment]
Has any progress been made on this?

**Comment by Trollgeir** [comment]
We would also love this as a feature. F5 is bothersome when you're watching training-graphs.

**Comment by gloryVine** [comment]
I would also welcome this.

**Comment by deepfindr** [comment]
I would also love this feature. :)

**Comment by simonhessner** [comment]
Thsi feature would be extremely useful. Especially because whenever you press F5 the page scrolls up and if you want to watch for new artifacts, you have to scroll down again.

Another good feature would be if the UI would remember choices that I make, e.g. setting log-scale, selected losses, etc even if I open another run in the same experiment.

**Comment by sim-san** [comment]
Party solved by https://github.com/mlflow/mlflow/pull/5017

**Comment by dbczumar** [comment]
As indicated by @sim-san, this has been addressed for metrics via https://github.com/mlflow/mlflow/pull/5017. Additionally, the MLflow Experiment page now displays a count of new runs that have been created since the last page load, which helps the user know whether or not they need to refresh the page. In light of these improvements, I'm going to go ahead and close this issue. Please feel free to reopen it if significant work remains to be done.

**Comment by mazer-ai** [comment]
Another upvote for this -- in particularly it can useful to have the run table view update automatically - particularly if you have a custom list of columns and are using that to monitor aspects of training across multiple runs..
