### ISSUE TITLE
[BUG] _search_runs takes a lot of memory

### ISSUE THREAD

**Issue by t-henri** [mlflow/mlflow#1865]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **MLflow installed from (source or binary)**: Source master branch
- **MLflow version (run ``mlflow --version``)**: 1.2.1.dev0
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
I tried the tracking server with the latest changes including the latest_metrics table, and I noticed that when trying to list runs for my experiments, the server was OOM killed, and it didn't happen before. 

I took a look in the code and I saw that in _search_runs we now we perform one big query joining the runs, parameters, tags and latest_metrics table. The result of this query is really huge since for each run it will return number of tags * number of metrics * number of parameters lines. 
Since we have runs with an average of ~55 tags, 20 parameters and 15 metrics, we have 16500 lines by run. Our biggest experiment has more than 1000 runs, and it causes out of memory errors, and if it did succeed I am not sure it would be faster than before.

A solution could be to paginate the runs directly in SQL using LIMIT and OFFSET instead of doing it at the end of the _search_runs function, so the server wouldn't have to get so many rows. It would mitigate the out of memory error, but I am still not sure that it would be faster than before since the query returns a huge number of lines.

For information, my server has 6GB of RAM.

### Code to reproduce issue
Create an experiment with runs that have a high cardinality of parameters, tags and metrics, and try to call _search_runs on this experiment.
If you want I can add a test with such an experiment.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.

**Comment by dbczumar** [comment]
@t-henri Can you clarify where the error occurs? Is your SQL database suffering experiencing OOM exceptions, or is this an issue with the MLflow tracking server instance?

In the case of the MLflow Tracking server instance, it's not immediately apparent why reducing the number of database would produce this behavior because the tracking service fetches the same set of data from the database on the current `master` branch as it does on the release branch (release version `1.2`); the updates to `master` simply reduce the number of queries required to fetch this information.

**Comment by t-henri** [comment]
Hello @dbczumar, the error occurs in the MLflow tracking server instance.

You indeed reduced the number of queries made to the SQL database, but you also increased a lot the number of rows we receive.

Before your changes, we made one query to get run informations and then 3 queries to get the corresponding params, tags and metrics. So the total number of lines we got for a run was 1 + number of params + number of tags + number of metrics.

Now, with the latest metrics table, we do a single query that join the tables runs, params, metrics and tags, and it returns the cartesian product between the params, metrics and tags. So now we have number of params * number of tags * number of metrics lines for each run. 

I added a test in sqlalchemy_store were I create 1000 runs and add 100 params, 100 tags and 100 metrics in each run. This test is successful with the 1.2 version but fails on master. When I run it locally (inside a docker container with 6GB of ram), with master branch, my container is OOM killed, and on branch 1.2 it succeed and the max ram is ~600MB.
You can check these two branches and their corresponding build on Travis:
From 1.2: 
https://github.com/criteo-forks/mlflow/pull/9
https://travis-ci.com/criteo-forks/mlflow/builds/129074615
From master:
https://github.com/criteo-forks/mlflow/pull/8
https://travis-ci.com/criteo-forks/mlflow/builds/128954439
You can see that the python tests were successful with the 1.2 version, and with the master version the test timeouts on the test I added (test_big_experiment).

**Comment by dbczumar** [comment]
@t-henri Thank you for your detailed analysis. I've reproduced the problem and am working on a patch that should reduce memory usage while minimizing the number of database roundtrips.

**Comment by dbczumar** [comment]
@t-henri I've filed https://github.com/mlflow/mlflow/pull/1878 to correct this issue by using a `subquery` load for eager loading instead of a `joinedload` (see https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#subquery-eager-loading for more information). Please take a look! It would be very helpful if you could try it out and confirm that it resolves your memory utilization issues.

Just to confirm, are you running your production MLflow database on a separate instance/machine, or are you running it on the same machine as your tracking server?

My current working theory is that the `joinedload` procedure is very memory-intensive for the *database instance* because the cross product of latest metrics, parameters, and tags are held in memory for each run. However, the SqlAlchemy documentation for the `joinedload` technique is very adamant in stating that the query result should be identical to the result set produced by other loading techniques (e.g., lazy loading); this would imply that the tracking instance receives the same amount of output. Please let me know if your setup/experience contradicts this reasoning (e.g., if your tracking instance exhibits OOM exceptions while the database instance does not exhibit any issues with memory utilization). For reference, here's the documentation on `joinedload`: https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#the-zen-of-joined-eager-loading. In the mean time, I will continue to investigate this hypothesis.

**Comment by t-henri** [comment]
Hello @dbczumar, yes I am running my database on a separate instance than my MLflow tracking server, and the memory issue only occurs in the tracking server. The memory issue occurs because even if sqlalchemy returns the same objects than with lazy loading, it has to perform the huge query at some point.

I tried your fix and it is much better, there is no more memory issues and it is also faster, that is a great fix.

I still have some questions I would like to ask you about the search_runs method:

- I fear it will not scale indefinitely, since we perform a 'SELECT *' in the database, with the growth of the database we might reach a point where it becomes slow again.
- I see that after this SELECT, we loop through the runs in python to sort/filter them and then we return only a subset to paginate, which means we potentially make a lot of operations that we don't need. Don't you think it would be better to filter/sort directly in SQL and then we could also paginate in SQL too using limit and offset ?

Also, do you think I should make a PR to add the test I created for this issue ? So we can detect early a similar error ?

**Comment by dbczumar** [comment]
@t-henri You're absolutely correct that we should eventually push pagination logic into the SQL execution layer for performance and scalability reasons. We'd love to review a PR implementing this behavior!

Regarding a test PR, that would be very useful! Feel free to file a separate PR or push to the branch associated with #1878!

**Comment by t-henri** [comment]
Hello @dbczumar, so I created this PR with the test I linked you before: https://github.com/mlflow/mlflow/pull/1880 

Feel free to ping me if you have any remark.
