### ISSUE TITLE
Keras models or networks built using Sequential() API cannot be stored in the MLflow.

### ISSUE THREAD

**Issue by dmatrix** [mlflow/mlflow#189]
Keras models or networks built using Sequential() API cannot be stored in MLflow as artifacts using
[tf.estimator](https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator) for conversion. This conversion API expects models constructed using tf.keras.Models. 

Best if MLflow directory used Keras API to save and load models rather than having to translate it via tf.keras.Models or tf.estimator, which does not support models constructed with Keras sequential API.

**Comment by juntai-zheng** [comment]
Is the error occurring in `log_saved_model(saved_model_dir, signature_def_key, artifact_path)` or when you try to use `load_pyfunc(saved_model_dir)` for inference? We were planning on changing the MLflow Tensorflow API to more closely match the sklearn and SparkML model APIs anyway, so your input might be useful for that. What do you think @smurching?

**Comment by smurching** [comment]
Thanks @dmatrix @juntai-zheng. IMO we should have a separate MLflow API for Keras models rather than require/encourage users to log their models via the TF APIs, would love to see a PR adding Keras model support. https://github.com/databricks/mlflow/pull/170 could be a good example to see the necessary types of changes, basically:
* Add an `mlflow.keras` module, implement `save_model`, `log_model`, `load_model`, and `load_pyfunc`
* Update the models docs (https://github.com/databricks/mlflow/blob/master/docs/source/models.rst) to mention the new Keras model type (i.e. add to [this listing] of model types (https://github.com/databricks/mlflow/blob/master/docs/source/models.rst#scikit-learn-sklearn))

**Comment by dmatrix** [comment]
Yes, having a model type of Keras and using its respective APIs makes sense. That way, Keras developers can directly use it. Also, we keeping the mlflow.<model_type> APIs consistent is a better interface: save_model, log_model, load_model & load_pyfunc.
