### ISSUE TITLE
[FR] Custom docker images for models

### ISSUE THREAD

**Issue by matallanas** [mlflow/mlflow#1963]
## Describe the proposal
Add the possibility of attaching a dockerfile for creating custom images and installing different tools inside the docker.

### Motivation
Right now the deployment of a model in microservices is limited. In order to export it to the Azure ML or Amazon Sagemaker or to create a docker image locally, you cannot specify a dockerfile that could facilitate the creation of a microservice through different steps. Although this service can be done in Azure ML directly, it cannot be done in mlflow.
With custom dockerfiles you can specify steps for installing different components like compilers or tools of the base image OS.
This feature is necessary to create customized microservices.

### Proposed Changes
They are really small changes, we should make an append of the dockerfile file that creates mlflow with the file that the user passes and this can be the same for all frameworks because right now mlflow is already writing this dockerfile below without the user knowing.

**Comment by raghav20** [comment]
any update ?

**Comment by asiron** [comment]
+1 Would it be possible to add a new field e.g .`docker_env` to `MLmodel` file, similarly to `MLProject`?

**Comment by cfusting** [comment]
I added the ability to specify a base image in build_docker and disable installing Java (since it's big). Will open a pull request shortly.

**Comment by cfusting** [comment]
PR 2189 open.

**Comment by matallanas** [comment]
That is fantastic to know. Thank you so much.

**Comment by tallen94** [comment]
I think this is a related topic. Im trying to use a custom image when deploying to AWS Sagemaker. I can use the `mlflow sagemaker build-and-push-container` to create the base image and then create another image with some custom python packages installed. However the default behavior when serving the pyfunc is to activate a conda environment (unless an environment variable is specified https://github.com/mlflow/mlflow/blob/bbf8886a2cbf4fa371f0a67157fdd3df3dfa47dd/mlflow/models/container/__init__.py#L121) 
which prevents the model from accessing the system dependencies.

In the custom image I create I can get around the conda env creation by adding 
```
ENV MLFLOW_DISABLE_ENV_CREATION=true
```
However, I think this line reveals a bug if the conda env is not created 

I think this line should be removed https://github.com/mlflow/mlflow/blob/30a90ec9cbffa5c0d0212368b9f2a7e8c8a3fc81/mlflow/models/container/__init__.py#L127

since if the conda creation happens, it will be activated here https://github.com/mlflow/mlflow/blob/30a90ec9cbffa5c0d0212368b9f2a7e8c8a3fc81/mlflow/models/container/__init__.py#L106

Ive been able to validate that removing that line ends up fixing the issue. Thoughts?

**Comment by MarkusShepherd** [comment]
I think I ran into issues which could be similarly resolved by more control over the Dockerfile.

I want to pip install a library from a private GitHub repo, which is not possible right now because the Docker build context does not have access to it. I circumvented the problem for the time being by including the `whl` into my docker images, but this likewise required a custom Dockerfile.

Long story short, more flexibility and control over the Dockerfile would solve my problem without hacky workaround.

**Comment by omanges** [comment]
In which release are you planning to release this feature?

**Comment by zionsofer** [comment]
Any updated to this? This is really needed for us to install private dependencies

**Comment by dbczumar** [comment]
Hi @zionsofer, apologies for the delay. We'll revisit this shortly. Is the solution presented in https://github.com/mlflow/mlflow/pull/2189, which provides base image customization, satisfactory for your use case, or would you prefer to specify your own template with placeholders for MLflow-specific operations, such as `{install_mlflow}`? Are both of these useful?

**Comment by zionsofer** [comment]
Hi, @dbczumar , thanks for the reply.
The solution proposed in #2189 is sufficient in its idea, but I believe the implementation lacks two things:
1. Add support for supplying a base image in the CLI of SageMaker (to be able to use the direct build/push functionality through mlflow.sagemaker)
2. When supplying your own docker base image with custom properties/private dependencies, you'd sometimes want to include it in the relevant virtualenv/conda env that the model will be working in. In the proposed solution, a new venv is created through miniconda regardless of the custom image, which will just make the base virtualenv redundant, or if we trry to create one before on the same path that mlflow does, will fail since the directory already exists.
I believe adding support for the base virtualenv would work, of course.

Specifying our own templates would work as well, of course, but that means that we are not "aligned" if there are any changes to the mlflow docker template. Not ideal, but could work as well.

**Comment by chenmoneygithub** [comment]
Seems to be closed, see https://github.com/mlflow/mlflow/issues/6084 for details.
