### ISSUE TITLE
[BUG] MLFlow UI run page shows all metric values rounded to 3 decimal points

### ISSUE THREAD

**Issue by andrey-tsykunov** [mlflow/mlflow#2006]
### System information
- **OS Platform and Distribution (RHL 7.6)**:
- **MLflow installed from (binary, pip)**:
- **MLflow version (1.3.0)**:
- **Python version 3.6.8**:

### Describe the problem
While "all runs" MLFlow UI page shows metric values as they are reported (without rounding), individual run page displays all metrics rounded to 3 decimal points

### Other info / logs
all runs:
![all_runs](https://user-images.githubusercontent.com/12177913/67693086-83d96e00-f977-11e9-81d9-ec7fba0e3062.PNG)
run:
![run](https://user-images.githubusercontent.com/12177913/67693109-8a67e580-f977-11e9-9597-d4437e24f448.PNG)

**Comment by harupy** [comment]
Metrics values get rounded by `formatMetric`. This function needs to be fixed to render small metric values properly.

## formatMetric

```javascript
  static formatMetric(value) {
    if (Math.abs(value) < 10) {
      return (Math.round(value * 1000) / 1000).toString();
    } else if (Math.abs(value) < 100) {
      return (Math.round(value * 100) / 100).toString();
    } else {
      return (Math.round(value * 10) / 10).toString();
    }
  }

  // if value = 0.0001, (Math.round(value * 1000) / 1000) returns 0
```
https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/utils/Utils.js#L40-L48


## getMetricValues

```javascript
const getMetricValues = (latestMetrics, getMetricPagePath) => {
  return Object.values(latestMetrics).sort().map((m) => {
    const key = m.key;
    return [
      <Link to={getMetricPagePath(key)} title="Plot chart">
        {key}
        <i className="fas fa-chart-line" style={{paddingLeft: "6px"}}/>
      </Link>,
      Utils.formatMetric(m.value)
    ];
  });
};
```

https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/components/RunView.js#L256-L267

**Comment by harupy** [comment]
I think `toExponential` should be used if the metric value is smaller than a specified threshold.

https://www.w3schools.com/jsref/jsref_toexponential.asp

```
>>> (0.000438).toExponential(3)
'4.380e-4'
```

**Comment by harupy** [comment]
@andrey-tsykunov I created a PR. What do you think?

**Comment by andrey-tsykunov** [comment]
@harupy  Would it be consistent with the way it is shown on "run search" page?

**Comment by harupy** [comment]
Yes, I will fix the run search table.

**Comment by andrey-tsykunov** [comment]
@harupy Would it be enough to just make sure formatting is the same (without changing it to exponential)?

**Comment by harupy** [comment]
@andrey-tsykunov That would be fine too.

**Comment by mirekphd** [comment]
This should be made more flexible IMO... Hard-coding `Utils.formatMetric()` (see e.g. its [unit tests](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/common/utils/Utils.test.js#L15)) to 4 significant digits means that MLflow shaves off 2 decimal places of RMSE, making a hundred or so of Kaggle competitors with `np.round(my_RMSE, 3) == 0.899` indistinguishable...: 
https://www.kaggle.com/c/competitive-data-science-predict-future-sales/leaderboard

**Comment by aarondav** [comment]
@mirekphd Do you have a proposal for a better algorithm on how many digits/sig figs to show? The original proposal was about avoiding losing precision with small numbers.

**Comment by mirekphd** [comment]
> @mirekphd Do you have a proposal for a better algorithm on how many digits/sig figs to show? The original proposal was about avoiding losing precision with small numbers.

Yes, we did observe precision loss. For instance we have these six models becoming indistinguishable, apparently due to loss of 1 significant digit in RMSE (zeros seem to be counted to the limit of 4 digits displayed by mlflow's UI):
fin_mod_oot_r2    | 0.358 | 0.356 | 0.355 | 0.35 | 0.354 | 0.354 | 
fin_mod_oot_rmse 0.077 | 0.077 | 0.077 | 0.077 | 0.077 | 0.077 | 

However, this may be related to our client-server combination, specifically the server version being prior to the above fix for #2006. Only client library is automatically kept up to date by our CI/CD (currently at 1.8.0), while server version is lagging, currently at 1.3.0 (from Oct 1, 2019, which is prior to the above fix from Nov 7, 2019). You think server upgrade would solve it?

Still, It would be best to be able to control precision in `log_metric()` for each metric separately, because while 3 places is fine for "large" metrics like R^2 or AUC, it is way too aggregated for RMSE or logloss, where 4 or 5 are needed.

**Comment by aarondav** [comment]
The server does serve the JavaScript, so upgrading may fix the precision issue. Note that the metrics are always logged with full precision, it's just the UI that is truncating the digits. So ordering, for example, would be correct given the full precision.

**Comment by 00sapo** [comment]
IMHO, the user should be able to decide between exponential and decimal format with a checkbox. #2022 only works for values < 1e-3. It doesn't make sense, because the exponential format is used to compare the order of magnitude of two numbers and is useful for any number, small or large.

I think that exponential format should be the default format, as it works well for any order of magnitude, as opposed to decimal format. This would also make the code in `formatMetric` easier and cleaner, without all those if.
