### ISSUE TITLE
[FR] Baseimage from Dockerfile

### ISSUE THREAD

**Issue by chuber1986** [mlflow/mlflow#2028]
Hi,

I think it would be nice if 'mlflow run' was able to use a Dockerfile to build the base image for the MLFlow image. So the base image is at every run consistent with the corresponding Dockerfile.

BR Christian

**Comment by dbczumar** [comment]
Hi @chuber1986 , this is currently supported by the `docker_env#image` attribute of the MLproject configuration (see https://github.com/mlflow/mlflow/blob/master/examples/docker/MLproject#L4). You can provide your own Docker base image using this field; I would recommend use a base image built on top of the MLflow Docker image produced by `mlflow build-docker`. For more information, see https://mlflow.org/docs/latest/projects.html#specifying-an-environment

Since this seems to be supported, I'm going to go ahead and close this issue. Please feel free to re-open the issue if the existing field doesn't meet your requirements.
