### ISSUE TITLE
Azure blobstorage key requirement

### ISSUE THREAD

**Issue by damejovanoski** [mlflow/mlflow#2081]
Hello,

I wonder why do I need to have the key on the client side and on the mlflow server side, is it possible to have it only in the server part to take care about the upload?

**Comment by mparkhe** [comment]
The advantage of the current design is that deployed `mlflow server` does not have to act as a file system proxy in order to stream large models from/to clients and serving systems. In most cases, artifacts will be stored on blob stores such that containers (or buckets as in the case of AWS) are accessible to all users of the experiment.
