### ISSUE TITLE
[FR] New component for table of runs

### ISSUE THREAD

**Issue by rom1504** [mlflow/mlflow#2084]
## Describe the proposal

I'm proposing a new component for the table of runs using https://github.com/tannerlinsley/react-table .
Benefits : 
* easy to sort (click on the right column)
* easy to filter (write your filter on top of the column)
* proper pagination

### Motivation
The use case for us at Criteo is to be able to compare many runs (for example we do some hyperparameter tunings in different teams) on several metrics / parameters / tags.

### Proposed Changes
On top of these already merged changes : 
* filtering in sql as implemented by @jcuquemelle in https://github.com/mlflow/mlflow/pull/2030
* sorting and limiting in sql as implemented by @jcuquemelle in https://github.com/mlflow/mlflow/pull/2059

I'm proposing : 
* a whitelisting option in search_runs to retrieve only some runs, tags, metrics : I will propose a PR for this soon
=> these 3 changes make the backend fast enough (<500ms in our case)

and 2 small additional changes : 
* return the total number of runs in search_runs : this is required to have a proper pagination in the ui : I will soon propose a PR for this
* a new endpoint that retrieve the list of tags, metrics, params for an experiment : required to be able to select what columns to show in UI : I will soon propose a PR for this

All these backend changes can then be used in a new ui based on react-table.

It looks like this : 

![image](https://user-images.githubusercontent.com/2346494/68680214-98198f80-0561-11ea-8da1-99917dd2b5f8.png)

I will also submit a PR for this change (the code is mostly ready and working, but there's a few things to finish)

(cc @Zangr )

This should handle both https://github.com/mlflow/mlflow/issues/1839 and https://github.com/mlflow/mlflow/issues/1666

**Comment by mateiz** [comment]
This seems great. Can it show nested runs and let the user expand those too (runs with a parent run ID)?

**Comment by Zangr** [comment]
@rom1504 thank you for sketching the feature request! Glad to see continuous interest on improving the runs table. It's a good timing because I also plan to work on runs table next week to bring back the columns view. Is there a particular reason to choose ReactTable vs the current ReactVirtualized? If we were to bring in a new table component, I'd consider those ones with more out-of-the-box features.

cc @mparkhe for API changes
cc @gioa for design

**Comment by rom1504** [comment]
Hello,
Here is the first PR, it's for whitelisting columns, I put it on our fork first https://github.com/criteo-forks/mlflow/pull/38 ; you can already have a look, I'll put it in this repo next.
It's an important part because it allows the UI to be fast, which is crucial.

For the ui : 
I did not implement nested run yet, I can add it but I have a few questions : 
* what is the use case of this feature : why wouldn't users compare runs between "master runs" ?
* how should it work UX wise ? for example what should happen in kind of sorting, which runs get displayed first ? (current behavior is to sort regardless of nesting which is not intuitive)

The reason why I chose react table is because it already implements : 
* ordering by clicking on the column names (and even multiple column ordering)
* filtering on top of each columns
* pagination (page count, page numbering, selection of numbers of runs by page)
* calling the API when doing ordering, filtering, ...
Wheras I would have to reimplement all of this if using ReactVirtualized

So I think it has more features out of the box.

I will soon publish a PR for the ui, I hope that will make things clearer.

**Comment by rom1504** [comment]
That's the second pull request, to add the total run count in backend https://github.com/criteo-forks/mlflow/pull/43 ; important to implement pagination in UI. It's also useful in general

**Comment by mparkhe** [comment]
One of the concerns with adding "run count" with `SearchRuns` API is that it dictates how the backend would implement pagination. For instance the backend users would be required to
1. Either load all results from search query and then apply pagination filter to extract qualifying page of results
2. Do a dual query on backend one for counts (without pagination filters) and apply entire filter including pagination to extract necessary result. 

This is easier when doing limit and offset style of pagination but significantly harder when implementing cursor based tokens for pagination.

ref: [RFC for pagination](https://docs.google.com/document/d/1Ygti9oyMbi4DJNbaM0D49nNIKb8BLXwGYQ7WmrOKJ3s/edit?usp=sharing)

**Comment by rom1504** [comment]
Third pull request about being able to list all columns for a series of experiment https://github.com/criteo-forks/mlflow/pull/46

**Comment by mparkhe** [comment]
Hi @rom1504: Yes. The concern is with changing the API--specifically adding a separate `total_run_count` field in `SearchRuns.Response`. I am not sure how you intend on building the UI component described here and if that will **require** returned response to have this `total_run_count` value. Lemme clarify.

I am not sure if got a chance to look through the document I attached with my previous comment. We have deliberately tried to keep the token response as a generic string rather than a structured field. This gives the backend and frontend to have an opaque implementation for pagination. For instance, current open source pagination is an offset and limit based implementation -- where `offset` is returned in the json string. Another backend may choose to have a more detailed [cursor based approach](https://docs.google.com/document/d/1Ygti9oyMbi4DJNbaM0D49nNIKb8BLXwGYQ7WmrOKJ3s/edit?usp=sharing#heading=h.76z02dr2xfy6) for implementing pagination. In the case of the latter, it may be difficult to know what is the exact # of runs that qualify the original search criteria (depending on how the backend is implemented). As I mentioned, the original design for `SearchRuns` with pagination API was such that it was open to any implementation of UI and backend.

I fact #2059 achieves this for SQL backend by pushing pagination down to SQL layer for efficiencies and total # of runs is no longer available. To get this additional information, it would be necessary to do an additional `COUNT` query with the same filter and no pagination to achieve total row count.

One way of doing this would be 
1. Leave it to individual backend developers if they want to add total run count. If so, the token can have an optional `"total_run_count"` field. Add this to the dictionary before encoding the token. Some backends like `FileStore` will be able to implement that while `SqlAlchemyStore` and `RestStore` may choose to not implement that.
2. UI: add an optional component for optional component for `total_run_count` field. If present it will show the field else will skip "of ..." in the display. Before implementing UI components please have @Zangr and @gioa approve design for UI.

Another note: Other MLflow developers that have created their own backend and UI implementations conformant to MLflow API have used `plugin` implementation to inject backend implementation.

**Comment by rom1504** [comment]
Ok let me answer your concerns.

> I fact #2059 achieves this for SQL backend by pushing pagination down to SQL layer for efficiencies and total # of runs is no longer available. To get this additional information, it would be necessary to do an additional COUNT query with the same filter and no pagination to achieve total row count.

yes this is what I implemented there https://github.com/criteo-forks/mlflow/pull/43/files#diff-c56e37254d6acf031af8cf7d293c3622L663 (which is pretty simple and fast as you can see)

> Leave it to individual backend developers if they want to add total run count. If so, the token can have an optional "total_run_count" field. Add this to the dictionary before encoding the token. Some backends like FileStore will be able to implement that while SqlAlchemyStore and RestStore may choose to not implement that.

Sure I can make it optional and put the total run count return in the token if you prefer

About the ui, you can see on the first post the number of pages displayed, to be able to display that it's necessary to have the total number of runs for this filter.
I'm not sure how one could make an intuitive ui without that number of pages/runs.

**Comment by mparkhe** [comment]
> Third pull request about being able to list all columns for a series of experiment [criteo-forks#46](https://github.com/criteo-forks/mlflow/pull/46)

I took a look at the PR. It is an interesting idea, but I wonder what is the use case for fetching column names. Depending on the # of runs in list of requested experiments this column list might be very large. Some of the experiments we have seen have 100K+ runs and collecting **all** the distinct column names for metrics, params, attributes, and tags for qualifying experiments could be prohibitively expensive. Especially, if the runs use different ML algorithms records lots of unique params and metrics, these lists could be extremely large. This also adds new API surface that would need to be implemented in all backends.

What is the use case for knowing **all** metric, param, tag, and attribute keys for all runs in an experiment or set of experiments. Have you considered other design choices for this--for instance one of the options for the UI shown in the picture above, could be for these column lists be dynamically deduced in the UI from the data in runs returned, rather than adding a whole new API. With pagination, you will only have a subset of column names which can be reduced in the UI and kept in cache (which you might have to anyways if using a different API). As new pages are pulled from backend, this cache could be kept active.

As a reminder: before implementing UI components please have @Zangr and @gioa approve design for UI.

**Comment by rom1504** [comment]
The use case is to implement selecting the columns in the UI and to display only those. (Could you by the way have a look at my whitelisting columns PR mentioned above ?). So it's needed to retrieve all tags, params and metrics that could be relevant to be able to autocomplete on them and not only a few that are retrieved after pagination.

Retrieving the list of all metric, tags, params names seems to be pretty fast for 20k runs on sql. Doing a query without any join and simply aggregating the results can be fast up to million of rows.
If it happens to be slow for bigger experiments, we could consider adding filters to that endpoint, but do we really have this problem currently ?


About the UI, do you want me to submit more information/mocks to validate the ideas ?

**Comment by mparkhe** [comment]
> yes this is what I implemented there https://github.com/criteo-forks/mlflow/pull/43/files#diff-c56e37254d6acf031af8cf7d293c3622L663 (which is pretty simple and fast as you can see)

Yeah! The concern is that to get the count right, the query would have to be run twice. For instance the two lines of code below will involve 2 separate query executions on the SQL backend.

```
            total_run_count = queried_runs.count()
            queried_runs = queried_runs.offset(offset).limit(max_results)
```

One of the use cases for having a SQL backend was for performance which was further improved in #2059. Running the query twice would negate some of those gains. Especially, if the user does not care about total # of runs. Eg, if the user is interested only in the latest runs or API users that care about only the most relevant runs.

> Sure I can make it optional and put the total run count return in the token if you prefer

That would be the most convenient without adding a new API interface.

> About the ui, you can see on the first post the number of pages displayed, to be able to display that it's necessary to have the total number of runs for this filter.
> I'm not sure how one could make an intuitive ui without that number of pages/runs.

As I mentioned above, some UI users definitely care about total # of pages while API users usually want to pull **all** runs page by page or only the top-N runs ordered by a set of fields.

> After some more thought I have another proposal : what about adding a new endpoint that will return that number of runs and take the same filtering option as search runs ?
> It would also serve my purpose without changing anything about search runs API

How do you plan to use this? Is there any value add to a new API vs adding it to the token like we talked about above? Do you have your own UI for MLflow?

**Comment by rom1504** [comment]
Ok I understand your points, I will change my PR to make it optional and store the result in next page token.

About how I want to use it : I want to use it to provide to the UI component so the number of page (and page numbering) can be displayed. A separate endpoint may work as well, as the front could call let less often (maybe only once) to get the total number of runs. I think it's more coherent with your ideas about the opaque cursor to put it in the token however, so I'll go with that option.

**Comment by rom1504** [comment]
I would really appreciate some feedback on https://github.com/mlflow/mlflow/pull/2212 so this could move forward.

**Comment by Zangr** [comment]
New runs table with column filters is implemented in https://github.com/mlflow/mlflow/pull/2251
