### ISSUE TITLE
no support for sklearn_crfsuite  after serving the model, 

### ISSUE THREAD

**Issue by vikey725** [mlflow/mlflow#2155]
The model takes input like this:
[ {'bias': 1.0, 'width': 0.036, 'height': 0.006909090909090909, 'line': 42, 'length': 6, 'spacy_label': 'UNK', 'pos_tag': 'VERB', 'pattern': 'Xxxx', 'is_currency': False, 'is_title': True}, {...}, ...]

It takes list of dictionary as input, and output the for each word.

[https://sklearn-crfsuite.readthedocs.io/en/latest/](url)

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Provide a clear high-level description of the feature request in the following sections. Feature requests that are likely to be accepted:
* Are minimal in scope (note that it's always easier to add additional functionality later than remove functionality)
* Are extensible (e.g. if adding an integration with an ML framework, is it possible to add similar integrations with other frameworks?)
* Have user impact & value that justifies the maintenance burden of supporting the feature moving forwards. The [JQuery contributor guide](https://contribute.jquery.org/open-source/#contributing-something-new) has an excellent discussion on this.

### Motivation
What is the use case in mind?  Why is it valuable to support, and why is it currently difficult or impossible to achieve? Could the desired functionality alternatively be implemented as a third-party package using MLflow public APIs?

### Proposed Changes
For user-facing changes, what APIs are you proposing to add or modify? For internal changes, what code paths will need to be modified?

**Comment by tomasatdatabricks** [comment]
Hi @vikey725, thanks for posting! 

I see there are two issues:  

a) The model itself is a different concept from what is currently supported by mlflow since it uses context and predict is defined on sequences (i.e. the input to predict is list of lists of dicts).

b) The mlflow model interface takes pandas dataframe as input, which is not compatible with sklearn_crfsuite.

I think a) will not get solved in a while unless there is a lot of demand for this type of a model but we should be able to expose at least predict_single method from sklearn_crfsuite. The easiest workaround for now would be to log a custom pyfunc model wrapping around sklearn_crfsuite 
 model to do the input data translation. Would that be good enough for you for now? I

**Comment by vikey725** [comment]
It would be great, thanks a lot @tomasatdatabricks

**Comment by juntai-zheng** [comment]
Hi @vikey725, hopefully the post by @tomasatdatabricks was able to help you out. I'll close this issue for now, but if you have any other questions/suggestions, feel free to reopen!
