### ISSUE TITLE
[BUG] preview of text files in MLflow UI

### ISSUE THREAD

**Issue by macimovic** [mlflow/mlflow#2164]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Pop OS 18.04
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.4
- **Python version**: 3.6.5
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: 

### Describe the problem
After I create an artifact that is logged to a remote artifact uri using FTP I cannot preview the text file in MLflow Tracking Server UI it forwards me to "Something went wrong" page.

### Code to reproduce issue
First start a remote MLflow Tracking Server with FTP as default-artifact-store. Then on client run the code:
import mlflow
with mlflow.start_run() as run:
    with open("output.txt", "w") as f:
        f.write("Hello world!")
    mlflow.log_artifact("output.txt")

Thanks!

**Comment by drod331** [comment]
I ran into the same problem, did you ever figure out a workaround?

**Comment by AlbertoPereto** [comment]
Hi there, I've expiriencing something similar with @macimovic at MLFLow 1.6.0. The artifact uploading is working apropriately but when I've try to download by MLFlow UI the page "Something went wrong" appears and no error log is shown at server console. 

The problem seems to be with UI layer. When I've run the MLFlow UI with browse console opened, a error message was thrown:

```
react-dom.production.min.js:151 Error: Can't find child.
    at ArtifactUtils.js:50
    at Array.forEach (<anonymous>)
    at Function.value (ArtifactUtils.js:46)
    at t.value (ArtifactView.js:171)
    at t.value (ArtifactView.js:66)
    at t.value (ArtifactView.js:87)
    at t.value (ArtifactView.js:211)
    at p (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at i (react-dom.production.min.js:176)
```

In fact, the function _findChild_ at _ArtifactUtil.js_ was not caring about the value "" of variable "_part_". I my case, the variable _path_ contained the value: "/artefatos/1/5d6fdd11e9d84c78a95cbd565c2e031f/artifacts/Treinamento.xlsx" and after the "split" operation, the value of "_parts_" with index=0 contained a blank string.

```
  static findChild(node, path) {
    const parts = path.split('/');
    let ret = node;
    parts.forEach((part) => {
      if (ret.children && ret.children[part] !== undefined) {  // <== the error occurs HERE!!
        ret = ret.children[part];
      } else {
        throw new Error("Can't find child.");
      }
    });
    return ret;
  }
```

Is it a bug or is it my misleading?

Thank you!

**Comment by michalgromiec** [comment]
@AlbertoPereto have you resolve this? How we can deal with this bug?

**Comment by aarondav** [comment]
Hmm, interesting, the path at this point should not be absolute, but relative. For example, if I click on a directory in my run artifact dir calls "foo/bar", then path is just "foo/bar", not something like "/artifacts/$experimentId/$runId/foo/bar".

Is this specific to the FTP repository? Maybe there's a bug there when listing artifacts that it returns absolute paths as opposed to relative ones.

**Comment by michalgromiec** [comment]
clicking on directory gives the same error - what I see is some errors in developers' tools (Error: Can't find child. at ArtifactUtils.js:50)

It can be specific to FTP repository, but being honest I don't know yet how can I set up artifacts with other repository types. My mlflow server is placed on docker at the external server.

I've checked also `client.download_artifacts` method - it works well, also I've checked FTP server, the file is uploaded perfectly and stored correctly.

**Comment by AlbertoPereto** [comment]
Hi @michalgromiec.

We currently using MLFlow 1.6 using FTP to artifact repository and MySQL to MlFlow Database.
When I've uploaded an artifact, the file is correctly stored at FTP but the UI fails when I try to download the file. 

The UI uses the column "artifact_uri" of table "runs". So, I discovered a "ugly" workaround, running the update below. 

This sql changes the reference of all current artifact URI stored at MySQL. Actually, I've changed the URI to a absolute format.
 
Notice that the SQL below fits for my specific enviromnent. **It is not a general solution**:
`update runs set artifact_uri=concat('/opt/artifact/artefatos/', experiment_id, '/', run_uuid, '/artifacts')`

**Comment by michalgromiec** [comment]
Thanks Alberto, works good on my side also. But if I understand well, after this update mlflow ui retrieves data from local path and client is not able to push another artifact? (because mlflow is trying to upload artifact to server local path?)

**Comment by glenguo06** [comment]
I've also had the same issue. My remote tracking server uses a local sqlite file as backend-store and an remote FTP (NAS) server as the artifact-store. MLflow UI has the artifacts 'listed' correctly but when I click on the file for preview/download purpose it shows: "Something went wrong". The artifact_uri in the sqlite database is registered as "ftp://<username>:<password>@<host_ip>:path_to_artifact".

Actually I was also trying to use the same FTP as the sqlite backend-store but I could never succeeded because of sqlite has no permission to write to the mounted FTP folder. I have tried to change the folder permission very extensively but same problem persist even the folder permission was already "drwx-rwx-rwx".

**Comment by chenmoneygithub** [comment]
Since there hasn't been activity for 3 years I am closing this issue, we can reopen on demand.
