### ISSUE TITLE
Add support to gevent workers on server

### ISSUE THREAD

**Issue by gppeixoto** [mlflow/mlflow#220]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Fedora release 27 (Twenty Seven)
- **MLflow installed from (source or binary)**: 
Source
- **MLflow version (run ``mlflow --version``)**:
0.3.0
- **Python version**: 
2.7.14
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
I was setting up a remote server on AWS with Docker (built and pushed the image from the project's Dockerfile available) on Kubernetes (through StatefulSets). However it is very hard to effectively serve gunicorn-backed servers behind an AWS ELB, as evidenced mostly in this issue: https://github.com/benoitc/gunicorn/issues/1194. Besides directly deploying on EC2, one way to circumvent this issue would be to make `gevent` workers available. There would be mostly, two additions: 

* a new optional parameter to the CLI `mlflow server`, which could something on the lines of `mlflow server -k [gevent|gunicorn]`, defaulting to gunicorn;
* pass the option along, which would trigger a call of something like:

```
exec_cmd(["gunicorn", "-k", worker_type, "-b", bind_address, "-w", "%s" % workers, "mlflow.server:app"]
``` 

### Source code / logs
I was able to quickly test this enhancement by hardcoding the worker type to the gunicorn call to test if it would correctly respond to the requests -- server starts up successfully and it is able to handle requests:

```
[2018-07-31 10:59:08 +0000] [12073] [INFO] Starting gunicorn 19.9.0
[2018-07-31 10:59:08 +0000] [12073] [INFO] Listening at: http://0.0.0.0:5000 (12073)
[2018-07-31 10:59:08 +0000] [12073] [INFO] Using worker: gevent
[2018-07-31 10:59:08 +0000] [12077] [INFO] Booting worker with pid: 12077
[2018-07-31 10:59:08 +0000] [12078] [INFO] Booting worker with pid: 12078
[2018-07-31 10:59:08 +0000] [12079] [INFO] Booting worker with pid: 12079
[2018-07-31 10:59:09 +0000] [12086] [INFO] Booting worker with pid: 12086
```
I'd be glad to help with a PR, wanted to double check if it makes sense at the first place.

**Comment by aarondav** [comment]
This makes sense, although I think it's an option between `sync` and `gevent` (rather than between `gunicorn` and `gevent`), from [this doc](http://docs.gunicorn.org/en/stable/design.html).

`gevent` has the downside that it runs all threads in the same Python process, subject to the GIL. So the server can only have one request doing work in Python-land at a time. I don't think the server does much in Python-land, but it's not something we've optimized for.

`ghread` might be even better, since it uses a process pool (one commenter on that issue suggests it worked for them), although this would require adding `futures` as a dependency for python2.

For now, I think your initial proposal of adding at least `-k sync|gevent`, keeping the default of `sync` seems reasonable. We can change the default later (before 1.0) if this is a sufficiently common issue for people to run into.

**Comment by aarondav** [comment]
`-k` sounds good to me, to match gunicorn. Happy to help review the PR when it's ready!

**Comment by aarondav** [comment]
Closing, I think we added support for this a while ago.

**Comment by kjyv** [comment]
So for reference, the flag to be used now seems to be `--gunicorn-opts "-k gevent"`
