### ISSUE TITLE
[BUG] Expected behaviour of kubernetes backend

### ISSUE THREAD

**Issue by argoyal** [mlflow/mlflow#2321]
I have written a kubernetes job template and expecting to perform mlflow run using this backend. I understand I can configure kubernetes job template as per my wish which will solve most of the problems for me.

The major issue I am facing right now is that the environment variables that I have specified in the MLproject docker_env is not getting drilled to the kubernetes job template rather [three env variables](https://github.com/mlflow/mlflow/blob/8447c4201ae7306d69b692f5e634c7eb59cf1462/mlflow/projects/__init__.py#L578) are configured while [running kubernetes job](https://github.com/mlflow/mlflow/blob/8447c4201ae7306d69b692f5e634c7eb59cf1462/mlflow/projects/__init__.py#L196).

What is the expected behavior of the kubernetes backend.. will the specified configurations in docker_env be drilled down directly to the kubernetes run job or are we expecting to treat kubernetes standalone and reconfigure it again as per usage.

The issue in the later one is reconfiguring configmaps and secrets again which are already available to me in the mlflow run issuing system via docker_env

**Comment by dbczumar** [comment]
@argoyal Thanks for raising this issue. As you've pointed out, [three env variables](https://github.com/mlflow/mlflow/blob/8447c4201ae7306d69b692f5e634c7eb59cf1462/mlflow/projects/__init__.py#L578) are specified in the Kubernetes Job template via the `env` field in the Job container definition. In particular, the `MLFLOW_TRACKING_URI` environment variable is required in order to record information to the appropriate MLflow tracking server. According to https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/, it appears that environment variables specified within Job container specification will override the set of environment variables specified by the Docker image:

```
Note: The environment variables set using the env or envFrom field will override any environment variables specified in the container image.
```

For your use case, is it possible to specify these environment variables as environment variables within the Job container definition via the `env` field? These environment variables will be preserved - MLflow *appends* the three env variables to any preexisting variables in the Job specification (https://github.com/mlflow/mlflow/blob/c8ff2ab449dc2fc20cb7f8643af281bb4e42db96/mlflow/projects/kubernetes.py#L44). Please let me know if this works for you!

**Comment by dbczumar** [comment]
Hi @argoyal @sueann, I'm going to close this issue due to inactivity. @argoyal Please feel free to re-open this if the suggestion in https://github.com/mlflow/mlflow/issues/2321#issuecomment-580915616 does not satisfy your requirements.
