### ISSUE TITLE
[FR] Add usage of model registry to examples under examples directory

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#2341]
## Describe the proposal
We should add an example that uses the model registry component to the set of open-source examples under the [`examples` directory](https://github.com/mlflow/mlflow/tree/master/examples), and link to it from the Tutorials & Examples doc page ([see docs source code](https://github.com/mlflow/mlflow/blob/master/docs/source/tutorials-and-examples/index.rst))

We could achieve this by updating the existing scikit-learn wine example (https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine) to call `log_model` with the `registered_model_name` argument set, which will result in registration of a new model version.

In a follow-up PR, we can also add a README under the `sklearn_elastic_wine` directory explaining what the example does & how to view registered models generated by the example in the UI, etc

### Motivation
An example that uses the model registry would make it more discoverable / make it easier for users to get started.

**Comment by netanel246** [comment]
@smurching Hi, I would like to pick this issue if no one else is working on it.

**Comment by smurching** [comment]
@netanel246 that'd be great! cc-ing @dmatrix, who recently worked on adding some model-registry code snippets to the model registry doc page. 

I imagine it'd still be very useful to update the existing MLflow examples to log models to the registry. The main nice thing is that now, in the READMEs for different examples, we can link to @dmatrix's new docs in https://mlflow.org/docs/latest/model-registry.html#ui-workflow rather than explaining how to view the UI ourselves.

Any thoughts @dmatrix?

**Comment by dmatrix** [comment]
There are three primary ways  [Model Registry API workflows](https://mlflow.org/docs/latest/model-registry.html#api-workflow) to work with the model registry. None is a default one, and its usage and choice will depend on at what point in your experiment runs you will want to create or register a model. 

Instead of advising or showing examples to register the model while using mlflow.<model_flavor>.log_modelI(..), we should rather suggest the three ways you can register a model. 

This way a developer can choose at what point during his or her experiments are they ready to commit the model to the registry and start collaborating with the rest. 

If we update all the MLflow examples to register the model while logging the model, then we are dictating or setting the best practice, which may not always be the case. The workflows or usage I envision among developers is as follows:

**Scenario 1:** I know exactly which model I want to register as version 1, do it while running experiments, and let it create multiple versions, and I'll choose the best version later to transition to "Stage"
- create a model, log all metrics, and register as part of mlflow.log_model(...)

**Scenario 2**: Not sure which run within an experiment yields the best outcome, so don't register it during runs,
-  create a model, log all metrics
- examine all runs to evaluate the best run
- now register the model using the runs://URI

**Scenario 3:** Let me create a registered model with a unique name and no versions
- run experiments 
- chose the best run to create a version.

All these [three ways to interact with the registry are documented](https://mlflow.org/docs/latest/model-registry.html#api-workflow)

So IMHO, we should not always register the model at the time we log the model in our
examples because it may suggest what we think that scheme is the best. On the contrary, what's best will depend on each use case how the ML team experiments, and at what point feel they want
to commit to the registry for collaborating, testing, staging, productioinizing, archiving or deletinbg.

**Comment by netanel246** [comment]
@dmatrix, Thanks for your detailed explanation.

@smurching ,Do you want that I create a PR with the example and a comment that refers to the documentation?

**Comment by netanel246** [comment]
@smurching , @dmatrix, I've noticed that the Model Registry is not working if using the local file path as a tracking URL.
Should I check it before I registered the model?

**Comment by dmatrix** [comment]
Yes, the model registry does not work support file store. You will have to set the tracking uri in the code. For example, 

`local_registry = "sqlite:///mlruns.db"`
`mlflow.set_tracking_uri(local_registry)`

And then bring up the MLflow with `mlflow ui --backend-store-uri sqlite:://mlruns.db`

I have some test examples [here](https://github.com/dmatrix/mlflow-tests/tree/master/py/mlflow):

**Comment by netanel246** [comment]
@dmatrix, OK.
But do we really want to enforce the creation of a local registry?
I mean, the `sklearn_elastic_wine` example do not contain this line:
`mlflow.set_tracking_uri(local_registry)`

Maybe it will be better to check if it does not use a local file path and only then use the `register_model_name` otherwise, log the model without this param.
What do you think about it?

**Comment by dmatrix** [comment]
If they don't want to register the models then, they don't have to specify the registry URL. However, the model registry does not work with a local file store as you know.

 I suppose you can check if it does not have a local file path only then use the `register_model_name`.
