### ISSUE TITLE
[BUG] RuntimeWarning with "mlflow ui", leads to "Now Found" in browser.

### ISSUE THREAD

**Issue by Hydroo24** [mlflow/mlflow#2346]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Manjaro KDE Edition
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.5.0
- **Python version**: 3.8
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow ui

### Describe the problem
When running the UI with `mlflow ui`, I get a warning :
```
[2020-01-25 22:36:20 +0100] [3498] [INFO] Starting gunicorn 19.9.0
[2020-01-25 22:36:20 +0100] [3498] [INFO] Listening at: http://127.0.0.1:5000 (3498)
[2020-01-25 22:36:20 +0100] [3498] [INFO] Using worker: sync
/usr/lib/python3.8/os.py:1021: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-01-25 22:36:20 +0100] [3500] [INFO] Booting worker with pid: 3500
```
Then when I go to http://127.0.0.1:5000 (or localhost) in the browser, I get `Not Found`.

### Code to reproduce issue
clone the repo, `cd mlflow/examples,` run `python sklearn_elasticnet_wine/train.py 0 0`, run `mlflow ui`.

### Other info / logs
I does not happen when I use a Python 3.6 virtual environment, this must be a Python 3.8 issue.

EDIT : I precise that I did not use `pip install` to install mlflow, but I built it from the source package instead. I made a PKGBUILD file (for Arch Linux) and installed with pacman (Arch's package manager), since using pip with Arch in highly discouraged. Actually, acxz did it for me here : [https://aur.archlinux.org/packages/python-mlflow/](url)

**Comment by ParseThis** [comment]
In development mode (when you clone the repo) this happens if you don't have the build files where the server expects them. In `/mlflow/mlflow/server/js` try running 
```
npm install
npm run build
```
that install npm and build the necessary UI, placing them in the expected folder.

Then run `mlflow ui` from your project folder

I suspect that when you `pip to install mlflow` the UI build files are built on install,  so that's why you're not experiencing it with then

**Comment by Hydroo24** [comment]
I did
```
cd mlflow/mlflow/server/js
npm install
npm run build
cd ../../../examples
mlflow ui
```
Still does not work :(

**Comment by andychow-db** [comment]
I suspect there is something wrong with the build and install without pip. Can you share with me the exact workflow you do to accomplish this?

Also, are you working within a conda environment?

**Comment by acxz** [comment]
@andychow-db  just saw for some reason.
The PKGBUILD that Hydroo24 linked to (apparently erroneously) is essentially a build recipe. It should be fairly easy to understand. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-mlflow

Instead of using `pip` I am compiling/building the package with setup.py directly and then `install`ing them to a certain folder.

**Comment by acxz** [comment]
I believe we can close this @andychow-db , @ParseThis was correct. I did not read https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#building-a-distributable-artifact carefully when creating the Arch Linux package. I can no longer reproduce this issue as of `python-mlflow-1.7.2-3`

@Hydroo24 please let me know if you still have issues over at https://github.com/acxz/pkgbuilds

**Comment by andychow-db** [comment]
Sounds good. Closing the issue now.
