### ISSUE TITLE
ml flow ui can't be accessed from google colab

### ISSUE THREAD

**Issue by divyag11** [mlflow/mlflow#2350]
i can't access mlflow ui from google colab,however through jupytre notebook,it's accessible.

**Comment by harupy** [comment]
I'm curious how the MLflow UI looks like on Jupyter. Can you take a screenshot of it?

**Comment by pazlvbanke** [comment]
@divyag11 I can

**Comment by tienthegainz** [comment]
> @divyag11 I can
How do you do that?
mlflow ui expose in 127.0.0.1 means that it can't expose to the outsider, change host to 0.0.0.0 may work IDK.

**Comment by pazlvbanke** [comment]
@tienthegainz run ‘’’mlflow ui -h 0.0.0.0’’’ on you local machine, access by localhost:5000

**Comment by tienthegainz** [comment]
> @tienthegainz run ‘’’mlflow ui -h 0.0.0.0’’’ on you local machine, access by localhost:5000

The question is asking how to read it from Google Colab not your local machine.

**Comment by dmatrix** [comment]
You can install mlflow on the colab and it will run and track the experiment under your colabs drive. When you launch `mlflow ui`, it will launch try to launch to the server on the colab machine, and there is no way connect to it. Nor can you set the enviornment variable
`DISPLAY localhost:0.0` because it cannot the connect to your host.

One workaround is to download the `mlruns` directory from your colab drive to your local machine, and then launch `mlfow ui`

https://colab.research.google.com/drive/1m_g2lhehzhOlZH0UvqDHhPENbGFu9pgn#scrollTo=MrJhP1CBSWdi

**Comment by dmatrix** [comment]
![Screen Shot 2020-07-01 at 4 19 26 PM](https://user-images.githubusercontent.com/1117597/86300075-ad0d6680-bbb6-11ea-8584-9c5fa3c38e47.png)

**Comment by dmatrix** [comment]
I would not consider this as a bug.

**Comment by dmatrix** [comment]
Here is an [example](https://github.com/dmatrix/google-colab/blob/master/mlflow_issue_2350.ipynb)

**Comment by sp7412** [comment]
So there's no way to make this work in the cloud?

**Comment by dmatrix** [comment]
> So there's no way to make this work in the cloud?

No, at this moment MLflow UI works only in the Databricks and Azure cloud. 

> > @tienthegainz run ‘’’mlflow ui -h 0.0.0.0’’’ on you local machine, access by localhost:5000
> 
> The question is asking how to read it from Google Colab not your local machine.

Currently, as far as I know, you can't.

**Comment by dmatrix** [comment]
I have updated the notebook to show how to use MLflow in Google Colab. You can use `pyngrok` to tunnel. Realy simple!
https://github.com/dmatrix/google-colab/blob/master/mlflow_issue_2350.ipynb

**Comment by desertnaut** [comment]
@dmatrix many thanks for this!

Since this issue still appears open and your post is rather "buried" in here, I took the liberty to post your code as an answer to the Stack Overflow question [Setting-up MLflow on Google Colab](https://stackoverflow.com/questions/61615818/setting-up-mlflow-on-google-colab), with full attribution of course (including links to your notebook and here).

In case you feel this is a violation of your IP from my part, please take a minute to inform me here, and I will remove the post immediately.

Thanks again!

**Comment by dmatrix** [comment]
Am closing this since we have a solution now.

**Comment by salmanhiro** [comment]
Hi, found out that now the solution is no longer working. The error in the `pyngrok` forwarded URL is `Failed to complete tunnel connection` and it shows that, in example `the client failed to establish a connection to the local address localhost:5000.`. 

The error encountered was: dial tcp 127.0.0.1:5000: connect: connection refused

Seems like google collab blocks the port?

**Comment by salmanhiro** [comment]
Found a solution. add 
`get_ipython().system_raw("mlflow ui --port 5000 &")` before running the mlflow. So you actually ran the mlflow ui command inside the ipython terminal before

so it will be
```

from pyngrok import ngrok

get_ipython().system_raw("mlflow ui --port 5000 &")# run tracking UI in the background

# Terminate open tunnels if exist
ngrok.kill()

# Setting the authtoken (optional)
# Get your authtoken from https://dashboard.ngrok.com/auth
file1 = open('token.txt', 'r')
NGROK_AUTH_TOKEN = file1.readlines()

ngrok.set_auth_token(NGROK_AUTH_TOKEN[0])

# Open an HTTPs tunnel on port 5000 for http://localhost:5000
ssh_tunnel = ngrok.connect(22, "tcp")
print("MLflow Tracking UI:", ssh_tunnel)
```
