### ISSUE TITLE
[FR] Double nesting - better UI visualization

### ISSUE THREAD

**Issue by jankrepl** [mlflow/mlflow#2414]
### Proposal
Currently in the UI if a run is nested twice then the second nesting is not visible (same indentation as the parent).

### Motivation
The tracking API allows for arbitrary nesting so it would be cool to actually make the UI compatible.

**Comment by andychow-db** [comment]
Thank you for submitting this feature request. 

To help me understand your need better, I have a few questions. 

1. How are you using nested runs? 

2. Is there possibility for third level nesting or more?
 
3. Are you currently blocked due to this feature?

**Comment by jankrepl** [comment]
Thanks for your response!

1. The idea of nesting (hierarchy) of runs is to clearly separate metrics over different **dataset splits** and **models**. See below a sketch (each tree node represents a separate run in MLflow)

![mlflow](https://user-images.githubusercontent.com/18519371/74241408-43122480-4cdc-11ea-99b9-1b74f0fec593.png)

The idea would be to **log metrics only for the leaf nodes** as well as model specific parameters.  The non-leaf nodes would only store parameters.

Currently to log metrics over different data splits one would have to name the metrics based on what split we are on (however this does not scale).


2. Yes, third level nesting could come up with different validation schemes:
![mlflow_2](https://user-images.githubusercontent.com/18519371/74241568-997f6300-4cdc-11ea-9bfb-a873c29fac98.png)

3. I am not blocked because of it but I think it would be very nice to have different indententations for different nesting depths.

**Comment by andychow-db** [comment]
Alright, thank you for the information. It seems like an interesting feature. I'll put it in our backlog and we'll prioritize it accordingly.

**Comment by baldwint** [comment]
I also would benefit from this feature, or a clause in the documentation stating that the UI's maximum supported nesting depth is 2.

My application is a fairly simple three-step workflow (data prep, training, scoring). I wanted to use run nesting to reflect the latter two runs' dependence on the artifact produced in the previous step.

For example, I first run the data prep job with some set of parameters, and it produces an artifact (the training data). Some time later, I run the training job. This job re-starts the data prep run and uses `mlflow.get_artifact_uri` to load the training data artifact. Then it starts a nested run for training and logs all the model parameters and the model artifact it produces. The scoring job would do something similar, nested under the training job.

This is arguably a hack since training isn't really a part of data prep (and the fact that it unsets the parent's end time is a drawback), but it seemed like a nice way to group all runs derived from a given dataset together in the UI. The problem is that I wanted one more level, and I didn't realize the nesting was capped at 2 until I had built out the pipeline and run it.

Due to the UI limitation I ended up removing the nesting. I use MlflowClient to query the previous step's artifact instead of using `mlflow.get_artifact_uri`. I also log the previous step's run_id as a tag or parameter of the active run so that I can filter by it later. This requires me to copy/paste run ids into the filter box, which is not as nice as clicking a disclosure toggle in the UI, but works ok.

Not a blocker by any means, but wanted to share my use case for reference.

**Comment by MFreidank** [comment]
+1 Many situations were multi-level nesting is useful, including training ensemble models and hyperparameter tuning. Using it is already possible, but explaining to people that this feature exists and works but does not visualize in the UI is inconvenient. Please add support to show this in the mlflow UI.

**Comment by Dr-DaDe** [comment]
I'd like to add myself to the list of people who would highly appreciate if nested runs were visible in the UI. Whenever I encounter a "natural queue of processing steps", I try to use nested runs to keep the connection of related steps (i.e. model definition -> (training on various datasets) -> (seperate validation methods per training).

**Comment by Hadrien-Cornier** [comment]
I also would benefit from this feature, as I am doing hyperparameter tuning on a multistep pipeline. 
It would allow me to have 
level 0 - one entry for each set of parameters
level 1 - one entry for every image of the validation dataset on which the pipeline is applied
level2 - one entry for every step of the pipeline and their respective artifacts

The level 2 is useful to be able to reuse artifacts calculated for the same stage of the pipeline in otherwise different parameter settings. It is possible to work around this problem though, but it would be nice to have the option for multi level nesting.

**Comment by dmus** [comment]
Is there any progress here? This feature would be very welcome

**Comment by navarmn** [comment]
I would also love this feature.

**Comment by abin-tiger** [comment]
Yes. This would be very useful for hyperparameter tuning.

**Comment by mohammedayub44** [comment]
@andychow-db  running into similar situations with our experiments where we have to evaluate each model variant against multiple validation and test sets to compare and contrast. Managing this is becoming a pain. 
A strong feature like this will definitely be very helpful for our project. Let me know if any updates. 

Thanks !

**Comment by berkayolg** [comment]
Any updates about this issue? Would be highly useful

**Comment by andreaconti** [comment]
Any updates about this feature? I'd really love to use it

Thanks for the hard work!

**Comment by moustafa-7** [comment]
any updates?
Thanks : )

**Comment by moustafa-7** [comment]
any updates?  @andychow-db 
Thanks : )
