### ISSUE TITLE
[FR] Allow existing experiment name upon create_experiment

### ISSUE THREAD

**Issue by Minyus** [mlflow/mlflow#2464]
I have been trying to specify experiment name and artifact location for multiple experimentation runs.
I used `create_experiment` and it worked fine in the first run, but it returned `MlflowException` in the second run apparently because `create_experiment` expects a unique experiment name.

I managed to find a workaround using `try` and `except` as follows.

```pytyon
from mlflow import (
    create_experiment,
    set_experiment,
    start_run,
)
from mlflow.exceptions import MlflowException

# Some code here

            try:
                experiment_id = create_experiment(
                    self.experiment_name, artifact_location=self.artifact_location
                )
                start_run(experiment_id=experiment_id)
            except MlflowException:
                set_experiment(self.experiment_name)
```

This workaround does not look intuitive to me.
I would like `create_experiment` to allow existing experiment name for intuitive multiple runs under the same experiment name.

I use the latest version (1.6.0) of MLflow.

**Comment by harupy** [comment]
`set_experiment` creates an experiment with provided name if it does not exist.

https://github.com/mlflow/mlflow/blob/12bcee8e556d62b888d0c8a7afb2c8ed122f7354/mlflow/tracking/fluent.py#L39-L46

**Comment by Minyus** [comment]
Hi @harupy 

Thank you for your suggestion. 
It would be great if I can specify `artifact_location`.

**Comment by harupy** [comment]
@mparkhe @smurching 
Would it make sense to add `artifact_location` to `set_experiment`?

**Comment by smurching** [comment]
@Minyus thanks for filing - the same question actually came up in #1924, where the resolution was that adding an `artifact_location` parameter to `set_experiment` makes the API hard to reason about, as you're not guaranteed that the artifact location will actually be set on the newly-created experiment (the `artifact_location` will be honored if the experiment doesn't already exist with a different artifact location). 

It is possible to achieve a slightly simpler implementation of your use case (a few less lines of code, but still pretty gnarly):

```
existing_exp = mlflow.get_experiment_by_name(name)
if not existing_exp:
  mlflow.create_experiment(name, artifact_location="...")
mlflow.set_experiment(name)
```

However, I'm now leaning towards actually supporting `artifact_location` as a parameter to `set_experiment`, as it seems the current APIs do cause a good bit of pain from a usability standpoint. I think if we do this, we should make sure it's clear to the user when `artifact_location` is not honored because an experiment already exists with a different `artifact_location` (& hopefully that case is rare), e.g. log a warning in that case. Let me ask around for other opinions, but if others agree we'd be happy to review a contribution adding an `artifact_location` parameter :)

**Comment by smurching** [comment]
^Actually, better than logging a warning would be to just throw if the user-provided `artifact_location` doesn't match the artifact location of the existing experiment, if an experiment with the same name already exists.

**Comment by youra6** [comment]
Sorry for bringing this up but I think I have another _decent_ workaround if anyone else is having a hard time with calling `create_experiment()` multiple times. This will also avoid the "ERROR mlflow.utils.rest_utils..." logging message as well.

  ` try:
        experiment = mlflow.get_experiment_by_name('oof')
        experiment_id = experiment.experiment_id
    except AttributeError:
        experiment_id = mlflow.create_experiment('oof', artifact_location='s3://mlflow-minio/sample/')`

If it is the user's first time creating the experiment, the code will run into an AttributeError since `experiment_id` does not exist and the `except` code block gets executed.

If it is the second, third, etc the code is run, it will only execute the code under the `try` statement since the experiment now exists. Not fully tested but it works for me at least.

**Comment by dbczumar** [comment]
@youra6 Thank you for posting a detailed and helpful solution. At this time, we don't intend to extend `mlflow.set_experiment()` to support `artifact_location`.
