### ISSUE TITLE
[FR] Add simple health check API

### ISSUE THREAD

**Issue by mjmikulski** [mlflow/mlflow#2504]
## Current status
Currently, according to [this documentation](https://www.mlflow.org/docs/latest/rest-api.html), there is no dedicated method to check if there is a working connection to a server, if it is alive and responds etc. As a workaround one can use some of available methods with some dummy data, but this is not elegant and may lead to creation of dummy data on the server.

## Describe the proposal
Add a simple API for checking if ML flow server is running.

## Motivation
- Reliable and elegant health check for easier scripting in Python.
- Simpler deployment on kubernetes, [see why it's needed](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes).

### REST API
Add GET method to the API to check health

Optionally, add 3 methods for checking health, readiness and liveness, analogical as [here](https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html).  

### Python
Add `mlflow.check_remote_server()` or similar method that would return a bool indicating if the server is reachable and ready to accept data.

Optionally, the method could return a custom `ServerStaus` object with more detailed status.

**Comment by mjmikulski** [comment]
It seems that this feature request was partially implemented.

- [x] REST AP in #2725
- [ ] Python

**Comment by dbczumar** [comment]
@mjmikulski I don't think we have plans to implement a Python health check function in MLflow, since the health check API is only implemented by the open source MLflow server (other implementations of the REST API do not expose the `/health` endpoint). If we were to introduce such a function in Python, we would also likely have to introduce it for R and Java, expanding the API surface significantly.

Instead, we propose fetching the tracking server URL via `mlflow.get_tracking_uri()` and using a Python HTTP library (e.g., `requests`) to query the `/health` endpoint of an OSS MLflow tracking server. For now, I'm going to close this ticket; please feel free to reopen this if the proposed workaround does not meet your requirements.
