### ISSUE TITLE
[FR] Auto increment the step 

### ISSUE THREAD

**Issue by cdancette** [mlflow/mlflow#2505]
It would be nice to have an option to auto-increment the step parameter in the metric logging function.

The new value would be appended to existing value and the step would be incremented by 1.

This way we don't have to track the global step. 

For example:

```
mlflow.log_metric("score", 90, auto_increment=True)  # step 0
# training more...
mlflow.log_metric("score", 100, auto_increment=True) # step 1
```
```

**Comment by AveshCSingh** [comment]
Hi @cdancette, 

Thanks for submitting this enhancement idea. If we add an auto_increment parameter, what should happen when some metrics are logged for all epochs, while others are only logged for some? I believe this is a common pattern when evaluating a model is expensive.

Because of this, I'm not sure this improvement would be worthwhile.

This simplifies a process that is already quite simple (keeping track of the step manually), but at the expense of confusing more complicated use cases.

I'll close this out for now, but feel free to re-open with additional supporting evidence.

**Comment by AveshCSingh** [comment]
By the way, check out the workaround here: https://github.com/mlflow/mlflow/issues/2419#issuecomment-655714430
