### ISSUE TITLE
[BUG] Artifact URI doesn't change on existing experiments

### ISSUE THREAD

**Issue by AlessandroVol23** [mlflow/mlflow#2729]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.
- **MLflow installed from (source or binary)**: Binary Pip
- **MLflow version (run ``mlflow --version``)**: 1.7.2
- **Python version**: 3.6.9
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: `mlflow server --backend-store-uri postgresql://USER:PW@localhost/mlflow --default-artifact-root /mlflow_runs -h 0.0.0.0`

### Describe the problem
I try to change the artifact root to the folder `/mlflow_runs` and mount this folder via simple NFS share on the client. If I execute the following on the client, the `artifact_uri` is unchanged.

```python
import mlflow
mlflow.set_tracking_uri("....")
mlflow.set_experiment("TEST")
mlflow.get_artifact_uri()
# /home/ubuntu/mlruns/...
# This is the old path
```

If I create a new experiment the artifact path is correct.
```python
import mlflow
mlflow.set_tracking_uri("....")
mlflow.create_experiment("test123")
mlflow.set_experiment("test123")
mlflow.get_artifact_uri()
# /mlflow_runs
# Right path
```

**Comment by andychow-db** [comment]
A run gets it's artifact location from the experiment 
https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/store/tracking/sqlalchemy_store.py#L323

`get_artifact_uri()` gets the uri from the run information in the database.
https://github.com/mlflow/mlflow/blob/31536bd46d5c29419660c35c4f13ba1f2e6039f9/mlflow/tracking/artifact_utils.py#L43

Here is my hypothesis:
The experiment `TEST` was created with the artifact path `/home/ubuntu/mlruns` and so when you set the experiment to `TEST`, it would use this artifact path rather than the one specified on the command line. 

This works as expected because the artifact path on the command line is used only when creating a new experiment.

**Comment by dbczumar** [comment]
Following up here - the root artifact URI is immutable for a given experiment. Thank you for using MLflow!
