### ISSUE TITLE
EKS MLflow Server S3 Artifact Access Denied

### ISSUE THREAD

**Issue by TheVillageFool** [mlflow/mlflow#2746]
Hello,

I'm currently working on dockerizing and deploying mlflow on an eks cluster. In the dockerfile, I set the env variables and run a script to start mlflow server. I'm able to connect to the server and save to the postgres backend I have set up, but I'm getting an Access Denied when attempting to save artifacts to S3. I ensured the environment variables are set for aws during the deployment since a test 'aws s3 ls' to the artifact bucket returns correctly. Is there something that needs to be done to ensure the credentials are being passed to mlflow server correctly?

Dockerfile:
```
FROM python:3.7.0

RUN pip install mlflow
RUN pip install boto3
RUN pip install awscli
RUN pip install psycopg2-binary

ENV AWS_MLFLOW_BUCKET=aws_mlflow_bucket
ENV AWS_ACCESS_KEY_ID=aws_access_key_id
ENV AWS_SECRET_ACCESS_KEY=aws_secret_access_key
ENV AWS_SESSION_TOKEN=aws_session_token

COPY run.sh /
RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]
```

run.sh
```
#!/bin/sh

set -e

aws s3 ls s3://<bucket_name>

mlflow server \
--backend-store-uri ${POSTGRES_DB} \
--default-artifact-root ${S3_ARTIFACT_BUCKET} \
--host 0.0.0.0 \
--port 5000
```

Error when trying to store artifact in s3:
`An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity`

**Comment by tomasatdatabricks** [comment]
I am not sure if I understand your case correctly. Artifacts are usually logged by the client, not by the server. Does your client have sufficient rights to access your s3 bucket?

**Comment by smurching** [comment]
@TheVillageFool did you get a chance to take a look at @tomasatdatabricks's question above? As he mentioned, artifacts are logged by the client (i.e. when you call `mlflow.log_artifact` from your machine, the client determines the current run's artifact URI, and then attempts to write directly from your machine to that artifact URI, rather than via your machine -> MLflow server -> artifact URI). Does the machine from which you're logging artifacts have the appropriate AWS credentials set up?

For more info on the details of the artifact logging flow, see [this StackOverflow post](https://stackoverflow.com/questions/52331254/how-to-store-artifacts-on-a-server-running-mlflow)

**Comment by smurching** [comment]
Closing this for now as the original question's been answered, but feel free to reopen!
