### ISSUE TITLE
[BUG] Experiment ID can't be 0 in MySQL

### ISSUE THREAD

**Issue by weldpua2008** [mlflow/mlflow#2817]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No 
- **OS Platform and Distribution**: Debian GNU/Linux 10 (buster)
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.0.0
- **Python version**:  Python 3.6.10

### Describe the problem
I am working on a migration from file-based backend store to mysql database.
I am trying to add existing Experiment id 0 
```sql
INSERT INTO `experiments` (`experiment_id`, `name`, `artifact_location`, `lifecycle_stage`) VALUES (0, 'experiment_first', 's3://mlflow-unique-bucket/0', 'active');
```
but I am getting experiment id 1 

### Code to reproduce the issue
```sql 
MySQL [db]> select `experiment_id`, `name` from experiments;
Empty set (0.002 sec)

MySQL [db]> INSERT INTO `experiments` (`experiment_id`, `name`, `artifact_location`, `lifecycle_stage`) VALUES (0, 'experiment_first', 's3://mlflow-unique-bucket/0', 'active');
Query OK, 1 row affected (0.011 sec)

MySQL [db]> select `experiment_id`, `name` from experiments;
+---------------+------------------+
| experiment_id | name             |
+---------------+------------------+
|             1 | experiment_first |
+---------------+------------------+
1 row in set (0.001 sec)

```

**Comment by tomasatdatabricks** [comment]
Thanks for posting. 

Unfortunately, the default behavior of MySQL for auto-incremented columns is to treat 0 as a placeholder for the next item in the sequence. And since the sequence starts from 1, you are seeing id=1.

We can not do much here as I don't think this can be controlled on the column level. It can only be controlled on the database level (if I am reading mysql docs correctly). I see two possible workarounds:

a) start your mysql server with --sql-mode="NO_AUTO_VALUE_ON_ZERO"

or

b) Map your experiment 0 to a different unique value first, such as 54321

Let me know if this works for you.

**Comment by weldpua2008** [comment]
@sueann thank you for your reply
I am using the following ugly solution:
```python
    if experiment_id == 0 or experiment_id == '0':
        print("SET sql_mode='NO_AUTO_VALUE_ON_ZERO';")
```
