### ISSUE TITLE
[BUG] Fail to serve models stored in Azure Blob Storage

### ISSUE THREAD

**Issue by waqassiddiqi** [mlflow/mlflow#2842]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **MacOS**
- **MLflow installed from (source or binary)**:
- **mlflow, version 1.8.0**:
- **Python 3.8.2**:
- **export AZURE_STORAGE_ACCESS_KEY=access-key && mlflow models serve -m wasbs://x-container@y-storage.blob.core.windows.net/mlflow/8/b76bc49b0e42424c8bc3f4341dbdbdfc/artifacts/model -p 5001**:

### Describe the problem
Unable to serve model stored in Azure blob storage. I can see model files (model.pk, MLmode & conda.yaml) located at the path specified as command param `mlflow models serve -m wasbs://x-container@storage.blob.core.windows.net/mlflow/8/b76bc49b0e42424c8bc3f4341dbdbdfc/artifacts/model -p 5001`
If I download model.pk, MLmode & conda.yaml files locally and run the command like this: `mlflow models serve -m . -p 5001`, it works. 

### Code to reproduce issue
1. Use Azure as a remote store to keep models
2. Run an experiment and log model
3. Use the run ID to serve model

### Other info / logs

> Traceback (most recent call last):
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/mlflow/models/cli.py", line 53, in serve
    return _get_flavor_backend(model_uri,
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/mlflow/models/cli.py", line 164, in _get_flavor_backend
    model = Model.load(local_path)
  File "/Users/waqassiddiqi/opt/anaconda3/envs/c-mlpipeline-dev/lib/python3.8/site-packages/mlflow/models/__init__.py", line 73, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/dt/9f6c710j2sq7pybth858lzzw0000gn/T/tmpvm1zvbhq/MLmodel/MLmodel'
make: *** [serve] Error 1

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by smurching** [comment]
@waqassiddiqi thanks for reporting this issue! It'd be great to get your help understanding the root cause - when you run `mlflow models serve` against a remote URI, we download the model to a local directory, and then attempt to load it from there. It seems the loading step fails on your machine as the local directory that MLflow expects to contain the model does not exist. 

See the [relevant code here](https://github.com/mlflow/mlflow/blob/cf3b4e190612add14df99bb1036f1b5bfe775ba6/mlflow/models/cli.py#L162-L164). Note also that the path we load from (`'/var/folders/dt/9f6c710j2sq7pybth858lzzw0000gn/T/tmpvm1zvbhq/MLmodel/MLmodel'`) contains two occurrences of "MLModel". I suspect this happens because we append "MLmodel" to the file name twice, [here](https://github.com/mlflow/mlflow/blob/cf3b4e190612add14df99bb1036f1b5bfe775ba6/mlflow/models/cli.py#L163) and again [here](https://github.com/mlflow/mlflow/blob/branch-1.8/mlflow/models/__init__.py#L71).

Would you be able to verify whether the temporary directory expected to contain the model in fact exists? In particular, whether `/var/folders/dt/9f6c710j2sq7pybth858lzzw0000gn/T/tmpvm1zvbhq/` exists? And if it does, would you be able to verify the result of calling `os.path.isdir` on the MLmodel file within the directory, e.g. `import os; print(os.path.isdir('/var/folders/dt/9f6c710j2sq7pybth858lzzw0000gn/T/tmpvm1zvbhq/MLmodel'`)? Note of course that the path of the temporary directory will change if you rerun the `mlflow models serve` command, but you should be able to substitute it into the commands above from the stacktrace. Let me know if you have any questions, thanks!

**Comment by waqassiddiqi** [comment]
@smurching I checked, directories are not being created. So, from my message I can see `/var/folders/dt/9f6c710j2sq7pybth858lzzw0000gn/T` but there is no `tmpvm1zvbhq` directory

**Comment by smurching** [comment]
@waqassiddiqi sorry, my last message (which specifically referenced a directory named `tmpvm1zvbhq `) was confusing - note that temporary directories are removed when you restart your machine etc, so the directory from your original error message may have been created and then removed.

Would you be able to rerun the `mlflow models serve -m wasbs://x-container@storage.blob.core.windows.net/mlflow/8/b76bc49b0e42424c8bc3f4341dbdbdfc/artifacts/model -p 5001` command, and then when the command fails with a `FileNotFoundError`, check whether the parent directories of the missing file exist?

**Comment by dbczumar** [comment]
Hi folks, I believe this was fixed by #3014 (thanks @arjundc-db). Feel free to reopen this issue if #3014 did not resolve it.
