### ISSUE TITLE
[DOC-FIX] Some features are unavailable with a file-based backend store (e.g. model registry)

### ISSUE THREAD

**Issue by OlivierBondu** [mlflow/mlflow#2857]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this documentation issue template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the MLflow code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the MLflow community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

https://www.mlflow.org/docs/latest/tracking.html#storage

Please also see https://github.com/mlflow/mlflow/issues/2079 that tracks some (bad) user experience on this.

### Description of proposal (what needs changing):
Provide a clear description. Why is the proposed documentation better?

Some features will simply just not work with a file-based backend store, such as the model registry. This is not clear at all from current documentation. Also, migrations instructions or guidance from file-based to something more solid are not provided.

**Comment by smurching** [comment]
@OlivierBondu thanks for filing this! Agree that we should document this limitation, I'd be happy to review a PR that updates [this page](https://mlflow.org/docs/latest/model-registry.html#model-registry-workflows) (see [relevant source code](https://github.com/mlflow/mlflow/blob/master/docs/source/model-registry.rst#model-registry-workflows) & [development loop for documentation](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#writing-docs)) to state something like "In order to use model registry functionality via the UI or API, ensure you're running an MLflow server using SQL backend store. [See here](https://mlflow.org/docs/latest/tracking.html#storage) for more information"

**Comment by mparkhe** [comment]
Addressed by @smurching in PR #2865

**Comment by swertz** [comment]
Are those warnings in the docs still relevant? We are somewhat confused because we were able to use model registry features with a tracking server that is not configured to use a DB backend store but rather a file-based store...
