### ISSUE TITLE
Several questions about Tracking UI

### ISSUE THREAD

**Issue by makcedward** [mlflow/mlflow#30]
First of all, seems like "Date" is local time. If that is the case, it may cause confusing if having multiple timezone office.

For user, any plan to allowing provided as an parameter? 

For storage, seems like it use local file as storage. Any roadmap/ plan to use database as storage media?

**Comment by makcedward** [comment]
For overriding user, believe that it may follow the behaviour of source_name or source_version when invoking start_run function. If no user id is passed, using default behaviour. Actually, I modified in my machine and it works fine:). However, I cannot finish the push request because I cannot execute all test cases. May you advise how can I run all test cases? I tried default python unit test cases but it only executed 32 test cases which is less than I found.

Would like to supplement  more on the reason of overriding user. First of all, I am using Window which does not come with pwd. Another reason is that, I do have linux environment but the user is shared with others due to some reasons.

In the same time, I also understand that there may be some audit/ security consideration on it. Please kindly review this feature.

Btw, i just found that, I did not need to modify code to overriding user if i am using Window. :)

**Comment by gppeixoto** [comment]
As much as I liked the overall design of mlflow, both the api and the web ui, I quite do not understand how metadata storage on a db wasn't prioritized at first. Would you care to elaborate on what motivated the mlflow design towards local fs storage and avoiding a db?

**Comment by gppeixoto** [comment]
IMO postgres seems a pretty reasonable option at least a couple of reasons: 1. obviously, for postgres itself; 2. because it has a hosted option on every major cloud services provider ([GCP](https://cloud.google.com/sql/docs/postgres/), [Azure](https://azure.microsoft.com/en-us/services/postgresql/),[AWS RDS](https://aws.amazon.com/rds/postgresql/), [Heroku](https://www.heroku.com/postgres)...). I'm really having trouble on finding a reason to model the entire framework storage around local filesystem and avoid taking advantage of a major RDBMS. It seems, at first sight, counter-productive to me.

**Comment by nitishcse412** [comment]
@makcedward I see now support of postgres/mysql etc as a backend store. One question i have that mlflow ui when starts it does not show up the details from database and it was showing fine when everything was a file system. Any limitations to it because of backend store ?

**Comment by aarondav** [comment]
@nitishcse412 No limitations from the database store -- please file a new bug if you see any issues.
