### ISSUE TITLE
Question on how managed MLFLow is different from unmanaged

### ISSUE THREAD

**Issue by saroup** [mlflow/mlflow#3109]
From reading the documentation I got that when you use MLFlow on databricks then you are using the managed version of it.
Where as when you use it in a local setting you would be using the unmanaged version of it. 

From my local environment, if I am connecting through databricks-CLI to a databricks that exists on a vnet and setting experiment and creating runs then which version of MLFlow am I using?
how secure would that connection to databricks be? The managed version has support for Role-based access control but I am not sure what this really implies.

Thank you!

**Comment by dmatrix** [comment]
@saroup Thanks for posing this question. 
I assume the documentation you referring is this [docs](https://docs.databricks.com/applications/mlflow/index.html): 

When you configure your localhost to use databricks-cli to connect to the databricks cluster, effectively you are using "Managed MLflow" on your cluster, for all tracking your experiments' and runs' entities: all MLfow entities will be stored in the backend store manged by Databricks on your cluster. 

The client on your localhost could be an OSS MLflow version as long as the MLFLOW_TRACKING_URI is set to your databricks cluster or  you code set `mlflow.set_tracking_uri(..)` to datarbicks, you can run locally and track remotely. Here's the [blog that ](https://databricks.com/blog/2019/10/17/managed-mlflow-now-available-on-databricks-community-edition.html) explains it.

I hope that clarifies it. If so can we close this since this is not a bug but a question?

thanks
Cheers

**Comment by saroup** [comment]
yes that makes things clearer, thanks! 
closing it.
