### ISSUE TITLE
Logging R models in MLflow

### ISSUE THREAD

**Issue by gs-alt** [mlflow/mlflow#3780]
Is there a way to log R models through the Python API in MLFlow? 

I want to be able to log, load, and run R models via the Python API's `predict()` eventually. 

I saw that [MLFlow supports a flavor for R](https://www.mlflow.org/docs/latest/models.html#r-function-crate), however, I don't see it in the [Python API's documentation](https://www.mlflow.org/docs/latest/python_api/index.html).

**Comment by dmatrix** [comment]
cc: @yitao-li @lorenzwalthert Any suggestions?

**Comment by lorenzwalthert** [comment]
Not sure I understand what you mean. Logging a model from a Python session involves a fitted model represented in that Python session. And you can’t represent R models in python in general (with the exception of models like xgboost or keas that can be loaded in both languages). If you have an R function already serialised as RDS, you can move this file into a `model/` directory of an MLflow run and also create an `MLmodel` file that meets the MLflow crate conventions but that’s not very elegant and robust. 

For prediction (and serving), you should be able to use the CLI and Python API independent of whether the model was created with R or Python, e.g. see https://www.mlflow.org/docs/latest/python_api/mlflow.models.html#mlflow.models.FlavorBackend.predict for the Python. Check to source code but for initializing, `config` can be an empty dict if I remember correctly and then you can call the `predict` method. It’s quite slow though IIRC because of conversion between languages and startup costs, serving is much quicker for processing a request once started up (going thorough Python, saving as csv, starting up R, reading in - all this can be skipped) I can provide more details if you need.

**Comment by gs-alt** [comment]
What I originally meant was, given model that was trained in R and somehow saved to file, is it possible that we can load it up in a Python environment, such that we can use Python APIs for the prediction. But, it seems it is possible with the [rpy2 package](https://pypi.org/project/rpy2/) anyways. 

Thank you!
