### ISSUE TITLE
Cannot Build The Project

### ISSUE THREAD

**Issue by hamroune** [mlflow/mlflow#405]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
OS X El Captain version 10.11.6
- **MLflow installed from (source or binary)**: 
docker build .
- **MLflow version (run ``mlflow --version``)**:
master
- **Python version**: 
py3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

DOCKER BUILD .
### Describe the problem

![image](https://user-images.githubusercontent.com/795761/44806121-60c1fb80-abc6-11e8-9efb-99094a5216e2.png)

![image](https://user-images.githubusercontent.com/795761/44806135-69b2cd00-abc6-11e8-9fd1-d1060bb9c137.png)

![image](https://user-images.githubusercontent.com/795761/44806150-76cfbc00-abc6-11e8-89f0-90958de6c6ce.png)

**Comment by aarondav** [comment]
We depend on third-party providers (in this case pythonhosted.org) to provide our library dependencies, and they may flaky (we've actually seen flakes like this in our CI). I would recommend just retrying.

The Docker container is going to be a little less forgiving here, since every time you rebuild it will need to redownload everything. I don't use the container personally (didn't even know we had one). Instead, I follow our guide in [CONTRIBUTING.rst](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)), creating a local conda environment and pip installing from there. This will cache already-downloaded dependencies, so even upgrading is more stable/faster.

Hope that helps!

**Comment by hamroune** [comment]
OK. I close the issue

**Comment by aarondav** [comment]
Thanks! Btw, in trying to reproduce the issue, I actually realized the current Dockerfile _is_ broken. So while retrying would fix the problem you saw, you would actually have run into a bug afterwards. I created a quick PR to fix this: #411.
