### ISSUE TITLE
Proposal: Add Sparkline for each metric

### ISSUE THREAD

**Issue by hamroune** [mlflow/mlflow#406]
I think, it is nice to compare the "current" Run to others, I imagine a drawing sparkline right next to metric

see:
https://omnipotent.net/jquery.sparkline/#s-about

at a glance we will be able to distinguish the "good" run from the bad ones

**Comment by max-allen-db** [comment]
@hamroune Hey! Sorry it's been a while since you filed this issue. Have you checked out our more recent MLflow UI? There's feature to compare multiple runs, and you can sort by metrics to help you classify what might be a "good" run. 

If you're still interested in this feature, can you describe the use case in more detail? What types of metrics are you trying to compare? What type of sparkline do you think would help here?

**Comment by smurching** [comment]
@hamroune closing this issue for now, as the hope is that the new metrics UX allows for this - but please feel free to reopen if something is missing or could be improved!
