### ISSUE TITLE
Choose MLflow server port for R connection using MLflow's CLI

### ISSUE THREAD

**Issue by javierluraschi** [mlflow/mlflow#416]
This issue is tracking work to:
- Provide mechanism in MLflow's CLI to provide a free port
- Make use of this port when launching MLflow from R

**Comment by max-allen-db** [comment]
Hey @javierluraschi, I'm sorry it's been a while since you open this issue. Are you asking about how to specify a port option in the CLI? If so, this is already available using the `-p` flag as seen in the documentation:

https://mlflow.org/docs/latest/cli.html?highlight=parameter#cmdoption-mlflow-models-serve-p

If this isn't what you meant, would you mind clarifying for me? Temporarily closing this issue and will open it up if you deem it hasn't been resolved.
