### ISSUE TITLE
[SETUP-BUG] Pinned requirement of alembic version getting old

### ISSUE THREAD

**Issue by HansBambel** [mlflow/mlflow#4215]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.

**Please fill in this installation issue template to ensure a timely and thorough response.**

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**: It would be 1.15.0
- **Python version**: 3.7.9
- **Exact command to reproduce**: `pip install mlflow` or `poetry add mlflow`

### Describe the problem
I would like to install MLflow for our project. This project has as a dependency that the version of alembic is 1.4.2. I have seen that the requirements for MLflow's alembic are <=1.4.1 (due to [#3363](https://github.com/mlflow/mlflow/pull/3363)). 
Since future projects with other packages are likely going to need higher alembic versions it would be nice to remove this limiting requirement. Maybe the issue of failing installs was fixed in higher alembic versions already.

### Other info / logs
```
Because mlflow (1.15.0) depends on alembic (<=1.4.1) 
and no versions of mlflow match >1.15.0,<2.0.0, mlflow (>=1.15.0,<2.0.0) requires alembic (<=1.4.1).
```

**Comment by dmatrix** [comment]
cc @harupy any comments on this requirement?

**Comment by amenck** [comment]
Is there any plan to address this? We have included `mlflow` as a requirement in some of our projects, which has limited us to using alembic 1.4.1. In practice I'm sure it would be fine to upgrade to a more recent version and just run the code, since we only use the client and definitely are not interacting with a DB via `mlflow`... however, since we have `mlflow` list in our, we would end up getting a conflict with `alembic` if we tried to update past 1.4.1.

At a broader level, it seems suboptimal that a library which we are using simply as a client has a requirement which involves DB interaction. Ideally, it would be great if there were a way to skip this entirely, since our use of `mlflow` does not involve any DB interaction.

**Comment by huxuan** [comment]
Same problem here, to be more specific. We joint the usage of `mlflow` and `airflow`. And in airflow v2, the least requirement for `alembic` package is `1.5.1`. Do we have any plans to upgrade that?

**Comment by jbvaningen** [comment]
I'd like to +1 this issue

**Comment by dbczumar** [comment]
Fortunately, https://github.com/mlflow/mlflow/pull/5249 has addressed this issue. Thank you for using MLflow!
