### ISSUE TITLE
[FR] Display max/min value of a metric in the experiments UI

### ISSUE THREAD

**Issue by dannyfriar** [mlflow/mlflow#4750]
## Proposal Summary
Allow displaying the max/min value of a metric for each run in the experiments UI. E.g. if logging a validation metric every epoch for NN training it would be useful to easily compare runs by the "best" value of the metric rather than the latest one.

## Motivation
Latest value of a metric for a specific run may not accurately represent how well the experiment run is doing. This would allow easily comparing experiment runs in the experiments UI when training NNs or boosted trees with early stopping.

Similar to: https://github.com/mlflow/mlflow/issues/1422

**Comment by niksbansode** [comment]
Hi,
I'm willing to contribute to this enhancement. I'll contribute to both UI and python server implementation. Below is the mocked screen for this enhancement. Min/Max values are calculated across the epochs for any particular run. 

![MinMaxFR](https://user-images.githubusercontent.com/19736733/131241756-391dea21-4cd0-4ed0-8095-2d65a7f1461f.png)

@dannyfriar please confirm if this enhancement is correctly aligned with the proposed solution.

**Comment by niksbansode** [comment]
Seems API changes are required, @harupy for that, changes might be needed in MlflowMessages.js which looks like proto file. How to generate that file? I'm not able to find necessary resources.
Here I'm facing difficulty:
For this enhancement, API response may look like this:
API: ajax-api/2.0/preview/mlflow/runs/get?run_id=3deb45d5572c4801ab3ee67a3395dd25
```
{
  "run": {
    "info": {
	....
	....
	....
    },
    "data": {
      "metrics": [
        {
          "key": "val_accuracy",
          "value": 0.8064516186714172,
          "timestamp": "1630175704448",
          "step": "4",
          "min_value": 0.7619577050209045,
          "max_value": 0.8109009861946106
        },
	....
	....
	....
        {
          "key": "loss",
          "value": 0.328249454498291,
          "timestamp": "1630175704448",
          "step": "4",
          "min_value": 0.328249454498291,
          "max_value": 1.4314649105072021
        }
      ],
      "params": [
        ....
	....
	....
      ],
      "tags": [
        ....
	....
	....
      ]
    }
  }
}
```

Here I have added min_value & max_value as additional parameters. Now I want to render them on UI but Metric prototype only return key value pair and we need max_value & min_value parameter. Could you please suggest an approach for this problem?

**Comment by dannyfriar** [comment]
Hi @niksbansode ,

Thanks for picking this up. This is aligned with what I was thinking although it would be good to see the min, max and latest (as is shown now) value of the metric in the table from your screenshot above.

Possibly as a follow-up but I think it would be useful to have an option to display either the min, max or latest in the table of experiment runs too. E.g. in the screenshot below, this is showing the latest value of `test_mse`.

![image](https://user-images.githubusercontent.com/10010084/131465191-ce460848-aa1d-416c-bbc2-141557ec4391.png)

**Comment by adamreeve** [comment]
Hi, I'm also willing to contribute this feature, assuming you're no longer interested @niksbansode? Otherwise if you're still working on this I'm keen to help out. It would be good to get some feedback on my proposed approach before implementing this though, as it looks like this will require reasonably significant changes. It looks like @harupy or @dbczumar, you're the best people for feedback here? This is what I'm thinking at the moment:

* Update the `RunData` protobuf message to include minimum and maximum metric values, eg:
```protobuf
message RunData {
  // Run metrics (latest values).
  repeated Metric metrics = 1;

  // Run parameters.
  repeated Param params = 2;

  // Additional metadata key-value pairs.
  repeated RunTag tags = 3;

  // Run metrics (minimum values).
  repeated Metric metric_minimums = 4;

  // Run metrics (maximum values).
  repeated Metric metric_maximums = 5;
}
```

* Add a new column to the `latest_metrics` table to differentiate between latest, minimum and maximum values. The migration script for this should create the new column with a default value corresponding to latest and then populate the table with minimums and maximums from the existing data, similar to the migration used when the `latest_metrics` table was initially added. Possibly we could make this optional if users have a lot of data to migrate and don't mind only getting min/max values for new runs. It would also be nice to rename this table to something like `summary_metrics`, although that might be a bit more disruptive.
* Update the minimum and maximum values in the DB when metrics are logged in the `SqlAlchemyStore`.
* Add support for getting minimum and maximum metrics with the `FileStore`.
* Update the UI to show minimums and maximums as well as latest values for single runs. Make sure this degrades nicely when using an older version store that doesn't provide min/max values.
* As a follow up PR, look into updating the UI for listing runs to allow showing min/max values and sorting by these.

**Comment by dbczumar** [comment]
Hi @dannyfriar @niksbansode @adamreeve. Apologies for the delayed response. I think we can leverage the existing GetMetricHistory API (https://mlflow.org/docs/latest/rest-api.html#get-metric-history) to implement this feature. This will require the frontend to scan the values of each metric and determine the min / max, but it should be much easier to implement than extending the `Metric` or `RunData` API, which is a major hurdle considering the number of organizations that implement their own MLflow Tracking services.

We'd be happy to review a pull request that implements this capability on the Runs page, as shown in the awesome mock provided by @niksbansode. In addition to Min & Max, we'd also want to display "Latest" (ideally, "Latest" would be displayed in the leftmost column).

**Comment by adamreeve** [comment]
Hi @dbczumar, computing the min and max on the UI side seems reasonable for the single run view, but showing the min/max values in the experiment view for multiple runs and potentially being able to sort and search based on the min/max values seems more useful, eg. to allow easily comparing runs, and that would probably require server side support.

I would think it should be possible to do this in a backwards compatible way, so that if a tracking API doesn't provide the min and max values then the UI just won't show them and won't allow sorting/searching by them (or maybe only show them in the single run view by falling back to the GetMetricHistory API).

I'd be happy to implement this in the single run view with min/max computation on the UI side as a starting point, but it would be great if there was a plan for how this can be supported in the experiment view too.

**Comment by dbczumar** [comment]
Absolutely, I agree that comparing and sorting runs based on min / max metric values would be quite helpful. I think it would be great to take incremental steps toward a solution, beginning with UIs for display min / max metric values for a single run. The next step we could take would be to display this information on the Compare Run page. After those, we can then work together to determine whether we want to update additional UIs (e.g. the runs table on the experiment page) or introduce expanded search support (e.g. including MIN / MAX clauses in the filter / order by strings).

**Comment by harupy** [comment]
#5574 implements this feature.

**Comment by addisonklinke** [comment]
@niksbansode I have a deployment of 1.29.0 (released well after this issue was closed). However, the metrics section of my run page UI does not match your [screenshot](https://github.com/mlflow/mlflow/issues/4750#issuecomment-907741736). There's only a value column (which shows the latest) and no min/max columns. Did that end up making it into the PR?

![image](https://user-images.githubusercontent.com/39926682/199810361-41a32cfc-bdda-4dbd-967b-394896b9721f.png)

@harupy there are several mentions of adding min/max metrics to the runs table on the experiment homepage
* On this issue by @adamreeve and @dbczumar 
* In https://github.com/mlflow/mlflow/issues/1422 by @stablum 

Is there an existing issue tracking progress towards that feature, or should we open a new one? This issue is the only title which seems like a match when I search for "experiment table metric max value"

**Comment by adamreeve** [comment]
Hi @addisonklinke, due to the high cost of retrieving all metric values when there a large number of metrics, this ended up being implemented slightly differently. Rather than showing the min and max values on the run page, the metrics page that you get to if you click on one of the metric names in your screenshot now has a table of latest, min and max values. If you view a metric from the run comparison page you can also compare values across runs.

See the discussion at https://github.com/mlflow/mlflow/pull/5517#discussion_r834535434 for more details, and #5574 is the PR that added the table to the metric page.
