### ISSUE TITLE
AttributeError: 'RestStore' object has no attribute 'get_experiment_by_name'

### ISSUE THREAD

**Issue by DorIndivo** [mlflow/mlflow#549]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
I am trying to implement simple tracking server using mlflow.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **MLflow installed from (source or binary)**: using pip
- **MLflow version (run ``mlflow --version``)**:0.6.0
- **Python version**: 3.6.5
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
```
import mlflow

mlflow.set_tracking_uri('http://my-mlflow-server:port')
client = mlflow.tracking.MlflowClient()
expr = client.get_experiment_by_name('test')

```
### Describe the problem
As you can see in the above code I'm trying to get the experiment object (similar to example in the documentation)  but the client object is RestStore and it is not has this function.
thank you

**Comment by dmarkhas** [comment]
Getting the same issue when calling set_experiment()

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    mlflow.set_experiment("wine-quality-test3")
  File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 41, in set_experiment
    experiment = client.get_experiment_by_name(experiment_name)
  File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/tracking/client.py", line 89, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
AttributeError: 'RestStore' object has no attribute 'get_experiment_by_name'

This only happens when using a remote tracking server (and as a result, using RestStore).
