### ISSUE TITLE
[FR]Add functionality to permanent delete of run from UI - removing from backend db and S3 artifacts

### ISSUE THREAD

**Issue by smiraldr** [mlflow/mlflow#5541]
## Proposal Summary

Does mlflow ui have an option to delete runs , experiment which reflects in the postgres backend and also automatically deletes s3 artifacts?
[https://github.com/mlflow/mlflow/issues/2152](url) This one had no resolution 

## Motivation
- Everytime I delete a run due to some improper triggering of any ml training , I have to manually locate the run in s3 and delete the artifacts to clear it.

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [✅ ] `area/artifacts`: Artifact stores and artifact logging
- [✅ ] `area/server-infra`: MLflow Tracking server backend
- [✅ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

**Comment by BenWilson2** [comment]
Does the client API's `.delete_run(run_id)` and `.delete_experiment(experiment_id)` not work for what you're looking to do?

**Comment by smiraldr** [comment]
I never tried using client api for deleting runs as I would have to fetch runs from db and was wondering if it works directly from UI now as this has been a known issue from sometime. Just to confirm does the .delete_run(run_id) delete a run completely from db backend and also delete it's existing s3 artifacts?

**Comment by BenWilson2** [comment]
Hi @smiraldr I see what you're looking for with regards to enabling UI support for this. Unfortunately, the scope of implementing such a feature is substantial when factoring in security, authentication, and properly handling access rights to delete (vs., say, view a run or experiment). We likely will not be looking at this in the short-term for a priority. We hear your request and we'll mark it for consideration for future work, but I can't promise you anything on when (or if) it will ever get done. Sorry for that.

To answer your question fully (my apologies for the drive-by answer before), the `delete_run()` and `delete_experiment()` functions are soft deletions only. Essentially it will mark a run or experiment in its lifecycle stage as "deleted" so that it will not show up on normal UI queries or API requests that do not explicitly request data with that lifecycle stage. 

To _permanently_ _delete_ the data from the `backend_store_uri` (artifacts and metadata), there is a cli command for this that can be run by an administrator: https://mlflow.org/docs/latest/cli.html#mlflow-gc  
With the execution of `mlflow gc --backend-store-uri <PATH> --run-ids <run_ids>` from the cli, 'cleanup' of runs that you are really sure that you don't want hanging around can be done without having to manually go through the s3 bucket.

I hope this helps.
