### ISSUE TITLE
[FR] Support for vanilla PyTorch autologging 

### ISSUE THREAD

**Issue by harishankar-gopalan** [mlflow/mlflow#5699]
Is there any plans for supporting autologging of parameters and metrics for vanilla Pytorch ? The main concern here is for frameworks like fairseq which are essentially models subclassed from torch.nn.Module.

Also is there any workaround to achieve it via MlFlow ? Any help would be greatly appreciated.

**Comment by dbczumar** [comment]
@akshaya-a Do you have input here?

**Comment by harupy** [comment]
Related tickets:

- https://github.com/mlflow/mlflow/issues/3230
- https://github.com/mlflow/mlflow/issues/2087

**Comment by harupy** [comment]
Not sure if this is useful, but you could create your own autologging like this:

```python
original_train = some_module.train

# Patch `some_module.train`
def new_train(*args, **kwargs):
    # Do pre trainining logging
    mlflow.log_params(...)
    model = original_train(*args, **kwargs)
    # Do post training logging
    preds = model(...)
    acc = compute_accuracy(preds, labels)
    mlflow.log_metrics(...)

some_module.train = new_train

# Use patched `some_module.train`
some_module.train(...)
```

The actual implementation is much more complicated.

**Comment by temporaer** [comment]
I understand that there's some effort on the way to make autologging work for vanilla pytorch. While that's in the works, would you be open to simply patching `pytorch.utils.tensorboard.SummaryWriter.add_scalar` for now to provide some bare-bones functionality instead of erroring out when pytorch-lightening is not installed?
