### ISSUE TITLE
Can I obfuscate the Git repository address when use Mlflow + Azure ML?

### ISSUE THREAD

**Issue by WillersonAbreu** [mlflow/mlflow#5823]
Hi, in our project we are using the Mlflow with a tracking URI pointing to Azure ML.
The trigger to execute our workflow is  triggered through the **mlflow.projects.run** method passing the project git address and other information.
My question is as follow: Can I obfuscate the git address when running our workflow through **mlflow.projects.run**?

Check printscreen from the info I want to obfuscate (marked red rectangle at the right):
![github_issue](https://user-images.githubusercontent.com/42680931/167006118-fbe175cc-94f8-4371-a82d-8b63d9bb3810.png)

**Comment by dbczumar** [comment]
@akshaya-a @wamartin-aml @trangevi Can you provide guidance here?

**Comment by Xctrunner** [comment]
@dbczumar thanks for alerting us - we'll discuss and get back to you next week

**Comment by wamartin-aml** [comment]
@dbczumar thanks for alerting us - we'll discuss and get back to you next week

**Comment by akshaya-a** [comment]
While @wamartin-aml  helps drive this discussion, @WillersonAbreu can you share a bit more information on at least the structure and source of this git repo url? Does it embed a secret, which is why you want to obfuscate it? Do you just want to remove showing that property even if an API caller can retrieve it?

Happy to learn more about the reasoning so we can deliver a solution at the right layer for you

**Comment by WillersonAbreu** [comment]
> While @wamartin-aml helps drive this discussion, @WillersonAbreu can you share a bit more information on at least the structure and source of this git repo url? Does it embed a secret, which is why you want to obfuscate it? Do you just want to remove showing that property even if an API caller can retrieve it?
> 
> Happy to learn more about the reasoning so we can deliver a solution at the right layer for you

You are right! We are using a Personal Access Token to enable the mlflow to access the repository. So, we want to at least obfuscate this token.

**Comment by akshaya-a** [comment]
@WillersonAbreu as a short term thing, can you try setting AZUREML_GIT_REPOSITORY_URI as an env var *where you are submitting from* (that is, where you run mlflow.projects.run) not as an env var in the remote job

**Comment by WillersonAbreu** [comment]
> @WillersonAbreu as a short term thing, can you try setting AZUREML_GIT_REPOSITORY_URI as an env var _where you are submitting from_ (that is, where you run mlflow.projects.run) not as an env var in the remote job

Ok, I will try this implementation at next monday and get back with the results.

**Comment by WillersonAbreu** [comment]
@akshaya-a I've tried the short term implementation, but the git repo address continues to be shown at Azure ML.
How can you see below, I've created the env variable AZUREML_GIT_REPOSITORY_URI on my OS:
![env_var](https://user-images.githubusercontent.com/42680931/167417109-33462f2c-ec91-4173-b8a2-35cc882fd1b4.png)

And I'm submitting the experiment as shown below:
![projects_run](https://user-images.githubusercontent.com/42680931/167417602-e0d4b8be-9e9d-4fbd-9778-d0be9e77db4f.png)

I also tried to omit the **uri** parameter from mlflow.projects.run, but the parameter is required for this method.

**Comment by akshaya-a** [comment]
@WillersonAbreu apologies for the weak guidance - let me confirm on my own repro and get back to you. Just to clarify, you're setting the AZUREML_GIT_REPOSITORY_URI to a dummy value like "ignoreme" instead of your actual URI, correct? The point is whatever is in this variable overrides what you see in the UI, while leaving the actual snapshotted project correct (so don't change how you invoke mlflow.projects.run)

**Comment by akshaya-a** [comment]
And yes, @WillersonAbreu I'm able to confirm this works on my end. Perhaps you can try setting it right before submitting? ie
`
import os
os.environ["AZUREML_GIT_REPOSITORY_URI"] = "dummyvalinmem"
submitted_run = mlflow.projects.run(...)
`

![image](https://user-images.githubusercontent.com/16749003/167529435-60fbb343-de27-4b45-9fff-a28feb03c911.png)

**Comment by WillersonAbreu** [comment]
@akshaya-a I thought that I had to use the env variable instead of use the URI into the mlflow.projects.run but now it's ok, the URI was obfuscated on Azure ML UI. You've help me a lot, the way you supported me I never seen before. Thank you so much for the support!!!

**Comment by WillersonAbreu** [comment]
@akshaya-a I have more one question. My main entry point execute another entry points as child (I'm using **mlflow.run** like the multi step workflow example) and the Git URI is passing as tags for all the child. Exists a way to obfuscate the URI of the tags?

**Comment by akshaya-a** [comment]
@WillersonAbreu can you clarify exactly how you're submitting the children? At a high level, any process that you spawn, if you set the above environment variable, it will override the value that AzureML even receives, let alone shows in the UI. So by setting AZUREML_GIT_REPOSITORY_URI to a dummy value in any process you start, you never even send AML that secret.

You mention tags, though, so I might be misunderstanding something. The above git uri is stored in an AML-only location called "properties" - you can think of them as MLflow "readonly" tags. If you're seeing the git uri in tags somewhere, it is unlikely that AML is setting them. There's also a simple fix if it is tags, because tags are not readonly and you can just mlflow.set_tags() to whatever you want whenever you want.

Hope that helps and feel free to elaborate on the exact code for creating the children and what you're seeing in case the above doesn't work

**Comment by WillersonAbreu** [comment]
> @WillersonAbreu can you clarify exactly how you're submitting the children? At a high level, any process that you spawn, if you set the above environment variable, it will override the value that AzureML even receives, let alone shows in the UI. So by setting AZUREML_GIT_REPOSITORY_URI to a dummy value in any process you start, you never even send AML that secret.
> 
> You mention tags, though, so I might be misunderstanding something. The above git uri is stored in an AML-only location called "properties" - you can think of them as MLflow "readonly" tags. If you're seeing the git uri in tags somewhere, it is unlikely that AML is setting them. There's also a simple fix if it is tags, because tags are not readonly and you can just mlflow.set_tags() to whatever you want whenever you want.
> 
> Hope that helps and feel free to elaborate on the exact code for creating the children and what you're seeing in case the above doesn't work

@akshaya-a I'm submitting the children this way on my main script (Note that the main (parent job) script is submitted from one Airflow DAG using the **mlflow.projects.run:**): 
![children_call](https://user-images.githubusercontent.com/42680931/167708207-78036630-7349-41ca-913d-0e8f55637d67.png)

Submitting this way, each child receives some tags from parent, among these tags the **mlflow.gitRepoURL** and
**mlflow.source.git.repoURL** presents the Git URI, but the parent haven't any Git URI tag, only that property that we are using the value of AZUREML_GIT_REPOSITORY_URI that we are setting with antoher value that isn't the Git URI.


Take a look at the print of one the children:
![child_tags](https://user-images.githubusercontent.com/42680931/167709933-af2f9a06-520a-4fce-8b35-208cfc57bc16.png)
