### ISSUE TITLE
Feature request: Support for automated machine learning (AutoML) libraries

### ISSUE THREAD

**Issue by narcisapantilimon** [mlflow/mlflow#616]
Hello,

Thank you for making this project happen!

I was wondering if you are planning to add suport for AutoML libraries?

Here are some libraries:

- H2O Driverless AI http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/index.html
- Auto-Keras https://autokeras.com
- Auto-Sklearn https://automl.github.io/auto-sklearn/stable/

Thanks,
Narcisa

**Comment by mparkhe** [comment]
We are looking at various options. We started with adding an [example for hyperparam tuning](https://github.com/mlflow/mlflow/tree/master/examples/hyperparam) using gpyopt. 

In the mean time if you want to contribute to this project we would appreciate that.

**Comment by smurching** [comment]
Thanks @narcisapantilimon for filing this issue - closing for now, since the issue was filed we've implemented auto-instrumentation (autologging) for Keras, Tensorflow, and several other frameworks. It's not quite AutoML but hopefully makes it easier to record data to MLflow when using AutoML frameworks built off of Keras, TF, etc - let us know if you have any questions & thanks!
