### ISSUE TITLE
Enhancement: Dyanmodb as an alternative to Filestore.

### ISSUE THREAD

**Issue by brightsparc** [mlflow/mlflow#644]
### System information
- **Have I written custom code**: Dynamodb store 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.6  / linux
- **MLflow installed from (source or binary)**: source
- **MLflow version**: mlflow, version 0.7.1.dev0
- **Python version**: Python 3.7.0

### Summary
I have extend the [server handler](https://github.com/mlflow/mlflow/pull/640/files#diff-8ebe71d6560f997a5e24b5e5536d614b) treating the `file-store` as a URI, adding support for a `dynamodb://mlflow` where the path is optional and is the table prefix eg:

```
mlflow server \
    --file-store "dynamodb://mlflow" \
    --default-artifact-root s3://my-mlflow-bucket/ \
    --host 0.0.0.0
```

I have included a cloud formation script to create the following tables and global secondary indexes (GSI), the parameters are table_prefix and read (RCU) & write (WCU) capacity units.

* `mlflow_experiment` (HASH: experiment_id, GSI HASH: lifecycle_status, RANGE: name)
* `mlflow_run` (HASH: run_uuid, GSI HASH: lifecycle_status, RANGE: experiment_id)
* `mlflow_run_param` (HASH: run_uuid, RANGE: key)
* `mlflow_run_metric` (HASH: run_uuid, RANGE: key)
* `mlflow_run_tag` (HASH: run_uuid, RANGE: key)

Default AWS credentials or IAM role are requried, AWS region will be picked up from environment.

Additional environment variables are supported to use a local dynamodb endpoint, or table prefix.
* `MLFLOW_DYNAMODB_ENDPOINT_URL`
* `MLFLOW_DYNAMODB_TABLE_PREFIX`

### Source code / logs
Added `dynamodb_store` which implements persistence for experiments/runs/metrics but not artifacts (which can be left to the `artifact_repo`).  

See: https://github.com/mlflow/mlflow/pull/640

**Comment by smurching** [comment]
@brightsparc MLflow >=1.0 contains support for logging to SQL backend stores instead of the FileStore (see the [tracking server](https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers). It's also now possible to implement a plugin that handles a custom tracking URI, if you'd like to implement a DynamoDB store as an external plugin - see [this example](https://github.com/mlflow/mlflow/tree/1c85add051ccf88a570ac5c809180f630238c109/tests/resources/mlflow-test-plugin) of a tracking plugin. Closing for now but please reopen if anything comes up!

**Comment by brightsparc** [comment]
I am revisiting this to create a plugin based on the latest code a new architecture.
