### ISSUE TITLE
C++ API?

### ISSUE THREAD

**Issue by sepidehhosseinzadeh** [mlflow/mlflow#666]
Is there someone started to implement the c++ API?

**Comment by mparkhe** [comment]
Hi @sepidehhosseinzadeh: Thanks for the interest. Currently, MLflow supports SDKs in Python, Java, and R, since these were the top 3 languages used for ML. I am curious to learn more about your C++ ML use case and particularly the need for C++ API. How will you be using this and do you have other Python/Java/R code that wraps the C++ ML code where you could use mlflow?

Thanks,
mani

**Comment by sepidehhosseinzadeh** [comment]
Hi @mparkhe : 
I have a project which the language is c++, and I am using Caffe for experiments. 
I have some python codes too. For now I need basic APIs like logParam, ...

Many Thanks

**Comment by sepidehhosseinzadeh** [comment]
I already started the C++ API, trying to mimic the Java API, but I am having errors in even basic functions (LogParam, LogMetric).

**Comment by mparkhe** [comment]
Hi @sepidehhosseinzadeh:

One of the things I am not clear on is why you could not use python SDK. What is the interface between your python and C++ code? Are you using C++ for the entire model training flow as well? 

We talked about this internally in the team and a couple of alternatives were suggested by the team

- Using Caffe callbacks and inside the callbacks use python SDK. Here's [an example](https://stackoverflow.com/questions/41490526/what-are-solvers-callback-functions-in-pycaffe-and-how-can-i-use-them).

- Using [python embedding](https://docs.python.org/2/extending/embedding.html) in your C++ code. You can create the interpreter in `main()` and reuse in your training.

If you cannot use the above 2, can you please describe the use case and also why you need C++ SDK to make your flow work. We try to keep the footprint limited based on use cases, so for instance we have python, R, and Java SDKs that interface with the rest client. The plan is to extend SDKs and various types of implementations very carefully. The reason here is so that these can be well unit tested and can continued to be maintained over time.

mani

**Comment by Raffaello** [comment]
You can still bind c++ in python and so wrapping your routine into python interface to communicate with mlfoow

**Comment by max-allen-db** [comment]
Hey @sepidehhosseinzadeh did you see the options laid out above? I think they could be good options for you. 

As for the C++ API, I don't think our team sees enough use cases that mandate a separate C++ API  to build, test, and maintain it for a long period of time. For that reason, we're going to close this issue.

**Comment by rilesdg3** [comment]
I vote for a c++ api. I do all my ai/data science/machine learning in c++.
