### ISSUE TITLE
Unable to log "Turicreate" Model

### ISSUE THREAD

**Issue by GautamKumarSkyPointCloud** [mlflow/mlflow#6836]
type(model) --> turicreate.toolkits.recommender.item_similarity_recommender.ItemSimilarityRecommender

    class SklearnModelWrapper(mlflow.pyfunc.PythonModel):
   
        def __init__(self, model):
            self.model = model
    
        def predict(self, context, model_input):
            return self.model.predict(model_input)
    
    wrappedModel = SklearnModelWrapper(model)
    conda_env = {
        "name": "mlflow-env",
        "channels": ["conda-forge"],
        "dependencies": [
            "python=3.7.0",
            {
                "pip": [
                    "turicreate"
                ],
            },
        ],
    }
    
    with mlflow.start_run(run_name="TestExperiment", experiment_id = "12345"):
        mlflow.pyfunc.log_model(artifact_path ="testModel",python_model=wrappedModel,conda_env = conda_env )

getting the following error:
TypeError: self._base_ptr,self.thisptr cannot be converted to a Python object for pickling

**Comment by BenWilson2** [comment]
This isn't an MLflow issue. This is an issue with https://github.com/apple/turicreate and its inability to be pickled. We don't provide support or guarantees for the functionality of arbitrary packages. In order to get this to work, you'd have to create a custom flavor plugin that would handle alternative serialization to pickle. 
One option is to use the pyfunc flavor (if that works for your use case). The other is to create your own flavor that you can use in your environments.
Guidelines for creating custom flavor plugins can be found here: [model-customization in MLflow](https://www.mlflow.org/docs/latest/models.html#model-customization )
