### ISSUE TITLE
Support for storing artifacts in remote server instead of file store

### ISSUE THREAD

**Issue by anabel1012** [mlflow/mlflow#697]
Hello,

We are planning to use mlflow to track our experiments on our company. We would like to store our artifacts in the remote server but when we start a run on another machine, the tracking uri is set to local althought the three folders (artifacts,metrics,params) are moving to the server. The artifacts folder appears empty while in the local machine it has the files.
Is there any way of having the artifacts in the remote server?

**Remote server** (192.168.159.140): mlflow server --file-store experiments --default-artifact-root experiments/artifacts --host 0.0.0.0 

**Server with experiments:**  export MLFLOW_TRACKING_URI='http://192.168.159.140:5000'

Thanks,
Anabel

**Comment by mateiz** [comment]
Hi Anabel,

To let jobs store data remotely, you need to use one of the remote file stores, such as NFS, SFTP, or Amazon S3, as described here: https://mlflow.org/docs/latest/tracking.html#supported-artifact-stores. You need to set the default-artifact-root to a URI in one of these formats. Right now, because you set it to `experiments/artifacts`, this is treated as a file system path on your local file system on each machine (this is definitely confusing but it would be useful if you had actually mounted a remote file system at that path).

**Comment by lumamachiron** [comment]
any updates?

**Comment by dbczumar** [comment]
Hi @lumamachiron, we introduced artifact streaming through the MLflow server in MLflow 1.23.0. Additionally, the MLflow tracking server now operates in this mode by default as of MLflow 2.0. You can find more information on https://mlflow.org/docs/latest/tracking.html, specifically https://mlflow.org/docs/latest/tracking.html#using-the-tracking-server-for-proxied-artifact-access. Thank you for using MLflow!
