### ISSUE TITLE
Feature request: Multi-user support for tracking and UI

### ISSUE THREAD

**Issue by calio** [mlflow/mlflow#724]
### Describe the problem
It would be nice to run mlflow tracking and mlflow ui as a central service to allow multiple user send their data to tracking API and view and share their results from central service.

For each user, it would be nice to give each of them an 'namespace', so each user only log to their own namespace. When accessing the UI, they pass the 'namespace' as a parameter and then the UI only show their own experiments. 

Users can share their experiment result with a URL with have their namespace in it. Proper access control can be added later.

**Comment by elgalu** [comment]
Are there plans to add multi-tenants support to MLFlow or is it out of scope ?

**Comment by smurching** [comment]
Sorry for the delayed response! We don't immediately plan to add this in open-source, but if there is a pluggable way to do this without requiring all implementors of the REST API / all client APIs to add a new parameter, we'd be open to hearing proposals (see the new [feature request template](https://github.com/mlflow/mlflow/blob/master/.github/ISSUE_TEMPLATE/feature_request_template.md)).

**Comment by raman-nbg** [comment]
I would also be interested in a solution for this. Are there any updates?

I don't know the existing architecture of mlflow in detail to design a good solution. If it is not possible to add multi-user support and access management to the existing components a gateway/proxy may could help.

At least we have to add a Authorization-Header to the REST API (or something similar) to identify the requesting user (= authentication). Also we have to categorize everything in namespaces (or name it "tenant", "space", "bucket", "context" ...) to avoid collisions (= authorization).

**Comment by sansagara** [comment]
Nice to see this is at least considered. I was wondering, since i saw this:

> We don't immediately plan to add this in open-source, but...

Is this actually something that enterprise plans include?

**Comment by Dhaval08** [comment]
Any update regarding the multi-tenancy feature?

**Comment by houqp** [comment]
@smurching do you know if MLFlow is open to accept contributions from the community for multi-user and role based access control support?

**Comment by elgalu** [comment]
probably not, as this might be an enterprise (paid) feature already

**Comment by tianlinzx** [comment]
Any Progress on this ?

**Comment by nreith** [comment]
> Sorry for the delayed response! We don't immediately plan to add this in open-source, but if there is a pluggable way to do this without requiring all implementors of the REST API / all client APIs to add a new parameter, we'd be open to hearing proposals (see the new [feature request template](https://github.com/mlflow/mlflow/blob/master/.github/ISSUE_TEMPLATE/feature_request_template.md)).

Been a long time, but the 2019 reply seemed open as long as they don't need to add a new parameter to every single api call. That sounds reasonable and means we just need to put our brains together and come up with a way to implement a plugin or wrapper without hacking the core code to bits. Should be doable with some creativity. Have those who are asking done any work on this?

**Comment by Talador12** [comment]
From #6108 and @dbczumar 

> At this time, we do not plan to build native auth / user management capabilities into MLflow

Would this be open to contributions? This is something that I have seen as a request from multiple teams/companies.

For examples of different ways we could approach this, here are similar solutions for different tools, and some are in current development.
https://www.kubeflow.org/docs/components/multi-tenancy/design/
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/
https://argoproj.github.io/argo-workflows/workflow-rbac/
https://airflowsummit.org/sessions/2022/multitenancy-is-coming/

**Comment by cao-nv** [comment]
We all really want to have multi-tenancy built in MLFlow, but this feature requires too much effort.

**Comment by harupy** [comment]
This document proposes an opt-in authentication/authorization mechanism using Flask's before_request and after_request hooks: https://docs.google.com/document/d/1VpYM8MBOrY71tYr3C80xwJi_xWa94u4hSIKVjYuTJc0

The proposed mechanism:

- protects MLflow resources (experiments, runs, etc.) and UI using Basic authentication.
- allows users to share their resouces with others.
- provides a simple signup for user registration.

We'd appreciate any feedback on the proposal!

cc @jmahlik would you be interested in working on implementing the proposal with us (asking because you worked on #7757)?

cc @dbczumar

**Comment by jmahlik** [comment]
I'd for sure be interested in at least providing feedback after giving it a read over. Potentially working on some smaller PR's toward the end goal. Sounds highly beneficial.

**Comment by harupy** [comment]
@jmahlik Thanks for the reply! Can you comment on the doc?

**Comment by nreith** [comment]
I still think this would be a valuable addition, but really since mlflow can't handle a lot of models and a lot of concurrency, it isn't equipped to be one monolithic deployment that handles multiple teams. We've found at my work that it is appropriate to have one mlflow instance per team or per project for a few reasons. One, after too many models and versions are stored, the ui becomes sluggish. Also, most users ignore naming conventions and this leads to clutter, so they don't want to share an instance with others they don't know. The lack of one more nested level of organization for "project-teams" means separate instances fulfills this function.

Auth and instance (container) management is still useful though. Auth can be done with a simple nginx wrapper like some examples you can find out there, with shared credentials (service account), or with something like AD if you find an nginx example to integrate with sso/ad. The approach we would suggest is embedding the mlflow container in something else that handles both auth and spinning up/down of instances to manage resources if they go idle for a long time. Think jhub or kubeflow.

Before any of this, I think a higher priority though might be to refactor the flask app part of mlflow to be a fastapi app, so it can leverage the faster and more efficient (newer) ASGI (Asynchronous Server Gateway Inteface) instead of the older WSGI used by flask. It's possible this could be improved/changed while keeping flask, which might minimize the need for refactoring. https://flask.palletsprojects.com/en/2.2.x/deploying/asgi/

I'm not sure which of these approaches is best, but ASGI would probably help performance with lots of concurrent api calls (necessary with multiple teams). Not sure what can be done about the sluggish UI in cases with lots of content. That's probably a separate issue.

The fastapi approach would also allow inclusion of auth in the same framework, without an extra nginx wrapper if that's desirable.

Just some thoughts.

**Comment by harupy** [comment]
@jmahlik Invited you in the community slack. We can discuss there if you want.

**Comment by avivio** [comment]
We use DagsHub for multi-tenancy, since it creates a separate MLflow sever with each repository, and this also includes authentication and access controls. 
See:
https://dagshub.com/docs/integration_guide/mlflow_tracking/index.html

**Comment by dbczumar** [comment]
Hi folks, MLflow 2.5 includes multi-user support with a standardized, extensible permissions system. Please check it out and provide feedback: https://mlflow.org/docs/latest/auth/index.html.

Thank you for your patience and your inputs!
