### ISSUE TITLE
[SETUP-BUG] - MLFlow / Google Colab compatibility issues.

### ISSUE THREAD

**Issue by ramsey-superpedestrian** [mlflow/mlflow#7367]
### System information

- ** Google Colab
```
> cat /etc/*release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- **MLflow installed from (source or binary)**: binary: aka `pip install mlflow==2.0.1`
- **MLflow version (run ``mlflow --version``)**:  `ERROR: Could not find a version that satisfies the requirement mlflow==2.0.1`
- **Python version**: 3.7

### Code to reproduce issue

```bash
pip install mlflow==2.0.1
```

### Describe the problem

It looks like about 3 weeks ago, mlflow 2.0.1 was released and this PR https://github.com/mlflow/mlflow/pull/7161

But it's not clear why MLFlow (client) stopped supporting 3.7 and the Google Colab platform is locked to 3.7

By locking MLFlow 2.0.1 to python 3.8, mlflow constrains Google Colab users to MLFlow 1.3.0.  And because the MLFlow 2.0.1 server does not appear to be compatible with mlflow 1.3.0, this constrains organizations which use Google Colab to also use mlflow server 1.3.0.

It's possible that you intended for mlflow server 2.0.1 to be backwards compatible.  In which case I will submit a bug regarding an incompatibility between mlflow client 1.30.0 and and mlflow server 2.0.1, but it's not clear whether this should be addressed by providing a patch to the client or a patch to the server.

### Other info / logs

When running mlflow server 2.0.1 and using mlflow client 1.3.0

Following the instructiongs here: https://www.mlflow.org/docs/1.30.0/model-registry.html#adding-an-mlflow-model-to-the-model-registry

```python
import mlflow
mlflow.set_tracking_uri("https://my.remote.server")  # Running mlflow 2.0.1 server
mlflow.set_registry_uri("https://my.remote.server")
```

```python
from mlflow import MlflowClient

client = MlflowClient()
client.create_registered_model("test")
```

This results in the stack trace:

```
[/usr/local/lib/python3.7/dist-packages/mlflow/tracking/client.py](https://localhost:8080/#) in create_registered_model(self, name, tags, description)
   1845             description: This sentiment analysis model classifies the tone-happy, sad, angry.
   1846         """
-> 1847         return self._get_registry_client().create_registered_model(name, tags, description)
   1848 
   1849     def rename_registered_model(self, name: str, new_name: str) -> RegisteredModel:

[/usr/local/lib/python3.7/dist-packages/mlflow/tracking/_model_registry/client.py](https://localhost:8080/#) in create_registered_model(self, name, tags, description)
     57         tags = tags if tags else {}
     58         tags = [RegisteredModelTag(key, str(value)) for key, value in tags.items()]
---> 59         return self.store.create_registered_model(name, tags, description)
     60 
     61     def update_registered_model(self, name, description):

[/usr/local/lib/python3.7/dist-packages/mlflow/store/model_registry/rest_store.py](https://localhost:8080/#) in create_registered_model(self, name, tags, description)
     81             CreateRegisteredModel(name=name, tags=proto_tags, description=description)
     82         )
---> 83         response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
     84         return RegisteredModel.from_proto(response_proto.registered_model)
     85 

[/usr/local/lib/python3.7/dist-packages/mlflow/store/model_registry/rest_store.py](https://localhost:8080/#) in _call_endpoint(self, api, json_body, call_all_endpoints)
     62         else:
     63             endpoint, method = _METHOD_TO_INFO[api]
---> 64             return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
     65 
     66     # CRUD API for RegisteredModel objects

[/usr/local/lib/python3.7/dist-packages/mlflow/utils/rest_utils.py](https://localhost:8080/#) in call_endpoint(host_creds, endpoint, method, json_body, response_proto)
    278             host_creds=host_creds, endpoint=endpoint, method=method, json=json_body
    279         )
--> 280     response = verify_rest_response(response, endpoint)
    281     js_dict = json.loads(response.text)
    282     parse_dict(js_dict=js_dict, message=response_proto)

[/usr/local/lib/python3.7/dist-packages/mlflow/utils/rest_utils.py](https://localhost:8080/#) in verify_rest_response(response, endpoint)
    212             raise MlflowException(
    213                 "%s. Response body: '%s'" % (base_msg, response.text),
--> 214                 error_code=get_error_code(response.status_code),
    215             )
    216 

MlflowException: API request to endpoint /api/2.0/preview/mlflow/registered-models/create failed with error code 404 != 200. Response body: '<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

Which seems to indicate that the mlflow 1.3.0 client expects a url that the mlflow 2.0.1 server doesn't support.

Normally I would solve this by upgrading the client, but the new constraint of using python 3.8 means that I can't do this if I want to use Google Colab as a jupyter notebook platform.

**Comment by ramsey-superpedestrian** [comment]
After a little extra experimentation trying to loosen this version constraint, it appears that decision that is forcing the upgrade to python 3.8 is the use of assignment expressions.

Would you consider replacing the assignment expressions with their equivelant python3.7 code to permit Google Colab users to utilize the MLFlow 2.0 client?

**Comment by ramsey-superpedestrian** [comment]
It also appears that there's only 1 use of assignment expressions on line `mlflow/_doctor.py:81`

```python
if (runtime := get_databricks_runtime()) is not None:
```

This line could just be replaced with
```
runtime = get_databricks_runtime()
if runtime is not None:
```

Which would allow the constraint to be loosened to 3.7

**Comment by BenWilson2** [comment]
Hi @ramsey-superpedestrian . We're sorry that you're encountering this issue. 
A bit of context for why we made this change:

The scientific computing community has been following the lead that the numpy team has set with this notification: 
https://numpy.org/neps/nep-0029-deprecation_policy.html

As of 12/26/2021, Numpy's official support of Python 3.7 was dropped. In their follow-up release, this support was dropped. Soon after, many packages that depend on numpy (the majority of the ML-focused integrations within MLflow) also dropped support for Python 3.7. Due to the fact that many packages dependencies do not specify version-pinning of their packages, including support for a 'dropped' language support in MLflow would leave a problematic experience for users of MLflow with frustrating dependency issues to resolve. 

Because of this, we've followed suit with the NEP-29 policy and removed Python 3.7 support with the 2.0.1 release of MLflow last week. 

I know this is frustrating that this limits you from using newer versions of MLflow within Google collab. Based on this issue 2165 on the collabtools repository, I don't think that you're alone in experiencing issues with deprecation and the otherwise complex steps required to update collab to support a more modern version of Python from within the Jupyter kernel (although it is entirely possible to do so with conda or virtualenv). 

I wish I had better news for you here, but due to the overwhelming number of tooling packages that have dropped support for Python 3.7 (the count of which is continuing to rise), I think your best course of action will be to either file an issue with the collab project to follow suit with NEP-29 or provide a simpler means of upgrading the kernel python version. 
We won't be reverting this change as it is not a bug, but rather is an intended act of stability for our users. 

Regarding the 2nd portion of your issue "In which case I will submit a bug regarding an incompatibility between mlflow client 1.30.0 and and mlflow server 2.0.1, but it's not clear whether this should be addressed by providing a patch to the client or a patch to the server." This won't be addressed either. 2.0.1 is a breaking change release (hence the major version declaration) and as such there is no plans to enable full compatibility with all features wherein the client is an older version than the server. If we were to address this compatibility, we would have to perform patch releases to all 1.x released versions that have been released within the last year which would be an incredibly time-consuming endeavor for effectively zero net benefit. 

Here's a good example of the bash commands to use miniforge to get your notebook environment to use an updated version of Python: https://gist.github.com/ngrislain/c3ba6f687c64ce31adc6b0dff1b26d6a?permalink_comment_id=4141168#gistcomment-4141168 (hope this helps!)

**Comment by ramsey-superpedestrian** [comment]
Thank you for the thoughtful response.

This is most unfortunate news.

Yes, I came across this post, but it seemed unlikely that this was the preferred method.  I suppose it'll have to do.  It's likely to substantially impede adoption.  It seems that this solution requires the use of a modified ipynb file.

It's going to be a difficult choice, either we: a) commit to using mlflow server 1.30.0 which means going through a migration later,  b) train all interested parties in the custom ipynb file approach,  c) run and support our own notebook server,  or d) select a different mlops toolset.

Ufff.

Well, I'm sorry you had to be the bearer of bad news.
