### ISSUE TITLE
Auth for API and MLFlow server

### ISSUE THREAD

**Issue by KevYuen** [mlflow/mlflow#761]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **MLflow installed from (source or binary)**:  Binary
- **MLflow version (run ``mlflow --version``)**: 0.8.0
- **Python version**: 3.7.1
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Authentication for the MLFlow server and APIs. Currently, there aren't any mechanism to ensure that third parties do not abuse the API or the UI. 

I think it'd be a great feature to have a layer of authentication on top of MLFlow that can be enable/disable and configure via environment variable. 

I am interested in contributing if this is something the community think is reasonable.

**Comment by KevYuen** [comment]
Looks like the community has already thought about this issue, and have some opinion on how ACL should be implemented. I will close this issue. 

@mparkhe Thanks for the information!

**Comment by mohammedi-haroune** [comment]
Hello, this is an old question but we tried the solution suggested by @matei and we hit a dead end because of the following reasons

- Nginx `auth_request` erases the data before sending `/authorize` requests and MLFlow sends the `experiment_id`/`run_id` in the data of `POST` and `UPDATE` requests instead of the URL (`POST /tracking/experiments/1`), this makes it impossible to authorize such requests, we are denying all them right now.
- We can't filter out the list of the experiments a user can see, we can only allow them to do a request or not. If we don't allow them to see the list of experiments, the front page of MLFlow will broken.

I think access control mechanics over MLFlow resources should be implemented in MLFlow itself or in an MLFlow plugin, that way we'll have access to the database, the UI and everything we need to implement such features. Or at least think about how third party applications can do that and makes it possible for them
