### ISSUE TITLE
[BUG] mlflow run in system environment not possible

### ISSUE THREAD

**Issue by mattijsdp** [mlflow/mlflow#7856]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: linux (amd64); OS image: Amazon Linux 2
- **Python version**: Python 3.10.9
- **yarn version, if running the dev UI**: na

### Describe the problem

The mlflow documentation ([here](https://mlflow.org/docs/latest/projects.html#project-environments)) explains that mlflow supports four project environments: Virtualenv environment, conda environment, Docker container environment, and system environment. The mlflow run command also allows you to specify an env_manager from: local, conda, virtualenv. In my MLproject file I have a docker container environment specified but I would like to be able to occasionally run my project in the system environment. I had expected that specifiying a local env_manger would not use my docker container environment. However it seems that specifying a local env_manager does the same as if no env_manager was specified. It still runs it with the standard local backend meaning it uses my docker container environment.

My use case for this behaviour is that I want to run training locally in a docker container environment but also have some scheduled training runs running in a Kubernetes cluster where I use another tool (Prefect) to handle creating the pod etc and as such want mlflow to run in the system environment of the pod/container but currently have to remove the docker_env specified when uploading my MLproject file.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```python
import mlflow

# assuming a MLproject file is specified with a suitable entrypoint and docker env specified e.g.:
# name: test_system_project
# docker_env:
#   image: some_image_url
# entry_points:
#   main:
#     command: "python some_script.py"

mlflow.run(
    uri=".",
    experiment_name="test_experiment",
    env_manager="local"
)
```

### Stack trace

```
na
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment]
The local environment manager would be the local instance within the container's run context (as opposed to using conda or virtualenv from within the docker container). If you're looking to execute a model saved within a container context, from your local environment, can't you just point directly to the `some_script.py` to execute a test from the local OS?

**Comment by BenWilson2** [comment]
An alternative that you might want to think about:
Open access to your local file system from within your docker container so that you can access the model directly from this opened port and shared file system path.

**Comment by BenWilson2** [comment]
Guidance on accessing bind points can be found here: https://docs.docker.com/storage/ 
Closing this issue.

**Comment by mattijsdp** [comment]
@BenWilson2 When specifying conda as the project environment is this not instead of the docker environment? So that mlflow creates a new conda env (not inside a container per se) and runs it inside that conda env?

In the same way, I want to run it in its current system environment so not have it create a docker container. As explained above I have another package that creates a container and I want mlflow to then simply run in that container's local (not create a docker env, conda env or anything else).

**Comment by BenWilson2** [comment]
I'm afraid I don't follow. If you have MLflow specify "conda" or "local" but you have the project configured to run in Docker, then it will use a conda environment or the local environment within the docker container's isolated process encapsulation. 
If you want to run the model within the local system environment, you can just log the model to the tracking server, use the native flavor or pyfunc flavor implementation to load the model from the tracking server's artifact registered location and use the model. 
With your 2nd statement above, the expedient thing to do is to build your 'external container' such that the registered model artifact is loaded into that container that contains the rest of your code and infrastructure. 
If that's not appealing to you, you'll have to look into secure ways of running DinD (Docker in Docker). There are plenty of advanced guides on the internet to help you get started. Here's one: https://hub.docker.com/_/docker Here's another: https://blog.nestybox.com/2019/09/14/dind.html 
Keep in mind that you'll have to run with elevated privileges in order to get it working. You might want to consider sibling containers as that is a far safer bet. 
However, none of this is officially supported by MLflow and we don't provide guidance on how to tackle these advanced use cases of Docker. Best of luck!
