### ISSUE TITLE
Integrate Data Versioning

### ISSUE THREAD

**Issue by slavakurilyak** [mlflow/mlflow#867]
As a developer, I want to leverage data version control libraries (i.e. [dvc](https://dvc.org/), [pachyderm](https://pachyderm.io/), or [dat](https://datproject.org/)), so that I can more easily keep track of files and data sets.

**Comment by slavakurilyak** [comment]
Also consider [Git Large File Storage (LFS)](https://git-lfs.github.com/) for large file versioning

**Comment by slavakurilyak** [comment]
@rctatman at @Kaggle has written on the [reproducibility of machine learning literature](https://openreview.net/forum?id=B1eYYK5QgX). She believes that the highest level of research reproducibility requires code, data and an environment.

**Comment by gerardsimons** [comment]
Take a look at [dvc](https://dvc.org/doc/get-started) dataset versioning; it seems like people integrate mlflow into dvc pipelines.

**Comment by amesar** [comment]
Here's a proposed solution in general terms.

Treat data versioning in a similar manner to code versioning. MLflow does not actually implement code versioning. Instead it delegates code versioning to git (mlflow.source.git.commit tag). For data versioning, we should similarly delegate it to custom providers.

Overview:
- Data versioning is more complex than code versioning. For code we simply have to deal with Python and its conventions. There is much more variety with data: file or folder, cloud vendor-specific APIs, local file system, etc.
- Add a new object to Run (or Run.Data) called DataSource. 
- DataSource would be an extensible plug-in similar to artifact repository.
- DataSource itself is an abstract class that contains a Validator and a list of data source paths.
- The Validator is responsible for checking that the paths exist and that the data is "valid".
- The training code would then retrieve its data from each DataSource path.
- Some DataSource providers: DVC, Pachyderm, Databricks Delta versions, S3 or local file system with no version control, S3 or local file system with file hash check, etc.

**Comment by tfurmston** [comment]
Hi, 

What is the status on this issue? Is the approach proposed by @amesar the agreed approach? Would be great to get an understanding of these point. 

Thanks! :)

**Comment by rlizzo** [comment]
Hi Everyone, 

I am a maintainer of the [Hangar](https://github.com/tensorwerk/hangar-py) project for data versioning.

I have the same question as @tfurmston above. We'd like to integrate with ML flow, but don't have a clear picture of how to make that happen. As mentioned above, data versioning is fairly complex, and the approaches taken by each of the individual tools are wildly different. How can we work together on this? 

Thanks, 
Rick

**Comment by bachsh** [comment]
Just wanted to point out to anyone who's following this thread that I ran
into a solution called DagsHub that integrates MLFlow and DVC under the
hood to create a holistic solution for MLOps. I'm trying them out now in a
video classification project.
https://dagshub.com/

**Comment by abhiksark** [comment]
I see this to be a very old issue. Is there any update on this?

**Comment by jeanlst** [comment]
I wish, I have asked on slack and no answers there as well

**Comment by kennydataml** [comment]
would a feature store be able to replace dataset versioning? 
databricks has a feature store in-preview

**Comment by addisonklinke** [comment]
@kennydataml I've been thinking about snapshots as well. My datasets consist of static image files with CSVs containing the annotations. I'm not worried about versioning the images, only the annotations (which are ~250 MB max per CSV). Couldn't MLflow support versioned artifacts for this use case? They already have versioned MLmodels, so it seems like not much work to extend this to metadata files

**Comment by kennydataml** [comment]
I see what you're saying. it would be nice to have versioned dataset artifacts in the MLFlow GUI that can be linked to the models, but I think this is **exactly the purpose of a feature store**. Feature stores are essentially your datasets that are transformed into your curated features (I'm assuming the annotations become features for the model you create) and you can create new versions of features if you were to use a feature store.

DVC is mentioned a lot here so it might make more sense to have an approach to integrate those two tools seamlessly.
Databricks has also announced their feature store which is built on top of delta lake so it's possible that they might release this "feature store" to the public under a new open source project maybe next year? who knows 😄

**Comment by jnp** [comment]
As pointed out earlier, there are many tools and systems that could be used for data versions or snapshots including delta lake, feature stores, s3 buckets, dvc. MLFlow should work with any of them. MLFlow doesn't have to manage the data versions but it should track the exact data versions used for every run and model. We might consider adding a new API say, log_input_feature, that takes a data snapshot artifact as input. Data snapshot artifact can be specified as a URL, a version id, a timestamp and a feature descriptor. Feature descriptor could contain other metadata associated with the data source. Ideally the URL should link to the data source so that the user can navigate to data source from MLFlow UI.

**Comment by joshburt** [comment]
It seems to have been awhile since the last update.  I just wanted to chime in and agree with @jnp.  I think providing a mechanism to track some type of pointer in/to the data versioning system is sufficient and all I would reasonably expect here.

**Comment by sergey-serebryakov** [comment]
In this [thread](https://github.com/google/ml-metadata/issues/49) Ben explains the difference between `ml model` and `pipeline` metadata. MLflow is an excellent fit for the former, while libraries like [ml_metadata](https://github.com/google/ml-metadata) are well suited for the latter. We experimented with several approaches:
1. Use external service / library to track pipeline-level metadata (e.g., `ml_metadata`). Artifacts, such as datasets, models and hyperparameter search results, are represented as metadata objects stored in ml_metadata store. In particular, every artifact has a mandatory parameter URI (uniform resource identifier) that points to exact location. The `schema` component of URIs specifies where the artifact is and how it can be accessed (so MLflow and other libraries can be supported). Example URIs:
    ```
    https:///storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
    file:///mnt/datasets/imagenet
    mlflow:///runs/E4066de5ff3840a98ff00e9314eac3ac5/mnist.npz
    ```
2. Do not use any external libraries - use MLflow. This works, but not as efficient as the approach described above. We use the same artifact representations with mandatory URI fields, and store all input and output artifacts as MLflow tags (JSON strings) - `md.execution.inputs` and `md.execution.outputs`. Here, `md` stands for metadata, and `execution` is the concept from ml_metadata world. With this, we run multi-stage pipelines in MLflow tracking pipeline-level metadata and providing artifact provenance. We prototyped a simple query engine that retrieves this information and helps answer various questions such as show me all models trained on this particular dataset. But since we need to decode strings each time we execute queries, as I mention above, this is not really efficient.
3. I guess even simpler approach would be to consider input artifacts as just MLflow run parameters, and use notation similar to the one described above (URIs) to provide artifact locations.

**Comment by twmht** [comment]
any update on this?

**Comment by dbczumar** [comment]
Hi folks, the brand new ``mlflow.data`` module introduced in MLflow 2.4 provides data versioning for MLflow Tracking. Please try it out and provide feedback. Thank you for your patience and for your inputs :)

https://mlflow.org/docs/latest/python_api/mlflow.data.html

**Comment by addisonklinke** [comment]
@dbczumar That looks like a great start!

> [Dataset](https://mlflow.org/docs/latest/python_api/mlflow.data.html#mlflow.data.dataset.Dataset): Represents a dataset used in model training or evaluation, including features, targets, predictions, and **metadata such as the dataset’s name, digest (hash) schema, profile, and source**

If users want to log metadata other than the properties listed, is the suggested approach `mlflow.log_input(tags=...)`? 

Separate question - are their docs/screenshots describing how these new entities are represented in the UI? I think a lot of the former complaints were that logging a dataset as a normal parameter didn't distinguish it visually as being special
