### ISSUE TITLE
artifacts not shown in UI

### ISSUE THREAD

**Issue by LeanderK** [mlflow/mlflow#884]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: pip
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2
- **Python version**: Python 3.6.8 :: Anaconda, Inc.
- **npm version (if running the dev UI): - 
- **Exact command to reproduce**: * mlflow ui --file-store .

### Describe the problem
I have logged artifacts and can clearly see them in the file-system. `/artifacts` contains:

- `/images` with a sample for each epoch
- `architecture.txt` with a small description for the architecture.

But when I visit the mlflow-ui, it just shows: `No artifacts recorded`.

**Comment by LeanderK** [comment]
hmm, they now show up

**Comment by artiom-zayats** [comment]
Do you have any clue why this happened? fixes? 
I think I am running into the same issue 
Thanks.

**Comment by LeanderK** [comment]
I can reopen the issue if you want, it would probably raise awareness. It kinda resolves itself, they just showed up

**Comment by OrlMat** [comment]
Same issue on my side, however I do not reached state in which they show up. Instead of running UI only I am running server.

**Comment by LeanderK** [comment]
They disappeared and reemerged. Not sure why, can't reproduce it right now because they are showing again.

**Comment by LeanderK** [comment]
I have reopened the issue since it seems to be not unique to me

**Comment by vbathrin** [comment]
i do have the same problem, the artifacts exists physically but UI shows the metrics and parameters of each run but doesnt display the files from the artifacts.

i run it in a docker and kubernetes if that information helps.

**Comment by artiom-zayats** [comment]
I was able to solve the issue by editing the meta file  path. Double check you meta files path and make sure this is a valid path.

**Comment by akagan2018** [comment]
I have the same problem - artifacts not shown in UI. Im running backend-store-uri  Postgres and --default-artifact-root is local directory. I do see artifacts in the specified location, but not in UI.

**Comment by Gryshchuk** [comment]
Hello, Any updates on this?

**Comment by OrlMat** [comment]
On my side this was connected with docker itself and attaching correct volume to it. Finally, while running docker image I've mounted directory to it (lets called it /srv/mlflow_srv). What was important was how this location was mounted inside image - you should use the same path to assure that script running within docker will be seeing the same path as from outside. 

In summary, while building docker I have used following dockerfile form:
```
FROM python:3.7

RUN pip install mlflow==1.0

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri /srv/mlflow_srv \
    --default-artifact-root /srv/mlflow_srv \
    --host 0.0.0.0
```

and then, while running image I have attached and mapped local directory to image:
`docker run -p 5000:5000 -d --name mlflowsrv -v /srv/mlflow_srv:/srv/mlflow_srv --user $(id -u):1005 mlflowsrv`

On my side, also I wanted to log data from many machines to one local server. Because I was in isolated environment I simply mapped server drive with use of NFS to each machine from which I wanted to log to MLFlow (also on each of those machines server directory was mapped under /srv/mlflow_srv path. 

With that, everything is working fine and correct.

**Comment by LeanderK** [comment]
I didn't use docker, so docker can't be the problem. Just `mlflow ui --file-store .`.

**Comment by henningsway** [comment]
I currently have the same problem using mlflow 1.1.0. I use the default locations for the backend- and artifact store and the artifacts appear in the file system for each run. But they do not show up in the UI, when I start `mlflow ui`.

The training and logging is done within a docker container, the call to the ui is done afterwards outside of docker.

**Comment by mallochio** [comment]
In my case the `artifact_uri ` does seem to be a proper filepath, but the artifacts are still not visible from the UI. Windows user here.

**Comment by geoHeil** [comment]
When logging to mlflow:

```
import os
from mlflow import log_metric, log_param, log_artifact

# Log a parameter (key-value pair)
log_param("param1", 5)

# Log a metric; metrics can be updated throughout the run
log_metric("foo", 1)
log_metric("foo", 2)
log_metric("foo", 3)

# Log an artifact (output file)
with open("output.txt", "w") as f:
    f.write("Hello world!")
log_artifact("output.txt")

```
the lines above work great when running locally. But they fail to upload the artifact. Only the metadata and parameters are transferred. The artifact is missing.

docker-compose.yml
```
mlflow:
   build:
     context: my-contet
     dockerfile: mlflow.Dockerfile
   container_name: mlflow
   expose: 
      - "5000"
   ports:
     - "5000:5000"
```
with DOCKERFILE
```
FROM python:3.7.4

RUN pip install mlflow

RUN mkdir /mlflow/

CMD mlflow server \
    --backend-store-uri /mlflow \
    --default-artifact-root /mlflow \
    --host 0.0.0.0
```

**Comment by laibe** [comment]
I encounter the same issue as @geoHeil , according to [this stackoverflow](https://stackoverflow.com/questions/52331254/how-to-store-artifacts-on-a-server-running-mlflow) it's currently the expected behavior.

**Comment by monicatao** [comment]
Hi, I still have the same problem when I run `mlflow server ` and it's still unclear for me how to solve this. Any suggestion?

**Comment by ciberger** [comment]
Hi, after hours searching online I couldn't find a solution when storing artifacts locally. Strangely, my test file is located within the run's artifacts directory, but it's not shown on the mlflow UI. Tried `mlflow ui --backend-store-uri models/mlruns --default-artifact-root models/mlruns` unsuccessfully. YAML file points to the right folder. 

```python
with open('test.file', 'wb') as f:
    joblib.dump(test, f)

mlflow.set_tracking_uri('../models/mlruns')
with mlflow.start_run():
    mlflow.log_artifact('test.file')
    print(mlflow.get_artifact_uri())
mlflow.end_run()

# ./models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/artifacts
```


```batch
❯ tree models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db
models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db
├── artifacts
│   └── test.file
├── meta.yaml
├── metrics
├── params
└── tags
    ├── mlflow.source.name
    ├── mlflow.source.type
    └── mlflow.user

4 directories, 5 files

❯ cat models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/meta.yaml
artifact_uri: ../models/mlruns/0/838f9f54c9f24f13bc299bac6068b8db/artifacts
end_time: 1593590656375
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 838f9f54c9f24f13bc299bac6068b8db
```

**Comment by hughperkins** [comment]
Ok. So I had this issue. It turns out that what was happening in my own case is that it is the *client* that stores the artifacts, not the server. This means that if you have your artifact root set like:

```
artifact_location: /home/mlruns/1
```

... then the *client* will store the artifacts on its own `/home/mlruns/1` folder, not on the server's. Of course, if the server is running on a different file system than the client, then this is invisible to the server...

I assume that one must mandatorily use some shared location, such as s3 or similar. (havent tested this yet, but seems plausible).

**Comment by CzakuGim** [comment]
Same issue here, 
I'm using docker container, there the mlruns file exists with all data.
When I'm running the mlflow ui inside the containder (I'm using the vs code remote host) - the ui is working great. 
Great for me means that all data like params, metrics and artifacts are visible.
After turning off the containder, I have also possibility tu run the ui of course, params and metrics are visible but, yeah artifacts -> "No Artifacts Recorded".

The only way to solve this was to change the artifact_location in meta.yaml file but it's for sure not the solution.

Any suggestions?

**Comment by Fawzikhattar** [comment]
@CzakuGim  I have the same problem did you manage to solve it?

**Comment by Fawzikhattar** [comment]
In the end I solved it by running mlflow ui inside the same docker image

**Comment by CzakuGim** [comment]
@Fawzikhattar Not yet, I have some idea but not tested yet.
Take a look here:
https://hernandezpaul.wordpress.com/2021/01/07/running-mlflow-server-using-docker-azure-blob-service-and-azure-sql-database/

**Comment by sfc-gh-adlee** [comment]
i have the same issue running on k8. any resolution?

**Comment by coalindiax** [comment]
same issue default-artifact-root have s3 path and backend-store-uri is mysql

**Comment by Rakesh-Raushan** [comment]
> @coalindiax / @sfc-gh-adlee: facing a similar issue while running on k8s- any clue on how to fix it??
> 
> > 
> 
> * --backend-store-uri=postgresql
> * --default-artifact-root=azure-blob storage
> 
> Note: I can see that artifacts are written into the blob storage but are not able to see anything on the mlflow dashboard UI

I had this problem, solved it by installing azure-blob-storage package in the environment where I was running MLflow UI  and also setting the environment variables for blob like this:
import os
os.environ['AZURE_STORAGE_ACCOUNT'] = <storage_account_name>
os.environ['AZURE_STORAGE_KEY'] = <storage_key>
os.environ['AZURE_STORAGE_CONNECTION_STRING'] = <storage_connection_string>
os.environ['AZURE_STORAGE_AUTH_MODE'] = 'key'

I think this is a common problem that we can see everything except the artifacts in the UI. 

This happens because, apart from the artifacts, rest all that we see in the UI comes from backend_store_uri for which the credentials are passed in the backend_store_uri itself while starting the mlflow server. 

However, for artifacts_root we just pass the azure blob/container location not the credentials required to interact with them when starting the server.

Often, the server runs at a place where we have the credentials to connect to the backend_store and hence we are able to log artifacts but the UI runs at a place where we do not have credentials to connect to the backend_store and hence UI fails to load the artifacts as it is unable to establish connection to the blob.
Just try to solve your issue along these lines irrespective of the environment in which you are facing the problem

**Comment by rasika** [comment]
I had the same issue when using the file storage, when using the absolute paths; It worked perfectly.

```
mlflow server --backend-store-uri /private/tmp/ttt/expstore --default-artifact-root /private/tmp/ttt/expstore
```

**Comment by Haruki-Kny** [comment]
I had the same issue.
I used the relative path, so I changed it to the absolute path. It fixed.
To check paths,
```
print('tracking uri:', mlflow.get_tracking_uri())
print('artifact uri:', mlflow.get_artifact_uri())
```
also checked meta.yaml

**Comment by redaelhail** [comment]
I still have the same issue, I am running the ui locally and can see the artifacts files in storage but not on ui. 
I checked the meta.yaml and everything seems to be correct.

**Comment by mshajarrazip** [comment]
In my case ... I was running the training script in a dev container with vs code and forgot to properly mount the path to artifacts. So, instead of writing to the folder on host (that is mounted to the mlflow tracking server container), I was writing to the directory in the dev container only...
