### ISSUE TITLE
MLflow Client create_run & store artifacts on S3 example

### ISSUE THREAD

**Issue by FRNCSCM** [mlflow/mlflow#917]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Mojave
- **MLflow installed from (source or binary)**:  pip
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3.7
- **npm version (if running the dev UI): 6.4.1

### Describe the problem
Hi, I really would like our team to use MLFlow, but to do so, we need to run the Tracking UI on a server. Here I encounter my two problems:
- How can I run an example code (let's say train.py) so it "runs" on the server UI (i.e. hosted on 10.20.30.40:5000) 
- and stores the logs, metrics and artifacts online on S3?

I know I should use MLFlowClient for the tracking and   --default-artifact-root for the S3, but I'm not sure how to rewrite train.py so it runs my server UI, neither it seems to connect to my S3 bucket.

Any tips on any of those two topics would help a lot!

### Source code / logs
Docker Code with which I run the code on my server:
```
RUN pip install mlflow==0.8.2

WORKDIR /app/

RUN useradd -u 999 -ms /bin/bash theuser 
RUN usermod -aG sudo theuser 
RUN passwd -d theuser

CMD mlflow server \
    --file-store s3://${BUCKET}/test \
    --default-artifact-root s3://${BUCKET}/test \
    --host 10.20.30.40.```

**Comment by dstine** [comment]
@FRNCSCM 

Note that the artifact location for an experiment is set at the time the experiment is created.

If you use the `experiments create --artifact-location TEXT` approach, this wins over the default from the server.

Otherwise, the default from the server will be used, which is the value you set above with `--default-artifact-root`.

For S3, you will have to configure appropriate credentials on both client and server (cc: #629).

You can see the location by inspecting the experiment configuration on the server:
```
$ grep artifact_location mlruns/[experiment_id]/meta.yaml
artifact_location: s3://my-bucket/my-subdir
```
