### ISSUE TITLE
Standardize HTTP status codes across MLflow REST API implementations

### ISSUE THREAD

**Issue by smurching** [mlflow/mlflow#993]
We may want to consider standardizing on HTTP status codes for errors common across implementations of the API (too many metrics, param value too large, failure to overwrite a param, internal error while persisting a metric/param/tag). From the OSS client perspective, we currently need only specify which errors are 400-level vs 500-level, in that the OSS rest client (RestStore) currently retries on 500-level errors but not 400-level errors. However it could be nice for users to see a consistent set of response status codes across API implementations. Currently the OSS server is only capable of responding with 500 Internal Server Error, so this is new logic we'll need to add.

**Comment by acroz** [comment]
Thanks for requesting our input on this @smurching.

Since we are implementing a backend that is tightly integrated with [our platform](https://faculty.ai/products-services/platform/), we have opted not to use the REST interface laid out in the library. Instead, we are implementing our own tracking store that users will use by installing [our MLflow plugin](https://github.com/facultyai/mlflow-faculty/), and so the interface we will rely on is in Python rather than at the REST level.

That said, having the OSS server return non-500 error codes in appropriate situations sounds valuable. I don't have strong feelings on what those codes should be, beyond using standard HTTP codes were relevant (404 for resources not existing, etc.).

**Comment by smurching** [comment]
@acroz got it, that makes sense - we'll look into updating some of the OSS error codes in an upcoming release :)
